<?php
namespace Pterodactyl\Http\Controllers\Admin;
use Illuminate\Http\Request; use Illuminate\Support\Facades\Crypt; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema; use Illuminate\Support\Str; use Pterodactyl\Http\Controllers\Controller;
class CommerceController extends Controller {
 public function billing(){ $invoices=Schema::hasTable('invoices')?DB::table('invoices')->orderByDesc('id')->limit(100)->get():collect();$orders=Schema::hasTable('billing_orders')?DB::table('billing_orders')->orderByDesc('id')->limit(100)->get():collect();$products=Schema::hasTable('billing_products')?DB::table('billing_products')->orderBy('sort_order')->orderBy('name')->get():collect();$categories=Schema::hasTable('billing_categories')?DB::table('billing_categories')->orderBy('sort_order')->orderBy('name')->get():collect();$gateways=Schema::hasTable('payment_gateways')?DB::table('payment_gateways')->orderBy('sort_order')->get():collect();return view('admin.commerce.billing',compact('invoices','orders','products','categories','gateways'));}
 public function payments(){ $gateways=Schema::hasTable('payment_gateways')?DB::table('payment_gateways')->orderBy('sort_order')->get():collect();return view('admin.commerce.payments',compact('gateways'));}
 public function orders(Request $r){$q=DB::table('billing_orders as o')->leftJoin('users as u','u.id','=','o.user_id')->leftJoin('billing_products as p','p.id','=','o.product_id')->select('o.*','u.username','u.email','p.name as product_name','p.product_type');if($r->filled('status'))$q->where('o.status',$r->input('status'));if($r->filled('search')){$s='%'.$r->input('search').'%';$q->where(function($x)use($s){$x->where('u.username','like',$s)->orWhere('u.email','like',$s)->orWhere('p.name','like',$s)->orWhere('o.id','like',$s);});}$orders=$q->orderByDesc('o.id')->limit(250)->get();return view('admin.commerce.orders',compact('orders'));}
 public function updateOrder(Request $r,int $id){$d=$r->validate(['status'=>'required|in:pending,paid,processing,completed,cancelled,refunded']);$order=DB::table('billing_orders')->where('id',$id)->first();abort_unless($order,404);DB::transaction(function()use($id,$d){DB::table('billing_orders')->where('id',$id)->update(['status'=>$d['status'],'updated_at'=>now()]);if(in_array($d['status'],['paid','completed'],true))DB::table('invoices')->where('order_id',$id)->update(['status'=>'paid','paid_at'=>now(),'updated_at'=>now()]);if($d['status']==='cancelled')DB::table('vps_services')->where('order_id',$id)->where('status','awaiting_payment')->update(['status'=>'cancelled','updated_at'=>now()]);});return back()->with('success','Ordre #'.$id.' blev opdateret.');}
 public function deleteOrder(int $id){$order=DB::table('billing_orders')->where('id',$id)->first();abort_unless($order,404);$activeVps=Schema::hasTable('vps_services')&&DB::table('vps_services')->where('order_id',$id)->whereNotIn('status',['awaiting_payment','pending','cancelled'])->exists();if($activeVps)return back()->withErrors(['order'=>'Ordren har en aktiv/provisioneret VPS og kan derfor ikke slettes. Stop eller fjern VPS’en først.']);DB::transaction(function()use($id){$invoiceIds=DB::table('invoices')->where('order_id',$id)->pluck('id');if(Schema::hasTable('invoice_items')&&$invoiceIds->isNotEmpty())DB::table('invoice_items')->whereIn('invoice_id',$invoiceIds)->delete();if(Schema::hasTable('billing_transactions'))DB::table('billing_transactions')->whereIn('invoice_id',$invoiceIds)->delete();if(Schema::hasTable('vps_services'))DB::table('vps_services')->where('order_id',$id)->whereIn('status',['awaiting_payment','pending','cancelled'])->delete();DB::table('invoices')->where('order_id',$id)->delete();DB::table('billing_orders')->where('id',$id)->delete();});return back()->with('success','Ordre #'.$id.' og den tilhørende ubetalte faktura blev slettet.');}
 public function storeCategory(Request $r){$d=$r->validate(['name'=>'required|string|max:100','description'=>'nullable|string|max:1000','sort_order'=>'nullable|integer|min:0|max:9999']);DB::table('billing_categories')->insert(['name'=>$d['name'],'slug'=>$this->uniqueSlug('billing_categories',$d['name']),'description'=>$d['description']??null,'sort_order'=>$d['sort_order']??0,'active'=>$r->boolean('active',true),'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Kategorien blev oprettet.');}
 public function updateCategory(Request $r,int $id){$d=$r->validate(['name'=>'required|string|max:100','description'=>'nullable|string|max:1000','sort_order'=>'nullable|integer|min:0|max:9999']);DB::table('billing_categories')->where('id',$id)->update(['name'=>$d['name'],'description'=>$d['description']??null,'sort_order'=>$d['sort_order']??0,'active'=>$r->boolean('active'),'updated_at'=>now()]);return back()->with('success','Kategorien blev gemt.');}
 public function deleteCategory(int $id){DB::table('billing_products')->where('category_id',$id)->update(['category_id'=>null]);DB::table('billing_categories')->where('id',$id)->delete();return back()->with('success','Kategorien blev slettet.');}
 public function storeProduct(Request $r){$d=$this->validateProduct($r);DB::table('billing_products')->insert(array_merge($this->productData($r,$d),['slug'=>$this->uniqueSlug('billing_products',$d['name']),'created_at'=>now(),'updated_at'=>now()]));return back()->with('success','Pakken blev oprettet.');}
 public function updateProduct(Request $r,int $id){$d=$this->validateProduct($r);DB::table('billing_products')->where('id',$id)->update(array_merge($this->productData($r,$d),['updated_at'=>now()]));return back()->with('success','Pakken blev gemt.');}
 public function deleteProduct(int $id){if(DB::table('billing_orders')->where('product_id',$id)->exists()){DB::table('billing_products')->where('id',$id)->update(['active'=>false,'updated_at'=>now()]);return back()->with('success','Pakken har eksisterende ordrer og blev deaktiveret.');}DB::table('billing_products')->where('id',$id)->delete();return back()->with('success','Pakken blev slettet.');}
 public function saveGateway(Request $r,string $gateway){if(!in_array($gateway,['stripe','mobilepay','paypal'],true))abort(404);if(!Schema::hasTable('payment_gateways'))return back()->withErrors(['payment'=>'Betalingstabellen mangler. Kør Nodexa updateren/migrations først.']);$d=$r->validate(['name'=>'required|string|max:80','public_key'=>'nullable|string|max:2000','secret_key'=>'nullable|string|max:2000','webhook_secret'=>'nullable|string|max:2000','merchant_id'=>'nullable|string|max:2000','client_id'=>'nullable|string|max:2000','client_secret'=>'nullable|string|max:2000','sort_order'=>'nullable|integer|min:0|max:9999']);$old=DB::table('payment_gateways')->where('gateway',$gateway)->first();$data=['name'=>$d['name'],'enabled'=>$r->boolean('enabled'),'test_mode'=>$r->boolean('test_mode'),'sort_order'=>$d['sort_order']??0,'updated_at'=>now()];foreach(['public_key','secret_key','webhook_secret','merchant_id','client_id','client_secret'] as $key){if($r->filled($key))$data[$key]=Crypt::encryptString((string)$r->input($key));else if(!$old)$data[$key]=null;}if($old)DB::table('payment_gateways')->where('gateway',$gateway)->update($data);else DB::table('payment_gateways')->insert(array_merge($data,['gateway'=>$gateway,'created_at'=>now()]));return back()->with('success',$d['name'].' blev gemt.');}
 public function tickets(){ $tickets=Schema::hasTable('tickets')?DB::table('tickets')->orderByDesc('updated_at')->limit(100)->get():collect();return view('admin.commerce.tickets',compact('tickets'));}
 private function validateProduct(Request $r):array{return $r->validate(['name'=>'required|string|max:120','description'=>'nullable|string|max:2000','category_id'=>'nullable|integer|exists:billing_categories,id','product_type'=>'nullable|in:game,vps','provider_product_id'=>'nullable|string|max:100','default_os_id'=>'nullable|string|max:100','vcores'=>'nullable|integer|min:1|max:256','price'=>'required|numeric|min:0|max:999999.99','currency'=>'required|string|size:3','billing_cycle'=>'required|in:monthly,quarterly,semiannually,annually,one_time','memory_mb'=>'nullable|integer|min:0|max:1048576','disk_mb'=>'nullable|integer|min:0|max:10485760','cpu_percent'=>'nullable|integer|min:0|max:100000','databases_limit'=>'nullable|integer|min:0|max:1000','backups_limit'=>'nullable|integer|min:0|max:1000','allocations_limit'=>'nullable|integer|min:0|max:1000','sort_order'=>'nullable|integer|min:0|max:9999']);}
 private function productData(Request $r,array $d):array{$type=$d['product_type']??'game';return ['name'=>$d['name'],'description'=>$d['description']??null,'category_id'=>$d['category_id']??null,'product_type'=>$type,'provider_product_id'=>$type==='vps'?($d['provider_product_id']??null):null,'default_os_id'=>$type==='vps'?($d['default_os_id']??null):null,'vcores'=>$type==='vps'?($d['vcores']??null):null,'price'=>$d['price'],'currency'=>strtoupper($d['currency']),'billing_cycle'=>$d['billing_cycle'],'active'=>$r->boolean('active'),'memory_mb'=>$d['memory_mb']??null,'disk_mb'=>$d['disk_mb']??null,'cpu_percent'=>$d['cpu_percent']??null,'databases_limit'=>$d['databases_limit']??0,'backups_limit'=>$d['backups_limit']??0,'allocations_limit'=>$d['allocations_limit']??1,'sort_order'=>$d['sort_order']??0,'provisioning'=>json_encode(['type'=>$type,'provider'=>'flax','product_id'=>$d['provider_product_id']??null,'os_id'=>$d['default_os_id']??null,'vcores'=>$d['vcores']??null,'memory_mb'=>$d['memory_mb']??null,'disk_mb'=>$d['disk_mb']??null,'cpu_percent'=>$d['cpu_percent']??null])];}
 private function uniqueSlug(string $table,string $name):string{$base=Str::slug($name)?:'item';$slug=$base;$i=2;while(DB::table($table)->where('slug',$slug)->exists())$slug=$base.'-'.$i++;return $slug;}
}
