<?php
namespace Pterodactyl\Http\Controllers\Admin;
use Illuminate\Http\Request;use Illuminate\Http\RedirectResponse;use Illuminate\Support\Facades\Artisan;use Illuminate\Support\Facades\File;use Illuminate\Support\Facades\Http;use Illuminate\View\View;use Prologue\Alerts\AlertsMessageBag;use Pterodactyl\Http\Controllers\Controller;
class DiscordBotController extends Controller{
 public function __construct(private AlertsMessageBag $alert){}
 private function definitions():array{
  $memberVars=['user'=>'Brugernavn','mention'=>'Nævner medlemmet','username'=>'Discord-brugernavn','display_name'=>'Visningsnavn','user_id'=>'Discord bruger-ID','avatar'=>'Avatar URL','server'=>'Servernavn','server_id'=>'Discord server-ID','member_count'=>'Antal medlemmer','member_number'=>'Medlemmets nummer','created_at'=>'Konto oprettet','joined_at'=>'Dato medlemmet joinede','account_age'=>'Kontoens alder','role_count'=>'Antal roller','date'=>'Dato','time'=>'Tid'];
  $core=[
   'welcome'=>['icon'=>'fa-sign-in','title'=>'Welcome / Goodbye','description'=>'Send velkomst- og farvelbeskeder.','fields'=>['channel_id'=>'Kanal','message'=>'Velkomstbesked','goodbye_message'=>'Farvelbesked'],'variables'=>$memberVars],
   'auto_role'=>['icon'=>'fa-user-plus','title'=>'Auto Role','description'=>'Giv automatisk en rolle til nye medlemmer.','fields'=>['role_id'=>'Rolle']],
   'tickets'=>['icon'=>'fa-ticket','title'=>'Tickets','description'=>'Avanceret ticket-system med panel, kategorier, staff, logs og automatisering.','fields'=>['ticket_templates'=>'Ticket templates','ticket_template_settings'=>'Template indstillinger','panel_channel_id'=>'Ticket panel kanal','category_id'=>'Åbne tickets kategori','closed_category_id'=>'Lukkede tickets kategori','staff_role_id'=>'Staff rolle','support_role_id'=>'Support rolle','log_channel_id'=>'Ticket log kanal','transcript_channel_id'=>'Transcript kanal','panel_title'=>'Panel titel','panel_message'=>'Panel besked','button_label'=>'Opret ticket-knap','ticket_name'=>'Kanalnavn format','welcome_message'=>'Besked i ny ticket','close_message'=>'Besked ved lukning','max_tickets'=>'Maks. åbne tickets pr. bruger','auto_close_hours'=>'Auto-luk efter inaktivitet (timer)','claim_enabled'=>'Tillad staff at claime tickets','transcript_enabled'=>'Gem transcript ved lukning','dm_transcript'=>'Send transcript til bruger i DM','require_reason'=>'Kræv årsag ved oprettelse'],'variables'=>array_merge($memberVars,['ticket_id'=>'Ticket-ID','ticket_channel'=>'Ticket-kanal','ticket_reason'=>'Årsag til ticket','ticket_created_at'=>'Ticket oprettet','ticket_closed_at'=>'Ticket lukket','claimer'=>'Staff der har claimet ticket','closer'=>'Staff der lukker ticket'])],
   'moderation'=>['icon'=>'fa-shield','title'=>'Moderation & Safety','description'=>'Professionelt Trust & Safety-center med AutoMod, anti-raid, cases, strafpolitik og audit logs.','fields'=>['log_channel_id'=>'Primær moderation log','automod_log_channel_id'=>'AutoMod log kanal','member_log_channel_id'=>'Medlems log kanal','case_log_channel_id'=>'Case log kanal','moderator_role_id'=>'Moderator rolle','senior_moderator_role_id'=>'Senior Moderator rolle','admin_role_id'=>'Administrator rolle','automod_enabled'=>'AutoMod','spam_enabled'=>'Spam / flood detection','duplicate_enabled'=>'Gentagne beskeder','caps_enabled'=>'Overdreven CAPS','emoji_enabled'=>'Emoji spam','mention_enabled'=>'Mention spam','invite_enabled'=>'Discord invites','links_enabled'=>'Links / domæner','blacklist_enabled'=>'Blacklistede ord','scam_enabled'=>'Scam / phishing mønstre','spam_limit'=>'Maks beskeder pr. interval','spam_interval'=>'Spam interval (sek.)','mention_limit'=>'Maks mentions pr. besked','caps_percent'=>'CAPS grænse (%)','duplicate_limit'=>'Gentagelsesgrænse','blocked_words'=>'Blacklistede ord (komma-separeret)','allowed_domains'=>'Tilladte domæner (komma-separeret)','antiraid_enabled'=>'Anti-Raid','raid_join_limit'=>'Join-grænse','raid_interval'=>'Join interval (sek.)','min_account_age_hours'=>'Minimum kontoalder (timer)','auto_lockdown'=>'Automatisk lockdown','raid_slowmode'=>'Raid slowmode (sek.)','warn_expiry_days'=>'Warn udløber efter (dage)','warn_3_action'=>'Handling ved 3 warns','warn_5_action'=>'Handling ved 5 warns','warn_7_action'=>'Handling ved 7 warns','warn_10_action'=>'Handling ved 10 warns','default_timeout_minutes'=>'Standard timeout (min.)','require_reason'=>'Kræv begrundelse','case_system_enabled'=>'Case-system','appeals_enabled'=>'Ban Appeals','audit_enabled'=>'Audit logging','dm_punishments'=>'DM bruger ved straf','exempt_roles'=>'Undtagede rolle-ID’er','exempt_channels'=>'Undtagede kanal-ID’er','exempt_users'=>'Undtagede bruger-ID’er']],
   'logs'=>['icon'=>'fa-list-alt','title'=>'Logs','description'=>'Log joins, leaves og Discord-hændelser.','fields'=>['channel_id'=>'Log kanal']],
   'server_status'=>['icon'=>'fa-server','title'=>'Server Status','description'=>'Vis status for Nodexa/game-servere i Discord.','fields'=>['channel_id'=>'Status kanal','refresh_interval'=>'Opdateringsinterval (sekunder)']],
   'announcements'=>['icon'=>'fa-bullhorn','title'=>'Announcements','description'=>'Send announcements fra Nodexa til Discord.','fields'=>['channel_id'=>'Announcement kanal']],
   'verification'=>['icon'=>'fa-check-circle','title'=>'Verification','description'=>'Verificér medlemmer og tildel en rolle.','fields'=>['channel_id'=>'Kanal','role_id'=>'Verificeret rolle','message'=>'Verification besked'],'variables'=>array_merge($memberVars,['role'=>'Verificeringsrolle','role_id'=>'Verificeringsrolle-ID'])],
   'commands'=>['icon'=>'fa-terminal','title'=>'Commands','description'=>'Aktivér bot slash-commands.','fields'=>['prefix'=>'Fallback prefix']]
  ];
  $community=config('discord-community-modules',[]);return array_merge($core,is_array($community)?$community:[]);
 }
 public function index():View{$bot=config('nodexa.discord_bot',[]);$status=['connected'=>false,'name'=>null,'avatar'=>null,'guild'=>null,'error'=>null];$token=(string)($bot['token']??'');if(($bot['enabled']??false)&&$token!==''){try{$user=Http::withHeaders(['Authorization'=>'Bot '.$token])->timeout(5)->get('https://discord.com/api/v10/users/@me');if($user->successful()){$json=$user->json();$status['connected']=true;$status['name']=$json['username']??'Discord Bot';}}catch(\Throwable $e){$status['error']='Kunne ikke forbinde til Discord.';}}return view('admin.discord-bot.index',['bot'=>$bot,'hasToken'=>$token!=='','status'=>$status]);}
 public function update(Request $request):RedirectResponse{$data=$request->validate(['enabled'=>'nullable|boolean','token'=>'nullable|string|max:255','client_id'=>'nullable|string|max:100','guild_id'=>'nullable|string|max:100','status_channel_id'=>'nullable|string|max:100','auto_role_id'=>'nullable|string|max:100','presence'=>'nullable|string|max:128']);$values=['NODEXA_DISCORD_BOT_ENABLED'=>$request->boolean('enabled')?'true':'false','NODEXA_DISCORD_BOT_CLIENT_ID'=>trim((string)($data['client_id']??'')),'NODEXA_DISCORD_BOT_GUILD_ID'=>trim((string)($data['guild_id']??'')),'NODEXA_DISCORD_BOT_STATUS_CHANNEL_ID'=>trim((string)($data['status_channel_id']??'')),'NODEXA_DISCORD_BOT_AUTO_ROLE_ID'=>trim((string)($data['auto_role_id']??'')),'NODEXA_DISCORD_BOT_PRESENCE'=>trim((string)($data['presence']??'Nodexa Hosting'))];if(filled($data['token']??null))$values['NODEXA_DISCORD_BOT_TOKEN']=trim($data['token']);$this->writeEnv($values);Artisan::call('config:clear');$this->alert->success('Discord Bot-indstillingerne er gemt.')->flash();return redirect()->route('admin.discord-bot');}
 public function modules():View{return view('admin.discord-bot.modules',['modules'=>$this->moduleConfig(),'definitions'=>$this->definitions()]);}
 public function module(string $module):View{$definitions=$this->definitions();abort_unless(isset($definitions[$module]),404);$modules=$this->moduleConfig();$discord=$this->discordOptions();$view=$module==='social_notifications'?'admin.discord-bot.social-notifications':'admin.discord-bot.module';return view($view,['key'=>$module,'module'=>$definitions[$module],'config'=>$modules[$module]??[],'channels'=>$discord['channels'],'categories'=>$discord['categories'],'roles'=>$discord['roles'],'discordError'=>$discord['error']]);}
 public function updateModule(Request $request,string $module):RedirectResponse{$definitions=$this->definitions();abort_unless(isset($definitions[$module]),404);$all=$this->moduleConfig();$data=['enabled'=>$request->boolean('enabled')];$booleanFields=['claim_enabled','transcript_enabled','dm_transcript','require_reason','automod_enabled','spam_enabled','duplicate_enabled','caps_enabled','emoji_enabled','mention_enabled','invite_enabled','links_enabled','blacklist_enabled','scam_enabled','antiraid_enabled','auto_lockdown','case_system_enabled','appeals_enabled','audit_enabled','dm_punishments'];foreach(array_keys($definitions[$module]['fields']) as $field){if($field==='ticket_templates'){$raw=json_decode((string)$request->input($field,'[]'),true);$allowed=['support','billing','technical','report','staff','ban','whitelist','partner','other'];$raw=is_array($raw)?array_values(array_unique(array_intersect($allowed,$raw))):[];$data[$field]=json_encode($raw,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);continue;}if($field==='ticket_template_settings'){$raw=json_decode((string)$request->input($field,'{}'),true);$clean=[];$allowed=['support','billing','technical','report','staff','ban','whitelist','partner','other'];if(is_array($raw))foreach($allowed as $k){if(!is_array($raw[$k]??null))continue;$clean[$k]=['emoji'=>mb_substr(trim((string)($raw[$k]['emoji']??'')),0,16),'name'=>mb_substr(trim((string)($raw[$k]['name']??$k)),0,60),'description'=>mb_substr(trim((string)($raw[$k]['description']??'')),0,180)];}$data[$field]=json_encode($clean,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);continue;}$data[$field]=in_array($field,$booleanFields,true)?$request->boolean($field):trim((string)$request->input($field,''));}$all[$module]=$data;$this->saveModules($all);$this->alert->success($definitions[$module]['title'].' er gemt.')->flash();return redirect()->route('admin.discord-bot.modules.module',['module'=>$module]);}
 public function updateModules(Request $request):RedirectResponse{$all=$this->moduleConfig();foreach(array_keys($this->definitions()) as $key)$all[$key]=array_merge($all[$key]??[],['enabled'=>$request->boolean('modules.'.$key.'.enabled')]);$this->saveModules($all);$this->alert->success('Module-status er gemt.')->flash();return redirect()->route('admin.discord-bot.modules');}
 public function test():RedirectResponse{$token=(string)config('nodexa.discord_bot.token');if($token===''){$this->alert->danger('Der er ikke gemt et Bot Token.')->flash();return redirect()->route('admin.discord-bot');}try{$response=Http::withHeaders(['Authorization'=>'Bot '.$token])->timeout(5)->get('https://discord.com/api/v10/users/@me');if($response->successful())$this->alert->success('Forbindelsen til Discord virker.')->flash();else$this->alert->danger('Discord afviste bot-tokenet.')->flash();}catch(\Throwable $e){$this->alert->danger('Kunne ikke kontakte Discord API.')->flash();}return redirect()->route('admin.discord-bot');}
 private function discordOptions():array{$out=['channels'=>[],'categories'=>[],'roles'=>[],'error'=>null];$token=(string)config('nodexa.discord_bot.token');$guild=(string)config('nodexa.discord_bot.guild_id');if($token===''||$guild===''){$out['error']='Gem Bot Token og Discord Server ID først.';return $out;}try{$headers=['Authorization'=>'Bot '.$token];$channels=Http::withHeaders($headers)->timeout(7)->get('https://discord.com/api/v10/guilds/'.$guild.'/channels');$roles=Http::withHeaders($headers)->timeout(7)->get('https://discord.com/api/v10/guilds/'.$guild.'/roles');if(!$channels->successful()||!$roles->successful()){$out['error']='Kunne ikke hente Discord-kanaler og roller.';return $out;}foreach($channels->json() as $c){$type=(int)($c['type']??-1);$row=['id'=>(string)$c['id'],'name'=>(string)($c['name']??$c['id']),'type'=>$type,'position'=>(int)($c['position']??0)];if($type===4)$out['categories'][]=$row;elseif(in_array($type,[0,2,5,13,15,16],true))$out['channels'][]=$row;}foreach($roles->json() as $r){if(($r['name']??'')==='@everyone')continue;$out['roles'][]=['id'=>(string)$r['id'],'name'=>(string)($r['name']??$r['id']),'position'=>(int)($r['position']??0),'color'=>(int)($r['color']??0)];}usort($out['channels'],fn($a,$b)=>$a['position']<=>$b['position']);usort($out['categories'],fn($a,$b)=>$a['position']<=>$b['position']);usort($out['roles'],fn($a,$b)=>$b['position']<=>$a['position']);}catch(\Throwable $e){$out['error']='Discord API kunne ikke kontaktes.';}return $out;}
 private function moduleConfig():array{$path=storage_path('app/nodexa/discord-bot-modules.json');if(!File::exists($path))return [];$d=json_decode(File::get($path),true);return is_array($d)?$d:[];}
 private function saveModules(array $data):void{$path=storage_path('app/nodexa/discord-bot-modules.json');File::ensureDirectoryExists(dirname($path));File::put($path,json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
 private function writeEnv(array $values):void{$path=base_path('.env');$contents=File::exists($path)?File::get($path):'';foreach($values as $key=>$value){$escaped='"'.addcslashes($value,"\\\"").'"';$line=$key.'='.$escaped;if(preg_match('/^'.preg_quote($key,'/').'=.*$/m',$contents))$contents=preg_replace('/^'.preg_quote($key,'/').'=.*$/m',$line,$contents);else$contents=rtrim($contents).PHP_EOL.$line.PHP_EOL;}File::put($path,$contents);}
}
