<?php
namespace Pterodactyl\Http\Controllers\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Pterodactyl\Http\Controllers\Controller;
class PlatformController extends Controller {
 public function notifications(){ $items=collect(); if(Schema::hasTable('invoices')){foreach(DB::table('invoices')->where('status','unpaid')->whereNotNull('due_at')->where('due_at','<',now())->orderBy('due_at')->limit(20)->get() as $x)$items->push((object)['type'=>'invoice','title'=>'Forfalden faktura #'.$x->id,'text'=>'En faktura er forfalden og kræver opmærksomhed.','at'=>$x->due_at]);} if(Schema::hasTable('billing_orders')){foreach(DB::table('billing_orders')->whereIn('status',['pending','paid','processing'])->orderByDesc('id')->limit(20)->get() as $x)$items->push((object)['type'=>'order','title'=>'Ordre #'.$x->id,'text'=>'Ordren afventer behandling/provisioning.','at'=>$x->created_at]);} if(Schema::hasTable('tickets')){foreach(DB::table('tickets')->whereNotIn('status',['closed','resolved'])->orderByDesc('updated_at')->limit(20)->get() as $x)$items->push((object)['type'=>'ticket','title'=>'Åben ticket #'.$x->id,'text'=>'Ticketen venter på behandling.','at'=>$x->updated_at]);} return view('admin.platform.notifications',['items'=>$items->sortByDesc('at')->values()]); }
 public function security(){ $stats=['admins'=>Schema::hasTable('users')?DB::table('users')->where('root_admin',true)->count():0,'users'=>Schema::hasTable('users')?DB::table('users')->count():0,'api_keys'=>Schema::hasTable('api_keys')?DB::table('api_keys')->count():0,'sessions'=>Schema::hasTable('sessions')?DB::table('sessions')->count():0]; return view('admin.platform.security',compact('stats')); }
 public function analytics(){ $hasInvoices=Schema::hasTable('invoices');$hasOrders=Schema::hasTable('billing_orders');$hasUsers=Schema::hasTable('users');$hasVps=Schema::hasTable('vps_services');$hasServers=Schema::hasTable('servers');$months=collect(range(5,0))->map(function($i)use($hasInvoices){$d=now()->subMonths($i);$paid=$hasInvoices?(float)DB::table('invoices')->where('status','paid')->whereYear('paid_at',$d->year)->whereMonth('paid_at',$d->month)->sum('total'):0;return ['label'=>$d->format('M Y'),'paid'=>$paid];});$thisMonth=$months->last()['paid']??0;$previous=$months->count()>1?($months->slice(-2,1)->first()['paid']??0):0;$growth=$previous>0?round((($thisMonth-$previous)/$previous)*100,1):($thisMonth>0?100:0);$metrics=['revenue_6m'=>(float)$months->sum('paid'),'revenue_month'=>(float)$thisMonth,'growth'=>$growth,'customers'=>$hasUsers?DB::table('users')->count():0,'orders'=>$hasOrders?DB::table('billing_orders')->count():0,'pending_orders'=>$hasOrders?DB::table('billing_orders')->whereIn('status',['pending','paid','processing'])->count():0,'vps'=>$hasVps?DB::table('vps_services')->count():0,'game_servers'=>$hasServers?DB::table('servers')->count():0,'unpaid'=>$hasInvoices?DB::table('invoices')->whereIn('status',['unpaid','overdue'])->count():0];$orderStatuses=$hasOrders?DB::table('billing_orders')->select('status',DB::raw('COUNT(*) as total'))->groupBy('status')->pluck('total','status'):collect();return view('admin.platform.analytics',compact('months','metrics','orderStatuses')); }
 public function status(){
  $nodes=Schema::hasTable('nodes')?DB::table('nodes')->select('id','name','fqdn','scheme','daemonListen','maintenance_mode')->orderBy('name')->get():collect();
  $hasHistory=Schema::hasTable('nodexa_node_health_checks');
  $nodes=$nodes->map(function($node)use($hasHistory){$node->reachable=null;$node->latency_ms=null;$node->checked_at=null;$node->uptime_24h=null;$node->checks_24h=0;if($hasHistory){$latest=DB::table('nodexa_node_health_checks')->where('node_id',$node->id)->orderByDesc('checked_at')->first();if($latest){$node->reachable=(bool)$latest->reachable;$node->latency_ms=$latest->latency_ms;$node->checked_at=$latest->checked_at;}$since=now()->subDay();$total=DB::table('nodexa_node_health_checks')->where('node_id',$node->id)->where('checked_at','>=',$since)->count();$up=DB::table('nodexa_node_health_checks')->where('node_id',$node->id)->where('checked_at','>=',$since)->where('reachable',true)->count();$node->checks_24h=$total;$node->uptime_24h=$total>0?round(($up/$total)*100,2):null;}return $node;});
  $serverStats=['total'=>Schema::hasTable('servers')?DB::table('servers')->count():0,'suspended'=>Schema::hasTable('servers')?DB::table('servers')->where('status','suspended')->count():0,'failed'=>Schema::hasTable('servers')?DB::table('servers')->whereIn('status',['install_failed','reinstall_failed'])->count():0];
  $nodeHealth=['reachable'=>$nodes->where('reachable',true)->count(),'unreachable'=>$nodes->where('reachable',false)->count(),'checked'=>$nodes->whereNotNull('reachable')->count(),'history_enabled'=>$hasHistory];
  return view('admin.platform.status',compact('nodes','serverStats','nodeHealth'));
 }
}
