<?php
namespace Pterodactyl\Http\Controllers\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Pterodactyl\Http\Controllers\Controller;
class PlatformController extends Controller {
 public function notifications(){ $items=collect(); if(Schema::hasTable('invoices')){foreach(DB::table('invoices')->where('status','unpaid')->whereNotNull('due_at')->where('due_at','<',now())->orderBy('due_at')->limit(20)->get() as $x)$items->push((object)['type'=>'invoice','title'=>'Forfalden faktura #'.$x->id,'text'=>'En faktura er forfalden og kræver opmærksomhed.','at'=>$x->due_at]);} if(Schema::hasTable('billing_orders')){foreach(DB::table('billing_orders')->whereIn('status',['pending','paid','processing'])->orderByDesc('id')->limit(20)->get() as $x)$items->push((object)['type'=>'order','title'=>'Ordre #'.$x->id,'text'=>'Ordren afventer behandling/provisioning.','at'=>$x->created_at]);} if(Schema::hasTable('tickets')){foreach(DB::table('tickets')->whereNotIn('status',['closed','resolved'])->orderByDesc('updated_at')->limit(20)->get() as $x)$items->push((object)['type'=>'ticket','title'=>'Åben ticket #'.$x->id,'text'=>'Ticketen venter på behandling.','at'=>$x->updated_at]);} return view('admin.platform.notifications',['items'=>$items->sortByDesc('at')->values()]); }
 public function security(){ $stats=['admins'=>Schema::hasTable('users')?DB::table('users')->where('root_admin',true)->count():0,'users'=>Schema::hasTable('users')?DB::table('users')->count():0,'api_keys'=>Schema::hasTable('api_keys')?DB::table('api_keys')->count():0,'sessions'=>Schema::hasTable('sessions')?DB::table('sessions')->count():0]; return view('admin.platform.security',compact('stats')); }
 public function analytics(){ $months=collect(range(5,0))->map(function($i){$d=now()->subMonths($i);$paid=Schema::hasTable('invoices')?(float)DB::table('invoices')->where('status','paid')->whereYear('paid_at',$d->year)->whereMonth('paid_at',$d->month)->sum('total'):0;return ['label'=>$d->format('M Y'),'paid'=>$paid];}); return view('admin.platform.analytics',['months'=>$months]); }
 public function status(){ $nodes=Schema::hasTable('nodes')?DB::table('nodes')->select('id','name','fqdn','maintenance_mode')->orderBy('name')->get():collect();$serverStats=['total'=>Schema::hasTable('servers')?DB::table('servers')->count():0,'suspended'=>Schema::hasTable('servers')?DB::table('servers')->where('status','suspended')->count():0,'failed'=>Schema::hasTable('servers')?DB::table('servers')->whereIn('status',['install_failed','reinstall_failed'])->count():0];return view('admin.platform.status',compact('nodes','serverStats')); }
}
