<?php

namespace Pterodactyl\Http\Controllers\Admin;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\View\View;
use Pterodactyl\Http\Controllers\Controller;
use Symfony\Component\Process\Process;

class UpdateController extends Controller
{
    private const STATE_DIR='/var/lib/nodexa'; private const VERSION_FILE=self::STATE_DIR.'/version.json'; private const STATE_FILE=self::STATE_DIR.'/update-state.json';
    public function index(): View { $installed=$this->installedVersion(); $latest=$this->latestVersion($installed,true); $state=$this->updateState(); return view('admin.updates.index',['installed'=>$installed,'latest'=>$latest,'state'=>$state,'changelog'=>$this->changelog($installed),'updateAvailable'=>$this->updateAvailable($installed,$latest)]); }
    public function status(): JsonResponse { $installed=$this->installedVersion(); $latest=$this->latestVersion($installed); return response()->json(['state'=>$this->updateState(),'installed'=>$installed,'latest'=>$latest,'update_available'=>$this->updateAvailable($installed,$latest)]); }
    public function run(): RedirectResponse { $state=$this->updateState(); if(($state['status']??'idle')==='running')return redirect()->route('admin.updates')->with('update_message','En Nodexa-opdatering kører allerede.'); $installed=$this->installedVersion(); $latest=$this->latestVersion($installed,true); if(!$this->updateAvailable($installed,$latest))return redirect()->route('admin.updates')->with('update_message','Nodexa er allerede opdateret til den nyeste GitHub-version.'); $trigger='/usr/local/sbin/nodexa-update-trigger'; if(!is_executable($trigger))return redirect()->route('admin.updates')->with('update_error','Nodexa update-triggeren er ikke installeret på denne server. Kør setup-updater.sh som root.'); $process=new Process(['/usr/bin/sudo',$trigger]); $process->setTimeout(15); $process->run(); if(!$process->isSuccessful()){ $error=trim($process->getErrorOutput()?:$process->getOutput()); return redirect()->route('admin.updates')->with('update_error','Kunne ikke starte updateren.'.($error!==''?' '.$error:'')); } return redirect()->route('admin.updates')->with('update_message','Nodexa-opdateringen er startet. Siden følger status automatisk.'); }
    private function installedVersion(): array { $d=$this->readJson(self::VERSION_FILE); return ['version'=>(string)($d['version']??'unknown'),'commit'=>$d['commit']??null,'repository'=>(string)($d['repository']??'yupthatpandadk/Nodexa'),'branch'=>(string)($d['branch']??'main'),'installed_at'=>$d['installed_at']??null]; }
    private function latestVersion(array $installed,bool $force=false): array { $repository=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($installed['repository']??'yupthatpandadk/Nodexa'))?:'yupthatpandadk/Nodexa'; $branch=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($installed['branch']??'main'))?:'main'; $key='nodexa:update:latest:'.sha1($repository.':'.$branch); if($force)Cache::forget($key); return Cache::remember($key,now()->addMinutes(5),function()use($repository,$branch){try{$r=Http::acceptJson()->withUserAgent('Nodexa-Panel-Updater')->timeout(8)->get("https://api.github.com/repos/{$repository}/commits/{$branch}");if(!$r->successful())return ['commit'=>null,'version'=>null,'error'=>'GitHub svarede med HTTP '.$r->status()];$c=$r->json();$version=null;try{$v=Http::accept('text/plain')->withUserAgent('Nodexa-Panel-Updater')->timeout(8)->get("https://raw.githubusercontent.com/{$repository}/{$branch}/VERSION");if($v->successful()){ $candidate=ltrim(trim((string)$v->body()),'vV'); if(preg_match('/^\d+(?:\.\d+){1,3}(?:[-+][0-9A-Za-z.-]+)?$/',$candidate))$version=$candidate; }}catch(\Throwable $e){} return ['version'=>$version,'commit'=>$c['sha']??null,'message'=>trim((string)data_get($c,'commit.message','')),'author'=>data_get($c,'commit.author.name'),'date'=>data_get($c,'commit.author.date'),'url'=>$c['html_url']??null,'error'=>null];}catch(\Throwable $e){return ['commit'=>null,'version'=>null,'error'=>'Kunne ikke kontakte GitHub: '.$e->getMessage()];}}); }
    private function changelog(array $installed): array {
        // Prefer the bundled changelog. It works even if GitHub API is rate-limited or unavailable.
        $paths=[base_path('../CHANGELOG.json'),base_path('CHANGELOG.json'),dirname(base_path()).'/CHANGELOG.json'];
        foreach($paths as $path){if(is_readable($path)){ $data=json_decode((string)@file_get_contents($path),true); if(is_array($data)&&count($data)){return collect($data)->take(20)->map(function($e){return ['sha'=>$e['sha']??'','title'=>(string)($e['title']??'Nodexa update'),'body'=>(string)($e['description']??$e['body']??''),'author'=>$e['author']??'Nodexa','date'=>$e['date']??null,'url'=>$e['url']??null,'type'=>$e['type']??null];})->all();} }}
        $repo=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($installed['repository']??'yupthatpandadk/Nodexa'))?:'yupthatpandadk/Nodexa'; $branch=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($installed['branch']??'main'))?:'main';
        // Raw GitHub changelog is the second source and does not consume the commits API rate limit.
        try{$r=Http::acceptJson()->withUserAgent('Nodexa-Panel-Updater')->timeout(8)->get("https://raw.githubusercontent.com/{$repo}/{$branch}/CHANGELOG.json");if($r->successful()){ $data=$r->json(); if(is_array($data)&&count($data))return collect($data)->take(20)->map(function($e){return ['sha'=>$e['sha']??'','title'=>(string)($e['title']??'Nodexa update'),'body'=>(string)($e['description']??$e['body']??''),'author'=>$e['author']??'Nodexa','date'=>$e['date']??null,'url'=>$e['url']??null,'type'=>$e['type']??null];})->all(); }}catch(\Throwable $e){}
        // Last fallback: recent GitHub commits.
        try{$r=Http::acceptJson()->withUserAgent('Nodexa-Panel-Updater')->timeout(8)->get("https://api.github.com/repos/{$repo}/commits",['sha'=>$branch,'per_page'=>12]);if(!$r->successful())return [];return collect($r->json())->map(function($c){$message=trim((string)data_get($c,'commit.message',''));$title=strtok($message,"\n")?:'Nodexa update';return ['sha'=>substr((string)($c['sha']??''),0,9),'title'=>$title,'body'=>trim(substr($message,strlen($title))),'author'=>data_get($c,'commit.author.name'),'date'=>data_get($c,'commit.author.date'),'url'=>$c['html_url']??null,'type'=>null];})->all();}catch(\Throwable $e){return [];}
    }
    private function updateAvailable(array $installed,array $latest): bool { $iv=ltrim(trim((string)($installed['version']??'')),'vV');$lv=ltrim(trim((string)($latest['version']??'')),'vV');if($iv!==''&&$lv!==''&&$iv!=='unknown'){if(version_compare($lv,$iv,'>'))return true;if(version_compare($lv,$iv,'<'))return false;if(!empty($installed['commit'])&&!empty($latest['commit']))return strtolower((string)$installed['commit'])!==strtolower((string)$latest['commit']);return false;}if(empty($installed['commit'])||empty($latest['commit']))return false;return strtolower((string)$installed['commit'])!==strtolower((string)$latest['commit']); }
    private function updateState(): array { $s=$this->readJson(self::STATE_FILE);return ['status'=>(string)($s['status']??'idle'),'message'=>(string)($s['message']??'Ingen opdatering kører.'),'updated_at'=>$s['updated_at']??null]; }
    private function readJson(string $path): array {if(!is_readable($path))return [];$d=json_decode((string)@file_get_contents($path),true);return is_array($d)?$d:[];}
}
