<?php

namespace Pterodactyl\Http\Controllers\Admin;

use Illuminate\Http\JsonResponse; use Illuminate\Http\RedirectResponse; use Illuminate\Support\Facades\Cache; use Illuminate\Support\Facades\Http; use Illuminate\View\View; use Pterodactyl\Http\Controllers\Controller; use Symfony\Component\Process\Process;
class UpdateController extends Controller
{
 private const STATE_DIR='/var/lib/nodexa'; private const VERSION_FILE=self::STATE_DIR.'/version.json'; private const STATE_FILE=self::STATE_DIR.'/update-state.json';
 public function index():View{$installed=$this->installedVersion();$latest=$this->latestVersion($installed,true);$state=$this->updateState();return view('admin.updates.index',['installed'=>$installed,'latest'=>$latest,'state'=>$state,'changelog'=>$this->changelog($installed),'updateAvailable'=>$this->updateAvailable($installed,$latest)]);}
 public function status():JsonResponse{$installed=$this->installedVersion();$latest=$this->latestVersion($installed);return response()->json(['state'=>$this->updateState(),'installed'=>$installed,'latest'=>$latest,'update_available'=>$this->updateAvailable($installed,$latest)]);}
 public function run():RedirectResponse{$state=$this->updateState();if(($state['status']??'idle')==='running')return redirect()->route('admin.updates')->with('update_message','En Nodexa-opdatering kører allerede.');$installed=$this->installedVersion();$latest=$this->latestVersion($installed,true);if(!$this->updateAvailable($installed,$latest))return redirect()->route('admin.updates')->with('update_message','Nodexa er allerede opdateret til den nyeste GitHub-version.');$trigger='/usr/local/sbin/nodexa-update-trigger';if(!is_executable($trigger))return redirect()->route('admin.updates')->with('update_error','Nodexa update-triggeren er ikke installeret på denne server. Kør setup-updater.sh som root.');$p=new Process(['/usr/bin/sudo',$trigger]);$p->setTimeout(15);$p->run();if(!$p->isSuccessful()){ $e=trim($p->getErrorOutput()?:$p->getOutput());return redirect()->route('admin.updates')->with('update_error','Kunne ikke starte updateren.'.($e!==''?' '.$e:''));}return redirect()->route('admin.updates')->with('update_message','Nodexa-opdateringen er startet. Siden følger status automatisk.');}
 private function installedVersion():array{$d=$this->readJson(self::VERSION_FILE);$version=(string)($d['version']??'unknown');if($version==='unknown'||$version===''){foreach([base_path('../VERSION'),base_path('VERSION'),dirname(base_path()).'/VERSION'] as $p){if(is_readable($p)){ $v=ltrim(trim((string)@file_get_contents($p)),'vV');if(preg_match('/^\d+(?:\.\d+){1,3}(?:[-+][0-9A-Za-z.-]+)?$/',$v)){ $version=$v;break;}}}}return ['version'=>$version,'commit'=>$d['commit']??null,'repository'=>(string)($d['repository']??'yupthatpandadk/Nodexa'),'branch'=>(string)($d['branch']??'main'),'installed_at'=>$d['installed_at']??null];}
 private function latestVersion(array $i,bool $force=false):array{$repo=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($i['repository']??'yupthatpandadk/Nodexa'))?:'yupthatpandadk/Nodexa';$branch=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($i['branch']??'main'))?:'main';if($repo!=='yupthatpandadk/Nodexa')$repo='yupthatpandadk/Nodexa';if($branch===''||in_array($branch,['pterodactyl-core','master'],true))$branch='main';$key='nodexa:update:latest:'.sha1($repo.':'.$branch);if($force)Cache::forget($key);return Cache::remember($key,now()->addMinutes(2),function()use($repo,$branch){$version=null;$commit=null;$meta=[];$errors=[];try{$v=Http::accept('text/plain')->withUserAgent('Nodexa-Panel-Updater')->timeout(8)->get("https://raw.githubusercontent.com/{$repo}/{$branch}/VERSION");if($v->successful()){ $x=ltrim(trim((string)$v->body()),'vV');if(preg_match('/^\d+(?:\.\d+){1,3}(?:[-+][0-9A-Za-z.-]+)?$/',$x))$version=$x;}else{$errors[]='VERSION HTTP '.$v->status();}}catch(\Throwable $e){$errors[]='VERSION: '.$e->getMessage();}try{$r=Http::acceptJson()->withUserAgent('Nodexa-Panel-Updater')->timeout(8)->get("https://api.github.com/repos/{$repo}/commits/{$branch}");if($r->successful()){ $c=$r->json();$commit=$c['sha']??null;$meta=['message'=>trim((string)data_get($c,'commit.message','')),'author'=>data_get($c,'commit.author.name'),'date'=>data_get($c,'commit.author.date'),'url'=>$c['html_url']??null];}else{$errors[]='GitHub HTTP '.$r->status();}}catch(\Throwable $e){$errors[]='GitHub: '.$e->getMessage();}return array_merge(['version'=>$version,'commit'=>$commit,'error'=>count($errors)?implode(' · ',$errors):null],$meta);});}
 private function changelog(array $i):array{
  $map=fn($e)=>['version'=>(string)($e['version']??''),'sha'=>$e['sha']??'','title'=>(string)($e['title']??'Nodexa update'),'body'=>(string)($e['description']??$e['body']??''),'author'=>$e['author']??'Nodexa','date'=>$e['date']??null,'url'=>$e['url']??null,'type'=>$e['type']??null];
  $entries=[];$paths=[base_path('../CHANGELOG.json'),base_path('CHANGELOG.json'),dirname(base_path()).'/CHANGELOG.json'];
  foreach($paths as $path){if(is_readable($path)){ $d=json_decode((string)@file_get_contents($path),true);if(is_array($d)&&count($d)){ $entries=collect($d)->map($map)->all();break;}}}
  $repo=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($i['repository']??'yupthatpandadk/Nodexa'))?:'yupthatpandadk/Nodexa';$branch=preg_replace('/[^A-Za-z0-9_.\/-]/','',(string)($i['branch']??'main'))?:'main';
  if(!$entries){try{$r=Http::acceptJson()->withUserAgent('Nodexa-Panel-Updater')->timeout(8)->get("https://raw.githubusercontent.com/{$repo}/{$branch}/CHANGELOG.json");if($r->successful()){ $d=$r->json();if(is_array($d))$entries=collect($d)->map($map)->all();}}catch(\Throwable $e){}}
  $known=collect($entries)->pluck('version')->filter()->unique()->flip()->all();
  try{for($page=1;$page<=10;$page++){ $r=Http::acceptJson()->withUserAgent('Nodexa-Panel-Updater')->timeout(10)->get("https://api.github.com/repos/{$repo}/commits",['sha'=>$branch,'per_page'=>100,'page'=>$page]);if(!$r->successful())break;$commits=$r->json();if(!is_array($commits)||!count($commits))break;foreach($commits as $c){$message=trim((string)data_get($c,'commit.message',''));$first=trim(strtok($message,"\n")?:$message);if(!preg_match('/(?:release|bump)\s*(?:nodexa\s*)?(?:to\s*)?v?(\d+\.\d+(?:\.\d+){1,2})/i',$first,$m))continue;$version=$m[1];if(isset($known[$version]))continue;$entries[]=['version'=>$version,'sha'=>(string)($c['sha']??''),'title'=>$first,'body'=>'Historisk Nodexa-release fra GitHub. Åbn versionen for at se release-posten.','author'=>(string)data_get($c,'commit.author.name','Nodexa'),'date'=>data_get($c,'commit.author.date'),'url'=>$c['html_url']??null,'type'=>'changed'];$known[$version]=true;}if(count($commits)<100)break;}}catch(\Throwable $e){}
  usort($entries,function($a,$b){$av=ltrim((string)($a['version']??'0'),'vV');$bv=ltrim((string)($b['version']??'0'),'vV');$cmp=version_compare($bv,$av);if($cmp!==0)return $cmp;return strcmp((string)($b['date']??''),(string)($a['date']??''));});return $entries;
 }
 private function updateAvailable(array $i,array $l):bool{$iv=ltrim(trim((string)($i['version']??'')),'vV');$lv=ltrim(trim((string)($l['version']??'')),'vV');if($iv!==''&&$lv!==''&&$iv!=='unknown'){if(version_compare($lv,$iv,'>'))return true;if(version_compare($lv,$iv,'<'))return false;if(!empty($i['commit'])&&!empty($l['commit']))return strtolower((string)$i['commit'])!==strtolower((string)$l['commit']);return false;}if(empty($i['commit'])||empty($l['commit']))return false;return strtolower((string)$i['commit'])!==strtolower((string)$l['commit']);}
 private function updateState():array{$s=$this->readJson(self::STATE_FILE);return ['status'=>(string)($s['status']??'idle'),'message'=>(string)($s['message']??'Ingen opdatering kører.'),'progress'=>max(0,min(100,(int)($s['progress']??0))),'step'=>(string)($s['step']??''),'updated_at'=>$s['updated_at']??null];}
 private function readJson(string $p):array{if(!is_readable($p))return [];$d=json_decode((string)@file_get_contents($p),true);return is_array($d)?$d:[];}
}
