@extends('layouts.admin')
@section('title','Faktura '.$invoice->number)
@section('content')
@php($overdue=$invoice->status==='unpaid'&&$invoice->due_at&&\Carbon\Carbon::parse($invoice->due_at)->isPast())
<div class="inv"><div class="top"><div><a href="{{route('admin.invoices')}}">← Fakturaer</a><h1>{{$invoice->number}}</h1><p>{{$invoice->username}} · {{$invoice->email}}</p></div><span class="badge-status {{$overdue?'overdue':$invoice->status}}">{{$overdue?'FORFALDEN':strtoupper($invoice->status)}}</span></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<div class="cols"><main><div class="card invoice-paper"><div class="invoice-title"><div><small>FAKTURA</small><h2>{{$invoice->number}}</h2></div><div class="dates"><span>Oprettet <b>{{\Carbon\Carbon::parse($invoice->created_at)->format('d/m/Y')}}</b></span><span>Forfalder <b>{{$invoice->due_at?\Carbon\Carbon::parse($invoice->due_at)->format('d/m/Y'):'—'}}</b></span></div></div><div class="customer"><small>FAKTURERES TIL</small><strong>{{$invoice->username}}</strong><span>{{$invoice->email}}</span></div><table><thead><tr><th>Beskrivelse</th><th>Antal</th><th>Pris</th><th>Total</th></tr></thead><tbody>@foreach($items as $item)<tr><td>{{$item->description}}</td><td>{{$item->quantity}}</td><td>{{number_format($item->unit_price,2,',','.')}}</td><td>{{number_format($item->total,2,',','.')}} {{$invoice->currency}}</td></tr>@endforeach</tbody></table><div class="totals"><div><span>Subtotal</span><b>{{number_format($invoice->subtotal,2,',','.')}} {{$invoice->currency}}</b></div><div><span>Moms {{$invoice->tax_rate??0}}%</span><b>{{number_format($invoice->tax,2,',','.')}} {{$invoice->currency}}</b></div><div class="grand"><span>Total</span><b>{{number_format($invoice->total,2,',','.')}} {{$invoice->currency}}</b></div><div><span>Restbeløb</span><b>{{number_format($invoice->balance??$invoice->total,2,',','.')}} {{$invoice->currency}}</b></div></div>@if($invoice->notes)<div class="notes"><small>NOTER</small><p>{{$invoice->notes}}</p></div>@endif</div>
<div class="card section"><h3>Fakturalinjer</h3><form method="POST" action="{{route('admin.invoices.items',$invoice->id)}}">@csrf<div class="formgrid"><input name="description" placeholder="Beskrivelse" required><input type="number" step="0.01" name="quantity" value="1" required><input type="number" step="0.01" name="unit_price" placeholder="Pris" required><button class="btn btn-primary">Tilføj</button></div></form></div></main>
<aside><div class="card section"><h3>Handlinger</h3><form method="POST" action="{{route('admin.invoices.status',$invoice->id)}}">@csrf @method('PATCH')<select name="status"><option value="unpaid">Ubetalt</option><option value="paid">Betalt</option><option value="cancelled">Annulleret</option><option value="refunded">Refunderet</option></select><button class="btn btn-primary full">Opdater status</button></form><form method="POST" action="{{route('admin.invoices.remind',$invoice->id)}}">@csrf<button class="btn btn-default full">Registrer/send rykker</button></form><a class="btn btn-default full" href="/client/checkout/{{$invoice->id}}">Åbn betalingsside</a></div>
<div class="card section"><h3>Registrer betaling</h3><form method="POST" action="{{route('admin.invoices.payments',$invoice->id)}}">@csrf<label>Beløb<input type="number" step="0.01" name="amount" required></label><label>Metode<select name="method"><option>manual</option><option>stripe</option><option>mobilepay</option><option>paypal</option><option>bank</option></select></label><label>Transaktions-ID<input name="transaction_id"></label><button class="btn btn-primary full">Registrer betaling</button></form></div>
<div class="card section"><h3>Betalinger</h3>@forelse($payments as $p)<div class="payment"><b>{{number_format($p->amount,2,',','.')}} {{$p->currency}}</b><span>{{$p->method}} · {{$p->paid_at}}</span></div>@empty<p class="muted">Ingen betalinger registreret.</p>@endforelse</div></aside></div></div>
<style>.inv{max-width:1450px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.top h1{margin:7px 0 3px}.top p,.muted{color:#8296a9}.badge-status{padding:7px 12px;border-radius:99px;background:#162b3c;font-size:11px}.badge-status.paid{background:#103225;color:#7be7a5}.badge-status.unpaid{background:#392e13;color:#ffd37a}.badge-status.overdue{background:#3b171c;color:#ff8d8d}.cols{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:18px}.card{background:#081522;border:1px solid #173047;border-radius:14px}.invoice-paper{padding:28px}.invoice-title{display:flex;justify-content:space-between}.invoice-title small,.customer small{color:#7e91a4;letter-spacing:.1em}.dates{display:flex;gap:25px}.dates span{display:flex;flex-direction:column;color:#7e91a4;font-size:11px}.dates b{color:#e7eef5;margin-top:4px}.customer{display:flex;flex-direction:column;margin:35px 0}.customer strong{font-size:16px;margin:7px 0 2px}.customer span{color:#8da0b3}.invoice-paper table{width:100%}.invoice-paper th,.invoice-paper td{padding:12px;border-bottom:1px solid #173047;text-align:left}.totals{margin:22px 0 0 auto;max-width:330px}.totals div{display:flex;justify-content:space-between;padding:7px}.totals .grand{font-size:18px;border-top:1px solid #23425d;margin-top:7px;padding-top:13px}.notes{border-top:1px solid #173047;margin-top:25px;padding-top:18px}.section{padding:18px;margin-bottom:16px}.section h3{font-size:15px;margin:0 0 15px}.section input,.section select{width:100%;background:#10283d!important;color:#e9f2fb!important;border:1px solid #244560;border-radius:8px;padding:10px;margin:5px 0 12px}.section option{background:#10283d}.full{width:100%;margin-bottom:8px}.formgrid{display:grid;grid-template-columns:1fr 100px 150px auto;gap:8px}.formgrid input{margin:0}.payment{padding:10px 0;border-bottom:1px solid #173047}.payment b,.payment span{display:block}.payment span{font-size:11px;color:#8093a6;margin-top:3px}@media(max-width:900px){.cols{grid-template-columns:1fr}.dates{flex-direction:column;gap:7px}.invoice-paper{padding:18px}.formgrid{grid-template-columns:1fr}.top{align-items:flex-start}.invoice-paper{overflow-x:auto}.invoice-paper table{min-width:600px}}</style>
@endsection