@extends('layouts.admin')
@section('title','Fakturaer')
@section('content')
<div class="nx-invoices"><div class="nx-head"><div><span>COMMERCE</span><h1>Fakturaer</h1><p>Komplet fakturastyring med betalinger, forfald og kundehistorik.</p></div><button class="btn btn-primary" onclick="document.getElementById('newInvoice').classList.toggle('open')">+ Ny faktura</button></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<div class="nx-stats"><div><small>Alle fakturaer</small><strong>{{$stats['count']}}</strong></div><div><small>Ubetalt</small><strong>{{number_format($stats['unpaid'],2,',','.')}} kr.</strong></div><div><small>Forfalden</small><strong>{{number_format($stats['overdue'],2,',','.')}} kr.</strong></div><div><small>Betalt i alt</small><strong>{{number_format($stats['paid'],2,',','.')}} kr.</strong></div></div>
<div id="newInvoice" class="nx-create"><h3>Opret manuel faktura</h3><form method="POST" action="{{route('admin.invoices.store')}}">@csrf<div class="grid"><label>Kunde<select name="user_id" required><option value="">Vælg kunde</option>@foreach($users as $u)<option value="{{$u->id}}">{{$u->username}} — {{$u->email}}</option>@endforeach</select></label><label>Beskrivelse<input name="description" required></label><label>Antal<input type="number" step="0.01" name="quantity" value="1" required></label><label>Pris<input type="number" step="0.01" name="unit_price" required></label><label>Moms %<input type="number" step="0.01" name="tax_rate" value="25"></label><label>Valuta<input name="currency" value="DKK" maxlength="3" required></label><label>Forfaldsdato<input type="date" name="due_at" required></label><label class="wide">Noter<textarea name="notes" rows="3"></textarea></label></div><button class="btn btn-primary">Opret faktura</button></form></div>
<form class="nx-filter" method="GET"><input name="search" value="{{request('search')}}" placeholder="Søg fakturanr., kunde eller e-mail"><select name="status"><option value="">Alle statusser</option>@foreach(['unpaid'=>'Ubetalt','paid'=>'Betalt','cancelled'=>'Annulleret','refunded'=>'Refunderet'] as $k=>$v)<option value="{{$k}}" {{request('status')===$k?'selected':''}}>{{$v}}</option>@endforeach</select><button class="btn btn-default">Filtrer</button></form>
<div class="nx-card"><div class="table-responsive"><table class="table"><thead><tr><th>Faktura</th><th>Kunde</th><th>Dato</th><th>Forfalder</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@forelse($invoices as $i)@php($overdue=$i->status==='unpaid' && $i->due_at && \Carbon\Carbon::parse($i->due_at)->isPast())<tr><td><strong>{{$i->number}}</strong><small>#{{$i->id}}</small></td><td>{{$i->username??'Kunde'}}<small>{{$i->email??''}}</small></td><td>{{optional(\Carbon\Carbon::parse($i->created_at))->format('d/m/Y')}}</td><td>{{$i->due_at?\Carbon\Carbon::parse($i->due_at)->format('d/m/Y'):'—'}}</td><td><strong>{{number_format($i->total,2,',','.')}} {{$i->currency}}</strong></td><td><span class="status {{$overdue?'overdue':$i->status}}">{{$overdue?'Forfalden':ucfirst($i->status)}}</span></td><td><a class="btn btn-sm btn-default" href="{{route('admin.invoices.show',$i->id)}}">Åbn</a></td></tr>@empty<tr><td colspan="7" class="empty">Ingen fakturaer endnu.</td></tr>@endforelse</tbody></table></div></div></div>
<style>.nx-invoices{max-width:1500px;margin:auto}.nx-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}.nx-head span{font-size:10px;letter-spacing:.12em;color:#818cf8;font-weight:800}.nx-head h1{margin:5px 0;font-size:28px}.nx-head p{color:#8da0b5}.nx-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.nx-stats>div,.nx-card,.nx-create{background:#081522;border:1px solid #173047;border-radius:14px}.nx-stats>div{padding:17px}.nx-stats small,.table td small{display:block;color:#7890a7}.nx-stats strong{display:block;font-size:20px;margin-top:6px}.nx-create{display:none;padding:20px;margin-bottom:18px}.nx-create.open{display:block}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grid label{font-size:12px}.grid input,.grid select,.grid textarea,.nx-filter input,.nx-filter select{display:block;width:100%;margin-top:5px;background:#10283d!important;color:#e8f2ff!important;border:1px solid #234563!important;border-radius:8px;padding:10px}.grid option,.nx-filter option{background:#10283d;color:#fff}.wide{grid-column:span 4}.nx-filter{display:grid;grid-template-columns:1fr 190px auto;gap:8px;margin-bottom:12px}.nx-filter input,.nx-filter select{margin:0}.nx-card{overflow:hidden}.table{margin:0}.table th{font-size:11px;color:#8298ad;border-color:#173047!important}.table td{vertical-align:middle;border-color:#132a3d!important}.status{padding:5px 9px;border-radius:99px;font-size:10px;background:#162b3c}.status.paid{color:#79e6a3;background:#103225}.status.unpaid{color:#ffd37a;background:#392e13}.status.overdue{color:#ff8d8d;background:#3b171c}.status.cancelled,.status.refunded{color:#aab6c2}.empty{text-align:center;padding:40px!important;color:#7890a7}@media(max-width:767px){.nx-head{align-items:flex-start;gap:15px;flex-direction:column}.nx-stats{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.nx-filter{grid-template-columns:1fr}.table{min-width:760px}}</style>
@endsection