@extends('layouts.admin')
@section('title','Ordrer')
@section('content-header')<h1>Ordrer <small>Administrér kundernes bestillinger</small></h1>@endsection
@section('content')
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
<style>.nx-filter{background:#0a1417;border:1px solid rgba(66,233,166,.14);padding:14px;border-radius:10px;margin-bottom:16px;display:flex;gap:10px}.nx-filter .form-control{max-width:300px}.nx-status{font-size:10px;padding:5px 8px;border-radius:12px;background:#132b2c;color:#42e9a6;text-transform:uppercase}.nx-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.nx-muted{color:#8ba09c;font-size:11px}@media(max-width:700px){.nx-filter{display:block}.nx-filter>*{margin-bottom:8px!important}.nx-filter .form-control{max-width:none}}</style>
<form class="nx-filter" method="GET"><input class="form-control" name="search" value="{{request('search')}}" placeholder="Søg ordre, kunde, email eller pakke"><select class="form-control" name="status"><option value="">Alle statusser</option>@foreach(['pending','paid','processing','completed','cancelled','refunded'] as $s)<option value="{{$s}}" {{request('status')===$s?'selected':''}}>{{ucfirst($s)}}</option>@endforeach</select><button class="btn btn-primary"><i class="fa fa-search"></i> Søg</button><a class="btn btn-default" href="{{route('admin.orders')}}">Nulstil</a></form>
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Seneste ordrer</h3><span class="pull-right nx-muted">{{$orders->count()}} vist</span></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>#</th><th>Kunde</th><th>Produkt</th><th>Beløb</th><th>Betaling</th><th>Status</th><th>Oprettet</th><th>Handlinger</th></tr></thead><tbody>@forelse($orders as $o)<tr><td><strong>#{{$o->id}}</strong></td><td>{{$o->username?:('Bruger #'.$o->user_id)}}<br><span class="nx-muted">{{$o->email}}</span></td><td>{{$o->product_name?:('Produkt #'.$o->product_id)}}<br><span class="nx-muted">{{$o->product_type}}</span></td><td>{{number_format((float)$o->amount,2,',','.')}} {{$o->currency}}</td><td>{{$o->payment_method?:'—'}}</td><td><span class="nx-status">{{$o->status}}</span></td><td>{{$o->created_at}}</td><td><div class="nx-actions"><form method="POST" action="{{route('admin.orders.update',$o->id)}}">@csrf @method('PATCH')<select class="form-control input-sm" name="status" onchange="this.form.submit()">@foreach(['pending'=>'Afventer','paid'=>'Betalt','processing'=>'Behandles','completed'=>'Færdig','cancelled'=>'Annulleret','refunded'=>'Refunderet'] as $v=>$n)<option value="{{$v}}" {{$o->status===$v?'selected':''}}>{{$n}}</option>@endforeach</select></form><form method="POST" action="{{route('admin.orders.delete',$o->id)}}" onsubmit="return confirm('Slet ordre #{{$o->id}}? Den tilhørende faktura og en ikke-provisioneret VPS fjernes også. Dette kan ikke fortrydes.');">@csrf @method('DELETE')<button class="btn btn-xs btn-danger"><i class="fa fa-trash"></i> Slet</button></form></div></td></tr>@empty<tr><td colspan="8">Ingen ordrer fundet.</td></tr>@endforelse</tbody></table></div></div>
@endsection