@extends('layouts.admin')
@section('title','Ticket #'.$ticket->id)
@section('content-header')<h1>Ticket #{{ $ticket->id }} <small>{{ $ticket->subject }}</small></h1>@endsection
@section('content')
<style>
.ticket-head,.ticket-side,.reply-box{background:#fff;border-radius:7px;padding:18px;margin-bottom:18px;box-shadow:0 1px 3px rgba(0,0,0,.08)}.message{display:flex;margin-bottom:18px}.message.staff{flex-direction:row-reverse}.message-body{max-width:78%;padding:14px 16px;border-radius:10px;background:#f4f4f4}.message.staff .message-body{background:#e8f3fb}.message-name{font-weight:700;margin-bottom:5px}.message-time{font-size:11px;color:#888;margin-top:8px}.message-text{white-space:pre-wrap;word-break:break-word}.ticket-detail{padding:8px 0;border-bottom:1px solid #eee}.conversation{background:#fff;padding:20px;border-radius:7px;box-shadow:0 1px 3px rgba(0,0,0,.08);margin-bottom:18px}
</style>
<div class="row"><div class="col-md-8">
 <div class="ticket-head"><a href="{{ route('admin.tickets') }}" class="btn btn-default btn-xs"><i class="fa fa-arrow-left"></i> Alle tickets</a><h3>{{ $ticket->subject }}</h3><span class="text-muted">Oprettet {{ \Carbon\Carbon::parse($ticket->created_at)->diffForHumans() }}</span></div>
 <div class="conversation">
 @forelse($messages as $message)<div class="message {{ $message->staff ? 'staff' : '' }}"><div class="message-body"><div class="message-name">{{ $message->staff ? 'Support · '.($message->username ?: 'Medarbejder') : ($message->username ?: 'Kunde') }}</div><div class="message-text">{{ $message->message }}</div><div class="message-time">{{ \Carbon\Carbon::parse($message->created_at)->format('d/m/Y H:i') }}</div></div></div>@empty<p class="text-muted">Ingen beskeder.</p>@endforelse
 </div>
 @if($ticket->status !== 'closed')<form method="POST" action="{{ route('admin.tickets.reply',$ticket->id) }}" class="reply-box">@csrf<h4><i class="fa fa-reply"></i> Svar kunden</h4><textarea class="form-control" name="message" rows="7" required placeholder="Skriv dit svar..."></textarea><div style="margin-top:12px;text-align:right"><button class="btn btn-primary"><i class="fa fa-paper-plane"></i> Send svar</button></div></form>@endif
</div><div class="col-md-4">
 <div class="ticket-side"><h4>Kunde</h4><div class="ticket-detail"><strong>{{ trim(($ticket->name_first??'').' '.($ticket->name_last??'')) ?: ($ticket->username ?: 'Kunde #'.$ticket->user_id) }}</strong><br><span class="text-muted">{{ $ticket->email }}</span></div><div class="ticket-detail">Kunde-ID <strong>#{{ $ticket->user_id }}</strong></div></div>
 <form method="POST" action="{{ route('admin.tickets.update',$ticket->id) }}" class="ticket-side">@csrf @method('PATCH')<h4>Ticket indstillinger</h4><label>Status</label><select name="status" class="form-control">@foreach(['open'=>'Åben','customer_reply'=>'Kundesvar','answered'=>'Besvaret','closed'=>'Lukket'] as $v=>$n)<option value="{{ $v }}" @selected($ticket->status===$v)>{{ $n }}</option>@endforeach</select><br><label>Prioritet</label><select name="priority" class="form-control">@foreach(['low'=>'Lav','normal'=>'Normal','high'=>'Høj'] as $v=>$n)<option value="{{ $v }}" @selected($ticket->priority===$v)>{{ $n }}</option>@endforeach</select><br><label>Afdeling</label><select name="department" class="form-control">@foreach(['support'=>'Support','billing'=>'Fakturering','sales'=>'Salg'] as $v=>$n)<option value="{{ $v }}" @selected($ticket->department===$v)>{{ $n }}</option>@endforeach</select><br><button class="btn btn-default btn-block">Gem ændringer</button></form>
 <div class="ticket-side">@if($ticket->status==='closed')<form method="POST" action="{{ route('admin.tickets.reopen',$ticket->id) }}">@csrf<button class="btn btn-success btn-block"><i class="fa fa-refresh"></i> Genåbn ticket</button></form>@else<form method="POST" action="{{ route('admin.tickets.close',$ticket->id) }}">@csrf<button class="btn btn-danger btn-block"><i class="fa fa-check"></i> Luk ticket</button></form>@endif</div>
</div></div>
@endsection