@extends('layouts.admin')
@section('title','Ticket Center')
@section('content-header')
<div class="nx-page-title"><div class="nx-title-icon"><i class="fa fa-comments-o"></i></div><div><h1>Ticket Center</h1><p>Kundesupport og henvendelser samlet ét sted</p></div></div>
@endsection
@section('content')
<style>
:root{--nx-bg:#07111f;--nx-panel:#0d1b2d;--nx-panel2:#102238;--nx-border:#203b58;--nx-text:#f3f7fc;--nx-muted:#8fa5bd;--nx-blue:#1683ff;--nx-green:#22c98a;--nx-orange:#f0a132;--nx-red:#ef5261}
.content-wrapper,.content{background:var(--nx-bg)!important}.content-header{background:var(--nx-bg)!important;padding:24px 24px 8px}.nx-page-title{display:flex;align-items:center;gap:15px;color:var(--nx-text)}.nx-page-title h1{font-size:28px;font-weight:700;margin:0}.nx-page-title p{margin:4px 0 0;color:var(--nx-muted);font-size:14px}.nx-title-icon{width:52px;height:52px;border-radius:14px;display:flex;align-items:center;justify-content:center;background:rgba(22,131,255,.13);color:var(--nx-blue);font-size:26px}
.nx-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:12px 0 20px}.nx-stat{position:relative;overflow:hidden;background:linear-gradient(135deg,var(--nx-panel2),var(--nx-panel));border:1px solid var(--nx-border);border-radius:12px;padding:20px;display:flex;align-items:center;gap:15px;min-height:112px}.nx-stat-icon{width:50px;height:50px;flex:0 0 50px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:22px}.nx-stat strong{display:block;color:var(--nx-text);font-size:28px;line-height:1}.nx-stat b{display:block;color:var(--nx-text);font-size:14px;margin-top:7px}.nx-stat small{display:block;color:var(--nx-muted);margin-top:3px}.nx-blue .nx-stat-icon{background:rgba(22,131,255,.17);color:#3c9cff}.nx-green .nx-stat-icon{background:rgba(34,201,138,.17);color:var(--nx-green)}.nx-orange .nx-stat-icon{background:rgba(240,161,50,.17);color:var(--nx-orange)}.nx-red .nx-stat-icon{background:rgba(239,82,97,.17);color:var(--nx-red)}
.nx-filter,.nx-ticket-panel{background:linear-gradient(180deg,var(--nx-panel2),var(--nx-panel));border:1px solid var(--nx-border);border-radius:12px;padding:18px;margin-bottom:20px;box-shadow:0 8px 30px rgba(0,0,0,.12)}.nx-search-row{display:flex;gap:12px;margin-bottom:12px}.nx-search-wrap{position:relative;flex:1}.nx-search-wrap i{position:absolute;left:15px;top:13px;color:var(--nx-muted)}.nx-filter .form-control{height:42px;background:#0a1727!important;border:1px solid #2b4764!important;color:var(--nx-text)!important;border-radius:8px;box-shadow:none;padding-left:13px}.nx-search-wrap .form-control{padding-left:40px}.nx-filter .form-control:focus{border-color:var(--nx-blue)!important}.nx-filter .form-control option{background:#0d1b2d;color:#fff}.nx-filter-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) 140px;gap:12px}.nx-btn{height:42px;border:0;border-radius:8px;background:linear-gradient(135deg,#1478ed,#2994ff);color:#fff;font-weight:600;padding:0 20px}.nx-btn:hover{color:#fff;filter:brightness(1.08)}
.nx-panel-head{display:flex;justify-content:space-between;align-items:center;padding-bottom:16px;border-bottom:1px solid var(--nx-border)}.nx-panel-head h3{color:var(--nx-text);font-size:17px;font-weight:700;margin:0}.nx-panel-head h3 i{color:var(--nx-blue);margin-right:8px}.nx-count{background:rgba(22,131,255,.15);border:1px solid rgba(22,131,255,.35);color:#67adff;border-radius:20px;padding:4px 10px;font-size:12px}.nx-table{margin:0!important}.nx-table thead th{border-bottom:1px solid var(--nx-border)!important;color:#aebfd1!important;font-size:12px;text-transform:uppercase;letter-spacing:.03em;padding:15px 10px!important}.nx-table tbody td{border-top:1px solid rgba(32,59,88,.65)!important;color:#dce7f2!important;padding:14px 10px!important;vertical-align:middle!important}.nx-table tbody tr:hover{background:rgba(22,131,255,.05)!important}.ticket-row{cursor:pointer}.ticket-subject{font-weight:600;color:#fff!important}.ticket-meta{font-size:11px;color:var(--nx-muted);margin-top:2px}.priority-high{color:#ff6674!important;font-weight:700}.priority-normal{color:#ffb64d!important}.priority-low{color:#37d69b!important}.nx-open{background:#13243a!important;border:1px solid #31506f!important;color:#dce9f8!important}.ticket-empty{padding:60px 20px;text-align:center;color:var(--nx-muted)}.ticket-empty .empty-icon{width:68px;height:68px;border-radius:18px;background:#13263d;display:flex;align-items:center;justify-content:center;margin:0 auto 15px;font-size:28px;color:#718ba5}.ticket-empty h4{font-size:18px;color:var(--nx-text);font-weight:700;margin:0 0 6px}.ticket-empty p{margin:0}.nx-mobile-list{display:none}.nx-mobile-card{background:#0b192a;border:1px solid var(--nx-border);border-radius:10px;padding:15px;margin-top:12px;color:var(--nx-text)}.nx-mobile-top{display:flex;justify-content:space-between;gap:10px}.nx-mobile-subject{font-size:15px;font-weight:700;margin:9px 0}.nx-mobile-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;color:var(--nx-muted);font-size:12px}.nx-mobile-card .btn{margin-top:12px;width:100%;background:#132a45;border-color:#2b4b6b;color:#fff}
@media(max-width:991px){.nx-stats{grid-template-columns:repeat(2,1fr)}.nx-filter-grid{grid-template-columns:1fr 1fr}.nx-btn{width:100%}}
@media(max-width:767px){.content-header{padding:18px 15px 5px}.content{padding:15px!important}.nx-page-title{align-items:flex-start}.nx-title-icon{width:44px;height:44px;flex-basis:44px;font-size:21px}.nx-page-title h1{font-size:22px}.nx-page-title p{font-size:12px}.nx-stats{grid-template-columns:1fr 1fr;gap:10px}.nx-stat{padding:13px;min-height:88px;gap:10px}.nx-stat-icon{width:38px;height:38px;flex-basis:38px;font-size:17px}.nx-stat strong{font-size:22px}.nx-stat b{font-size:12px}.nx-stat small{display:none}.nx-filter,.nx-ticket-panel{padding:12px;border-radius:10px}.nx-search-row{display:block}.nx-search-row .nx-btn{margin-top:10px}.nx-filter-grid{grid-template-columns:1fr}.nx-desktop-table{display:none}.nx-mobile-list{display:block}.nx-panel-head{padding-bottom:12px}.ticket-empty{padding:40px 10px}.nx-mobile-meta{grid-template-columns:1fr}.nx-count{font-size:11px}}
@media(max-width:390px){.nx-stats{grid-template-columns:1fr}.nx-stat small{display:block}}
</style>

<div class="nx-stats">
 <div class="nx-stat nx-blue"><div class="nx-stat-icon"><i class="fa fa-comment-o"></i></div><div><strong>{{ $stats['open'] ?? 0 }}</strong><b>Åbne tickets</b><small>Kræver handling</small></div></div>
 <div class="nx-stat nx-orange"><div class="nx-stat-icon"><i class="fa fa-clock-o"></i></div><div><strong>{{ $stats['waiting'] ?? 0 }}</strong><b>Afventer medarbejder</b><small>Nye kundesvar</small></div></div>
 <div class="nx-stat nx-green"><div class="nx-stat-icon"><i class="fa fa-check"></i></div><div><strong>{{ $stats['answered'] ?? 0 }}</strong><b>Besvaret</b><small>Afventer kunden</small></div></div>
 <div class="nx-stat nx-red"><div class="nx-stat-icon"><i class="fa fa-lock"></i></div><div><strong>{{ $stats['closed'] ?? 0 }}</strong><b>Lukkede</b><small>Afsluttede sager</small></div></div>
</div>

<form method="GET" class="nx-filter">
 <div class="nx-search-row"><div class="nx-search-wrap"><i class="fa fa-search"></i><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Søg efter ticket, kunde, e-mail eller emne..."></div><button class="nx-btn hidden-xs"><i class="fa fa-search"></i> Søg</button></div>
 <div class="nx-filter-grid">
  <select class="form-control" name="status"><option value="">Alle statusser</option>@foreach(['open'=>'Åben','customer_reply'=>'Kundesvar','answered'=>'Besvaret','closed'=>'Lukket'] as $v=>$n)<option value="{{ $v }}" @selected(request('status')===$v)>{{ $n }}</option>@endforeach</select>
  <select class="form-control" name="department"><option value="">Alle afdelinger</option>@foreach(['support'=>'Support','billing'=>'Fakturering','sales'=>'Salg'] as $v=>$n)<option value="{{ $v }}" @selected(request('department')===$v)>{{ $n }}</option>@endforeach</select>
  <select class="form-control" name="priority"><option value="">Alle prioriteter</option>@foreach(['high'=>'Høj','normal'=>'Normal','low'=>'Lav'] as $v=>$n)<option value="{{ $v }}" @selected(request('priority')===$v)>{{ $n }}</option>@endforeach</select>
  <button class="nx-btn visible-xs-block"><i class="fa fa-filter"></i> Filtrer</button><a href="{{ route('admin.tickets') }}" class="btn btn-default hidden-xs" style="height:42px;padding-top:10px;background:#172b43;border-color:#2b4764;color:#dce7f2;border-radius:8px"><i class="fa fa-refresh"></i> Nulstil</a>
 </div>
</form>

<div class="nx-ticket-panel">
 <div class="nx-panel-head"><h3><i class="fa fa-comments-o"></i> Support tickets</h3><span class="nx-count">{{ $tickets->count() }} tickets</span></div>
 <div class="table-responsive nx-desktop-table"><table class="table table-hover nx-table"><thead><tr><th>#</th><th>Kunde</th><th>Emne</th><th>Afdeling</th><th>Prioritet</th><th>Status</th><th>Seneste aktivitet</th><th></th></tr></thead><tbody>
 @forelse($tickets as $ticket)
 <tr class="ticket-row" onclick="window.location='{{ route('admin.tickets.show',$ticket->id) }}'"><td><strong>#{{ $ticket->id }}</strong></td><td>{{ $ticket->username ?: 'Kunde #'.$ticket->user_id }}<div class="ticket-meta">{{ $ticket->email }}</div></td><td class="ticket-subject">{{ $ticket->subject }}</td><td>{{ ['support'=>'Support','billing'=>'Fakturering','sales'=>'Salg'][$ticket->department] ?? ucfirst($ticket->department) }}</td><td class="priority-{{ $ticket->priority }}">{{ ['high'=>'Høj','normal'=>'Normal','low'=>'Lav'][$ticket->priority] ?? ucfirst($ticket->priority) }}</td><td>@php($labels=['open'=>['primary','Åben'],'customer_reply'=>['danger','Kundesvar'],'answered'=>['success','Besvaret'],'closed'=>['default','Lukket']]) @php($s=$labels[$ticket->status]??['warning',$ticket->status])<span class="label label-{{ $s[0] }}">{{ $s[1] }}</span></td><td>{{ \Carbon\Carbon::parse($ticket->updated_at)->diffForHumans() }}</td><td><a href="{{ route('admin.tickets.show',$ticket->id) }}" class="btn btn-xs nx-open">Åbn</a></td></tr>
 @empty<tr><td colspan="8"><div class="ticket-empty"><div class="empty-icon"><i class="fa fa-inbox"></i></div><h4>Ingen tickets fundet</h4><p>Der er ingen tickets der matcher dine filtre.</p></div></td></tr>@endforelse
 </tbody></table></div>
 <div class="nx-mobile-list">
 @forelse($tickets as $ticket)<div class="nx-mobile-card"><div class="nx-mobile-top"><strong>#{{ $ticket->id }} · {{ $ticket->username ?: 'Kunde #'.$ticket->user_id }}</strong>@php($ml=['open'=>['primary','Åben'],'customer_reply'=>['danger','Kundesvar'],'answered'=>['success','Besvaret'],'closed'=>['default','Lukket']]) @php($ms=$ml[$ticket->status]??['warning',$ticket->status])<span class="label label-{{ $ms[0] }}">{{ $ms[1] }}</span></div><div class="nx-mobile-subject">{{ $ticket->subject }}</div><div class="nx-mobile-meta"><span><i class="fa fa-folder-o"></i> {{ ['support'=>'Support','billing'=>'Fakturering','sales'=>'Salg'][$ticket->department] ?? ucfirst($ticket->department) }}</span><span><i class="fa fa-flag-o"></i> {{ ['high'=>'Høj','normal'=>'Normal','low'=>'Lav'][$ticket->priority] ?? ucfirst($ticket->priority) }}</span><span><i class="fa fa-clock-o"></i> {{ \Carbon\Carbon::parse($ticket->updated_at)->diffForHumans() }}</span></div><a href="{{ route('admin.tickets.show',$ticket->id) }}" class="btn btn-sm">Åbn ticket <i class="fa fa-angle-right pull-right"></i></a></div>@empty<div class="ticket-empty"><div class="empty-icon"><i class="fa fa-inbox"></i></div><h4>Ingen tickets fundet</h4><p>Der er ingen tickets der matcher dine filtre.</p></div>@endforelse
 </div>
</div>
@endsection