@extends('store.layout')
@section('title','Vidensbase')
@section('description','Find guides, svar og vejledninger i Nodexa Vidensbase.')
@push('styles')@include('store.knowledgebase.partials.styles')@endpush
@section('content')
<section class="kbHero"><div class="container"><div class="eyebrow">NODEXA SUPPORT</div><h1>Hvordan kan vi hjælpe?</h1><p>Søg i guides og løsninger, eller vælg en kategori nedenfor.</p><form class="kbSearch" action="{{ route('knowledgebase.search') }}" method="GET"><input type="search" name="q" placeholder="Søg i vidensbasen..." autocomplete="off"><button class="btn primary" type="submit">Søg</button></form></div></section>
<section class="kbShell"><div class="container">
<div class="kbSectionHead"><div><div class="sectionNo">KNOWLEDGEBASE</div><h2>Kategorier</h2></div></div>
@if($categories->isNotEmpty())<div class="kbGrid">@foreach($categories as $category)<a class="kbCategory" href="{{ route('knowledgebase.category',$category) }}"><div class="kbCategoryTop"><span class="kbCatIcon"><i class="fa {{ $category->icon ?: 'fa-book' }}"></i></span><span class="kbCount">{{ $category->articles_count }} artikler</span></div><h3>{{ $category->name }}</h3><p>{{ $category->description ?: 'Se guides og svar i denne kategori.' }}</p>@if($category->articles->isNotEmpty())<div class="kbArticleLinks">@foreach($category->articles as $article)<span>→ {{ $article->title }}</span>@endforeach</div>@endif</a>@endforeach</div>@else<div class="kbEmpty">Der er endnu ikke oprettet kategorier i vidensbasen.</div>@endif
@if($featured->isNotEmpty())<div class="kbSection"><div class="kbSectionHead"><div><div class="sectionNo">ANBEFALET</div><h2>Udvalgte artikler</h2></div></div><div class="kbArticleList">@foreach($featured as $article)<a class="kbArticleRow" href="{{ route('knowledgebase.article',$article) }}"><div><strong>{{ $article->title }}</strong><small>{{ $article->summary ?: $article->category->name }}</small></div><div class="kbMeta"><span>{{ $article->category->name }}</span><span>·</span><span>{{ number_format($article->views,0,',','.') }} visninger</span></div></a>@endforeach</div></div>@endif
@if($popular->isNotEmpty())<div class="kbSection"><div class="kbSectionHead"><div><div class="sectionNo">POPULÆRT</div><h2>Mest læste</h2></div></div><div class="kbArticleList">@foreach($popular as $article)<a class="kbArticleRow" href="{{ route('knowledgebase.article',$article) }}"><div><strong>{{ $article->title }}</strong><small>{{ $article->summary ?: 'Åbn artiklen for at læse mere.' }}</small></div><div class="kbMeta"><span>{{ number_format($article->views,0,',','.') }} visninger</span><span>→</span></div></a>@endforeach</div></div>@endif
</div></section>
@endsection