<!doctype html>
<html lang="da">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Client API Keys · Nodexa</title>
<style>
:root{color-scheme:dark;--bg:#07131f;--panel:#102132;--panel2:#172e46;--top:#171b29;--blue:#3585ea;--text:#f8fafd;--muted:#9ba9bc;--red:#ff718b;--green:#37d29f;--border:#29425c}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.top{height:82px;background:var(--top);display:flex;align-items:center;padding:0 28px;border-bottom:1px solid #20283a}.brand{font-size:28px;font-weight:800}.brand span{color:var(--blue)}.wrap{max-width:980px;margin:0 auto;padding:34px 20px 70px}.head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:24px}.head h1{margin:0 0 6px;font-size:32px}.head p{margin:0;color:var(--muted)}button,a.btn{border:0;border-radius:10px;padding:11px 16px;font-weight:700;font-size:14px;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.primary{background:var(--blue);color:white}.secondary{background:#1b3046;color:var(--text);border:1px solid var(--border)}.danger{background:transparent;color:var(--red);border:1px solid #6b3441}.card{background:var(--panel);border:1px solid #17304a;border-radius:16px;overflow:hidden}.row{display:grid;grid-template-columns:1fr 180px 190px 90px;gap:12px;align-items:center;padding:18px 20px;border-top:1px solid #1e3952}.row:first-child{border-top:0}.name{font-weight:750}.meta{color:var(--muted);font-size:13px;margin-top:4px}.prefix{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:#b9d2f8;background:#091725;padding:7px 10px;border-radius:8px;display:inline-block}.empty{padding:36px 20px;text-align:center;color:var(--muted)}.notice{margin-bottom:18px;background:#0d2941;border:1px solid #1f5e91;padding:14px 16px;border-radius:12px;color:#cfe5ff}.error{margin-bottom:18px;background:#321925;border:1px solid #6e3043;padding:14px 16px;border-radius:12px;color:#ff9eb0}.modal{position:fixed;inset:0;background:#000a;display:none;align-items:center;justify-content:center;padding:20px}.modal.show{display:flex}.modalbox{width:min(620px,100%);background:var(--panel);border:1px solid #27435f;border-radius:18px;padding:22px}.modalbox h2{margin:0 0 8px}.modalbox p{color:var(--muted)}label{display:block;font-size:13px;color:var(--muted);margin:16px 0 7px}input{width:100%;background:#081522;border:1px solid #39506a;color:white;border-radius:10px;padding:12px 13px;font-size:15px;outline:none}input:focus{border-color:var(--blue)}.secret{display:block;word-break:break-all;background:#06101a;border:1px solid #27415b;color:white;padding:14px;border-radius:10px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;margin:15px 0}.actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}@media(max-width:720px){.row{grid-template-columns:1fr}.head{flex-direction:column}.top{padding:0 18px}.wrap{padding:24px 14px}.actions{flex-wrap:wrap}}
</style>
</head>
<body>
<div class="top"><div class="brand">NOD<span>EXA</span></div></div>
<main class="wrap">
  <div class="head"><div><h1>Client API Keys</h1><p>Opret API-nøgler til Nodexa-appen og andre klienter. Nye nøgler bruger altid <strong>nxa_</strong>.</p></div><div style="display:flex;gap:10px"><a class="btn secondary" href="/">Tilbage</a><button class="primary" id="create">+ Opret API key</button></div></div>
  <div class="notice">Nodexa bruger formatet <strong>nxa_</strong> + 48 tilfældige bogstaver/tal. Den fulde nøgle vises kun én gang og gemmes kun hashed på serveren.</div>
  <div id="error"></div>
  <div class="card" id="list"><div class="empty">Henter API keys…</div></div>
</main>
<div class="modal" id="modal"><div class="modalbox"><h2>Opret Client API key</h2><p>Giv nøglen et navn, så du kan kende den senere.</p><label>Navn</label><input id="keyName" placeholder="F.eks. Nodexa Android"><div class="actions"><button class="secondary" id="cancel">Annuller</button><button class="primary" id="confirm">Opret</button></div></div></div>
<div class="modal" id="secretModal"><div class="modalbox"><h2>Din nye Nodexa API key</h2><p>Kopiér den nu. Af sikkerhedsgrunde kan den ikke vises igen.</p><code class="secret" id="secret"></code><div class="actions"><button class="secondary" id="copy">Kopiér</button><button class="primary" id="done">Færdig</button></div></div></div>
<script>
const token=localStorage.getItem('nodexa_panel_token');
const list=document.getElementById('list'),err=document.getElementById('error'),modal=document.getElementById('modal'),secretModal=document.getElementById('secretModal');
const headers={'Accept':'application/json','Content-Type':'application/json',...(token?{'Authorization':'Bearer '+token}:{})};
function fail(message){err.innerHTML='<div class="error">'+String(message).replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))+'</div>'}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...headers,...(options.headers||{})}});if(r.status===401){location.href='/';throw new Error('Din session er udløbet. Log ind igen.')}if(!r.ok){let x={};try{x=await r.json()}catch{}throw new Error(x.message||('HTTP '+r.status))}return r.status===204?null:r.json()}
function date(v){if(!v)return 'Aldrig';try{return new Date(v).toLocaleString('da-DK')}catch{return v}}
async function load(){err.innerHTML='';try{const keys=await api('/api/client-api-keys');if(!keys.length){list.innerHTML='<div class="empty">Du har ingen Nodexa Client API keys endnu.</div>';return}list.innerHTML=keys.map(k=>`<div class="row"><div><div class="name">${String(k.name||'Client API').replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}</div><div class="meta">Oprettet ${date(k.created_at)}</div></div><div><span class="prefix">nxa_••••••••••</span></div><div class="meta">Sidst brugt: ${date(k.last_used_at)}</div><button class="danger" onclick="removeKey(${Number(k.id)})">Slet</button></div>`).join('')}catch(e){fail(e.message);list.innerHTML='<div class="empty">Kunne ikke hente API keys.</div>'}}
async function removeKey(id){if(!confirm('Slet denne API key? Klienter der bruger den mister adgang med det samme.'))return;try{await api('/api/client-api-keys/'+id,{method:'DELETE'});load()}catch(e){fail(e.message)}}
document.getElementById('create').onclick=()=>{document.getElementById('keyName').value='Nodexa Android';modal.classList.add('show')};document.getElementById('cancel').onclick=()=>modal.classList.remove('show');
document.getElementById('confirm').onclick=async()=>{try{const x=await api('/api/client-api-keys',{method:'POST',body:JSON.stringify({name:document.getElementById('keyName').value})});modal.classList.remove('show');document.getElementById('secret').textContent=x.token;secretModal.classList.add('show');load()}catch(e){fail(e.message)}};
document.getElementById('copy').onclick=async()=>{await navigator.clipboard.writeText(document.getElementById('secret').textContent);document.getElementById('copy').textContent='Kopieret'};document.getElementById('done').onclick=()=>secretModal.classList.remove('show');
if(!token){fail('Du skal være logget ind i Nodexa-panelet først.');list.innerHTML='<div class="empty"><a class="btn primary" href="/">Gå til login</a></div>'}else load();
</script>
</body>
</html>
