<!doctype html>
<html lang="da">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nodexa · Fejl</title>
<style>
:root{color-scheme:dark;--bg:#071019;--card:#0c1722;--line:#1c2b38;--muted:#8ea0b1;--purple:#7c3aed;--red:#ef4444;--orange:#f59e0b;--green:#22c55e}*{box-sizing:border-box}body{margin:0;font:14px/1.45 Inter,system-ui,sans-serif;background:radial-gradient(circle at top,#101a2a 0,#071019 40%);color:#eef5fb}header{height:70px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:#08121c}.brand{font-size:22px;font-weight:800}.brand span{color:#9b6cff}.wrap{max-width:1500px;margin:0 auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:22px}.top h1{margin:0 0 6px;font-size:28px}.top p{margin:0;color:var(--muted)}button,select{background:#111f2c;border:1px solid var(--line);color:#fff;padding:10px 14px;border-radius:9px;cursor:pointer}.primary{background:linear-gradient(135deg,#6d28d9,#7c3aed);border-color:#7c3aed}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.metric,.card{background:rgba(12,23,34,.94);border:1px solid var(--line);border-radius:14px}.metric{padding:18px}.metric small{color:var(--muted);display:block}.metric strong{font-size:26px;margin-top:5px;display:block}.filters{display:flex;gap:10px;padding:14px;margin-bottom:14px}.table-card{overflow:hidden}table{width:100%;border-collapse:collapse}th,td{padding:14px 16px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:12px;color:#8ea0b1;text-transform:uppercase}.badge{display:inline-flex;align-items:center;padding:4px 8px;border-radius:999px;font-size:12px}.critical{background:#3b1117;color:#ff9393}.error{background:#341b20;color:#ffaaa5}.warning{background:#39290d;color:#ffd67d}.open{color:#ff8585}.resolved{color:#70dc92}.msg{max-width:560px;color:#c6d2dd;margin-top:4px}.muted{color:var(--muted)}.source{font-family:ui-monospace,monospace;color:#bba4ff}.empty{text-align:center;padding:40px;color:var(--muted)}.bar{display:flex;gap:8px;align-items:center}.back{color:#cdbaff;text-decoration:none}.diagnosis{margin-top:9px;padding:10px 12px;border-radius:9px;background:#0a1320;border:1px solid #1c3042}.diagnosis b{color:#cdbaff}.recommend{margin-top:7px;color:#a9dfba}.technical{margin-top:8px}.technical summary{cursor:pointer;color:#8397aa}.technical pre{white-space:pre-wrap;word-break:break-word;font:12px ui-monospace,monospace;color:#8fa4b8;background:#071019;border:1px solid var(--line);padding:10px;border-radius:8px;max-width:620px}.scan-status{margin-bottom:14px;padding:12px 14px;display:none}.scan-status.show{display:block}.scan-status.ok{border-color:#245a38;color:#8de8ac}.scan-status.bad{border-color:#69343a;color:#ffaaa5}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.wrap{padding:18px}.table-card{overflow:auto}}
</style>
</head>
<body>
<header><div class="brand">NODE<span>XA</span></div><a class="back" href="/">← Tilbage til adminpanelet</a></header>
<div class="wrap">
 <div class="top"><div><h1>Fejl & Systemstatus</h1><p>Nodexa analyserer selv nodes, Agent, database, Redis, queue, Docker, Nginx, diskplads og Database Hosts.</p></div><div class="bar"><button id="refresh">Opdater</button><button id="scan" class="primary">Kør fuld diagnose</button></div></div>
 <div id="scanStatus" class="card scan-status"></div>
 <div class="grid"><div class="metric"><small>Åbne fejl</small><strong id="mOpen">0</strong></div><div class="metric"><small>Kritiske</small><strong id="mCritical">0</strong></div><div class="metric"><small>Node/System fejl</small><strong id="mNodes">0</strong></div><div class="metric"><small>Løst</small><strong id="mResolved">0</strong></div></div>
 <div class="card filters"><select id="status"><option value="">Alle statusser</option><option value="open">Åbne</option><option value="resolved">Løste</option></select><select id="source"><option value="">Alle kilder</option><option value="node">Nodes</option><option value="agent">Agent</option><option value="system">System</option><option value="database-host">Database Hosts</option><option value="panel">Panel</option><option value="frontend">Frontend</option></select></div>
 <div class="card table-card"><table><thead><tr><th>Status</th><th>Alvorlighed</th><th>Kilde</th><th>Diagnose</th><th>Senest set</th><th>Antal</th><th></th></tr></thead><tbody id="rows"></tbody></table><div class="empty" id="empty" hidden>Ingen fejl fundet.</div></div>
</div>
<script>
const token=localStorage.getItem('nodexa_panel_token');if(!token)location.href='/';
const headers={Authorization:'Bearer '+token,Accept:'application/json','Content-Type':'application/json'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers,...(opt.headers||{})}});if(r.status===401||r.status===403){location.href='/';throw new Error('Unauthorized')}if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function issueHtml(i){const ctx=i.context||{};const diagnosis=ctx.diagnosis||'Nodexa har registreret fejlen, men har ikke en specifik automatisk diagnose endnu.';const rec=ctx.recommendation||'Åbn de tekniske detaljer og kontroller den berørte service.';return `<tr><td class="${i.status}">${i.status==='open'?'Åben':'Løst'}</td><td><span class="badge ${esc(i.severity)}">${esc(i.severity)}</span></td><td><span class="source">${esc(i.source)}</span>${i.node_id?`<div class="muted">Node #${i.node_id}</div>`:''}${i.server_id?`<div class="muted">Server ${esc(i.server_id)}</div>`:''}</td><td><strong>${esc(i.title)}</strong><div class="msg">${esc(i.message||'')}</div><div class="diagnosis"><b>Fundet årsag:</b> ${esc(diagnosis)}<div class="recommend"><b>Forslag:</b> ${esc(rec)}</div></div><details class="technical"><summary>Tekniske detaljer</summary><pre>${esc(JSON.stringify(ctx,null,2))}</pre></details></td><td>${i.last_seen_at?new Date(i.last_seen_at).toLocaleString('da-DK'):'-'}</td><td>${i.occurrences}</td><td>${i.status==='open'?`<button onclick="resolveIssue(${i.id})">Marker løst</button>`:''}</td></tr>`}
async function load(){const q=new URLSearchParams();if(status.value)q.set('status',status.value);if(source.value)q.set('source',source.value);const data=await api('/api/system-errors?'+q);const all=data.data||[];rows.innerHTML=all.map(issueHtml).join('');empty.hidden=all.length>0;mOpen.textContent=all.filter(x=>x.status==='open').length;mCritical.textContent=all.filter(x=>x.status==='open'&&x.severity==='critical').length;mNodes.textContent=all.filter(x=>x.status==='open'&&['node','agent','system','database-host'].includes(x.source)).length;mResolved.textContent=all.filter(x=>x.status==='resolved').length}
async function resolveIssue(id){await api('/api/system-errors/'+id+'/resolve',{method:'POST'});load()}
scan.onclick=async()=>{scan.disabled=true;scan.textContent='Analyserer…';scanStatus.className='card scan-status show';scanStatus.textContent='Nodexa kontrollerer systemservices, lagring, databaser og alle Nodes…';try{const r=await api('/api/system-errors/scan-all',{method:'POST'});const failed=(r.system?.checks||[]).filter(x=>x.status!=='ok').length;const down=(r.nodes||[]).filter(x=>!x.online).length;scanStatus.className='card scan-status show '+(failed||down?'bad':'ok');scanStatus.textContent=failed||down?`Diagnose færdig: ${failed} systemfejl og ${down} utilgængelige Nodes fundet.`:'Diagnose færdig: Alle kontroller bestået.';await load()}catch(e){scanStatus.className='card scan-status show bad';scanStatus.textContent='Diagnosen kunne ikke gennemføres: '+e.message}finally{scan.disabled=false;scan.textContent='Kør fuld diagnose'}};refresh.onclick=load;status.onchange=load;source.onchange=load;load();setInterval(load,30000);
</script>
</body></html>
