<!doctype html>
<html lang="da">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nodexa · Fejl</title>
<style>
:root{color-scheme:dark;--bg:#071019;--card:#0c1722;--line:#1c2b38;--muted:#8ea0b1;--purple:#7c3aed;--red:#ef4444;--orange:#f59e0b;--green:#22c55e}*{box-sizing:border-box}body{margin:0;font:14px/1.45 Inter,system-ui,sans-serif;background:radial-gradient(circle at top,#101a2a 0,#071019 40%);color:#eef5fb}header{height:70px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:#08121c}.brand{font-size:22px;font-weight:800}.brand span{color:#9b6cff}.wrap{max-width:1450px;margin:0 auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:22px}.top h1{margin:0 0 6px;font-size:28px}.top p{margin:0;color:var(--muted)}button,select{background:#111f2c;border:1px solid var(--line);color:#fff;padding:10px 14px;border-radius:9px;cursor:pointer}.primary{background:linear-gradient(135deg,#6d28d9,#7c3aed);border-color:#7c3aed}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.metric,.card{background:rgba(12,23,34,.94);border:1px solid var(--line);border-radius:14px}.metric{padding:18px}.metric small{color:var(--muted);display:block}.metric strong{font-size:26px;margin-top:5px;display:block}.filters{display:flex;gap:10px;padding:14px;margin-bottom:14px}.table-card{overflow:hidden}table{width:100%;border-collapse:collapse}th,td{padding:14px 16px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{font-size:12px;color:#8ea0b1;text-transform:uppercase}.badge{display:inline-flex;align-items:center;padding:4px 8px;border-radius:999px;font-size:12px}.critical{background:#3b1117;color:#ff9393}.error{background:#341b20;color:#ffaaa5}.warning{background:#39290d;color:#ffd67d}.open{color:#ff8585}.resolved{color:#70dc92}.msg{max-width:520px;color:#c6d2dd}.muted{color:var(--muted)}.source{font-family:ui-monospace,monospace;color:#bba4ff}.empty{text-align:center;padding:40px;color:var(--muted)}.bar{display:flex;gap:8px;align-items:center}.back{color:#cdbaff;text-decoration:none}.context{font-size:12px;margin-top:5px;color:#8296a8;word-break:break-word}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.wrap{padding:18px}.table-card{overflow:auto}}
</style>
</head>
<body>
<header><div class="brand">NODE<span>XA</span></div><a class="back" href="/">← Tilbage til adminpanelet</a></header>
<div class="wrap">
 <div class="top"><div><h1>Fejl & Systemstatus</h1><p>Node-nedbrud, Agent-forbindelser og fejl i Nodexa-panelet samles her.</p></div><div class="bar"><button id="refresh">Opdater</button><button id="scan" class="primary">Tjek alle Nodes</button></div></div>
 <div class="grid"><div class="metric"><small>Åbne fejl</small><strong id="mOpen">0</strong></div><div class="metric"><small>Kritiske</small><strong id="mCritical">0</strong></div><div class="metric"><small>Node fejl</small><strong id="mNodes">0</strong></div><div class="metric"><small>Løst</small><strong id="mResolved">0</strong></div></div>
 <div class="card filters"><select id="status"><option value="">Alle statusser</option><option value="open">Åbne</option><option value="resolved">Løste</option></select><select id="source"><option value="">Alle kilder</option><option value="node">Nodes</option><option value="agent">Agent</option><option value="panel">Panel</option><option value="frontend">Frontend</option></select></div>
 <div class="card table-card"><table><thead><tr><th>Status</th><th>Alvorlighed</th><th>Kilde</th><th>Fejl</th><th>Senest set</th><th>Antal</th><th></th></tr></thead><tbody id="rows"></tbody></table><div class="empty" id="empty" hidden>Ingen fejl fundet.</div></div>
</div>
<script>
const token=localStorage.getItem('nodexa_panel_token');
if(!token) location.href='/';
const headers={Authorization:'Bearer '+token,Accept:'application/json','Content-Type':'application/json'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers,...(opt.headers||{})}});if(r.status===401||r.status===403){location.href='/';throw new Error('Unauthorized')}if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function load(){const q=new URLSearchParams();if(status.value)q.set('status',status.value);if(source.value)q.set('source',source.value);const data=await api('/api/system-errors?'+q);const all=data.data||[];rows.innerHTML=all.map(i=>`<tr><td class="${i.status}">${i.status==='open'?'Åben':'Løst'}</td><td><span class="badge ${esc(i.severity)}">${esc(i.severity)}</span></td><td><span class="source">${esc(i.source)}</span>${i.node_id?`<div class="muted">Node #${i.node_id}</div>`:''}</td><td><strong>${esc(i.title)}</strong><div class="msg">${esc(i.message||'')}</div>${i.context?`<div class="context">${esc(JSON.stringify(i.context))}</div>`:''}</td><td>${i.last_seen_at?new Date(i.last_seen_at).toLocaleString('da-DK'):'-'}</td><td>${i.occurrences}</td><td>${i.status==='open'?`<button onclick="resolveIssue(${i.id})">Marker løst</button>`:''}</td></tr>`).join('');empty.hidden=all.length>0;mOpen.textContent=all.filter(x=>x.status==='open').length;mCritical.textContent=all.filter(x=>x.status==='open'&&x.severity==='critical').length;mNodes.textContent=all.filter(x=>x.status==='open'&&x.source==='node').length;mResolved.textContent=all.filter(x=>x.status==='resolved').length}
async function resolveIssue(id){await api('/api/system-errors/'+id+'/resolve',{method:'POST'});load()}
scan.onclick=async()=>{scan.disabled=true;scan.textContent='Tjekker…';try{await api('/api/system-errors/scan-nodes',{method:'POST'});await load()}finally{scan.disabled=false;scan.textContent='Tjek alle Nodes'}};refresh.onclick=load;status.onchange=load;source.onchange=load;load();setInterval(load,30000);
</script>
</body></html>
