<!doctype html>
<html lang="da">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nodexa · Opdateringer</title>
<style>
:root{color-scheme:dark;--bg:#071019;--card:#0c1722;--line:#1c2b38;--muted:#8ea0b1;--purple:#7c3aed;--green:#22c55e;--red:#ef4444;--amber:#f59e0b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#12182c 0,#071019 42%);color:#eef5fb;font:14px/1.5 Inter,system-ui,sans-serif}header{height:70px;padding:0 28px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;background:#08121c}.brand{font-size:22px;font-weight:800}.brand span{color:#9b6cff}.back{color:#ccbaff;text-decoration:none}.wrap{max-width:1100px;margin:0 auto;padding:32px 20px}.hero{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:22px}.hero h1{margin:0 0 7px;font-size:30px}.hero p{margin:0;color:var(--muted)}.card{background:rgba(12,23,34,.96);border:1px solid var(--line);border-radius:15px;padding:20px;margin-bottom:16px}.status{display:flex;align-items:center;justify-content:space-between;gap:18px}.pill{display:inline-flex;align-items:center;gap:7px;border-radius:999px;padding:7px 11px;font-weight:700}.pill.current{background:#11331f;color:#75e39a}.pill.available{background:#2c1b50;color:#cab7ff}.pill.running{background:#3a2b0b;color:#ffd477}.pill.failed{background:#3a151a;color:#ff9b9b}.versions{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.version{padding:16px;border:1px solid var(--line);border-radius:12px;background:#09131e}.version small{color:var(--muted);display:block;margin-bottom:7px}.version code{font-size:18px;color:#d8ccff}.commit-msg{margin-top:8px;color:#c8d3dd}.actions{display:flex;gap:10px;flex-wrap:wrap}button{border:1px solid var(--line);background:#12202d;color:white;border-radius:10px;padding:11px 16px;font-weight:700;cursor:pointer}button.primary{background:linear-gradient(135deg,#6d28d9,#7c3aed);border-color:#7c3aed}button:disabled{opacity:.5;cursor:not-allowed}.info{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.info div{border:1px solid var(--line);border-radius:12px;padding:14px}.info strong{display:block;margin-bottom:5px}.info span{color:var(--muted)}pre{margin:0;background:#050b11;border:1px solid #172533;border-radius:12px;padding:16px;min-height:180px;max-height:420px;overflow:auto;white-space:pre-wrap;color:#b9c8d4;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.hidden{display:none}.errorbox{background:#35151b;border:1px solid #64262f;color:#ffb2b2;border-radius:10px;padding:12px;margin-top:12px}@media(max-width:760px){.versions,.info{grid-template-columns:1fr}.status{align-items:flex-start;flex-direction:column}.hero{flex-direction:column}}
</style>
</head>
<body>
<header><div class="brand">NODE<span>XA</span></div><a class="back" href="/">← Tilbage til adminpanelet</a></header>
<div class="wrap">
 <div class="hero"><div><h1>Nodexa Opdateringer</h1><p>Kontroller GitHub og opdater hele platformen uden at geninstallere manuelt.</p></div><button id="checkBtn">Kontroller igen</button></div>
 <div class="card">
  <div class="status"><div><span id="statusPill" class="pill current">Kontrollerer…</span><h2 id="statusTitle">Kontrollerer Nodexa</h2><p id="statusText" style="color:var(--muted);margin:0">Henter seneste version fra GitHub.</p></div><div class="actions"><button id="updateBtn" class="primary" disabled>Installer opdatering</button></div></div>
  <div id="errorBox" class="errorbox hidden"></div>
  <div class="versions"><div class="version"><small>Installeret</small><code id="installedCommit">—</code><div id="installedVersion" class="commit-msg">Version —</div></div><div class="version"><small>Seneste på GitHub</small><code id="latestCommit">—</code><div id="latestMessage" class="commit-msg">—</div></div></div>
 </div>
 <div class="card info"><div><strong>Indstillinger bevares</strong><span>.env, database, uploads, storage og eksisterende serverdata bliver ikke slettet.</span></div><div><strong>Automatiske migrations</strong><span>Nodexa kører Composer, database-migrations og frontend-build som del af opdateringen.</span></div><div><strong>Agent opdateres</strong><span>Hvis Nodexa Agent er installeret lokalt, bliver binæren genbygget og servicen genstartet.</span></div></div>
 <div id="progressCard" class="card hidden"><h3>Opdateringsstatus</h3><p id="progressText" style="color:var(--muted)">Starter…</p><pre id="log">Venter på updater-log…</pre></div>
</div>
<script>
const token=localStorage.getItem('nodexa_panel_token');if(!token)location.href='/';
const headers={Authorization:'Bearer '+token,Accept:'application/json','Content-Type':'application/json'};
const q=id=>document.getElementById(id);let updateAvailable=false,poll=null;
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{...headers,...(opt.headers||{})}});const txt=await r.text();let data={};try{data=txt?JSON.parse(txt):{}}catch{data={message:txt}}if(r.status===401||r.status===403){location.href='/';throw new Error('Unauthorized')}if(!r.ok)throw Object.assign(new Error(data.message||'Request failed'),{status:r.status,data});return data}
function setPill(type,text){const p=q('statusPill');p.className='pill '+type;p.textContent=text}
async function check(){q('errorBox').classList.add('hidden');q('checkBtn').disabled=true;try{const d=await api('/api/admin/update/check');updateAvailable=!!d.available;q('installedCommit').textContent=d.installed?.short_commit||'ukendt';q('installedVersion').textContent='Version '+(d.installed?.version||'ukendt');q('latestCommit').textContent=d.latest?.short_commit||'—';q('latestMessage').textContent=d.latest?.message||'Ingen commit-besked';if(d.state?.status==='running'){showRunning();return}if(d.available){setPill('available','Opdatering tilgængelig');q('statusTitle').textContent='Der er en ny Nodexa-opdatering';q('statusText').textContent='En nyere commit findes på GitHub.';q('updateBtn').disabled=false}else if(d.installation_known===false){setPill('current','Status ukendt');q('statusTitle').textContent='Installeret version registreres';q('statusText').textContent='Nodexa viser ikke en opdateringsadvarsel, før den installerede commit er kendt. Kør den aktuelle updater én gang for at registrere versionen.';q('updateBtn').disabled=true}else{setPill('current','Opdateret');q('statusTitle').textContent='Nodexa er opdateret';q('statusText').textContent='Denne installation matcher den seneste version på GitHub.';q('updateBtn').disabled=true}}catch(e){updateAvailable=false;setPill('failed','Kunne ikke kontrollere');q('statusTitle').textContent='GitHub-kontrol fejlede';q('statusText').textContent='Ingen opdateringsadvarsel vises, før kontrollen lykkes.';q('updateBtn').disabled=true;q('errorBox').textContent=e.message;q('errorBox').classList.remove('hidden')}finally{q('checkBtn').disabled=false}}
function showRunning(){setPill('running','Opdaterer');q('statusTitle').textContent='Nodexa opdateres';q('statusText').textContent='Du kan lade siden stå åben. Servicen fortsætter i baggrunden.';q('updateBtn').disabled=true;q('progressCard').classList.remove('hidden');startPoll()}
async function status(){try{const d=await api('/api/admin/update/status');const s=d.state||{};q('progressText').textContent=s.message||s.status||'Opdaterer…';q('log').textContent=d.log||'Ingen log endnu.';q('log').scrollTop=q('log').scrollHeight;if(s.status==='running'){setPill('running','Opdaterer')}else if(s.status==='success'){setPill('current','Opdateret');q('statusTitle').textContent='Opdateringen er færdig';q('statusText').textContent='Nodexa blev opdateret korrekt.';clearInterval(poll);poll=null;setTimeout(check,1000)}else if(s.status==='failed'){setPill('failed','Fejlede');q('statusTitle').textContent='Opdateringen fejlede';q('statusText').textContent='Se loggen nedenfor for den konkrete fejl.';clearInterval(poll);poll=null}}catch{}}
function startPoll(){if(poll)return;status();poll=setInterval(status,2000)}
q('updateBtn').onclick=async()=>{if(!updateAvailable||!confirm('Installer den seneste Nodexa-opdatering nu?'))return;q('updateBtn').disabled=true;try{await api('/api/admin/update/run',{method:'POST'});showRunning()}catch(e){q('errorBox').textContent=e.message;q('errorBox').classList.remove('hidden');q('updateBtn').disabled=false}};
q('checkBtn').onclick=check;
check();status();
</script>
</body></html>
