<!doctype html>
<html lang="da">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nodexa · Storefronts</title>
<style>
:root{color-scheme:dark;--bg:#080a0f;--surface:#11151d;--surface2:#151a24;--line:#293142;--text:#f4f6fb;--muted:#929caf;--purple:#745cff;--red:#fb7185;--green:#34d399}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 10% -10%,rgba(116,92,255,.16),transparent 35%),var(--bg);color:var(--text);font:14px Inter,system-ui,sans-serif}.wrap{width:min(1250px,calc(100% - 28px));margin:0 auto;padding:36px 0 80px}.top{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:26px}.crumb{color:#8f99aa;font-size:12px}.top h1{font-size:32px;margin:6px 0}.btn{border:1px solid var(--line);background:#171c27;color:white;padding:10px 13px;border-radius:10px;font-weight:800;cursor:pointer}.primary{background:linear-gradient(135deg,#6550ef,#8d63ff);border:0}.danger{color:#ff9aac}.grid{display:grid;grid-template-columns:340px 1fr;gap:18px}.card{border:1px solid var(--line);background:linear-gradient(180deg,#11161f,#0e1219);border-radius:16px;padding:18px}.site{display:block;width:100%;text-align:left;border:1px solid var(--line);background:#0e131b;color:white;border-radius:12px;padding:14px;margin-bottom:10px;cursor:pointer}.site.active{border-color:#6655dc;background:#17142a}.site strong{display:block;font-size:15px}.site small{color:#8c96a7}.badges{display:flex;gap:6px;margin-top:9px}.badge{font-size:9px;padding:4px 7px;border-radius:999px;background:#222837;color:#aeb8ca}.badge.ok{background:#10261f;color:#70deb4}.badge.default{background:#251f49;color:#b8a8ff}.empty{color:#8f99aa;padding:24px 8px;text-align:center}.formGrid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.wide{grid-column:1/-1}label span{display:block;color:#a6afbf;font-size:11px;font-weight:800;margin:0 0 7px}input,textarea,select{width:100%;padding:11px 12px;border-radius:9px;border:1px solid #2a3242;background:#090d13;color:white;outline:none}textarea{min-height:88px;resize:vertical}.check{display:flex;align-items:center;gap:8px;margin-top:8px}.check input{width:auto}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:16px}.products{margin-top:20px;border-top:1px solid var(--line);padding-top:18px}.productRow{display:grid;grid-template-columns:1fr 130px 100px auto;gap:10px;align-items:center;border:1px solid #242c3a;background:#0d1118;border-radius:11px;padding:11px;margin-bottom:8px}.productRow small{color:#8c96a7}.domainNote{margin:14px 0;padding:12px;border:1px solid #3b345e;background:#171329;border-radius:10px;color:#b9afe3;font-size:12px;line-height:1.5}.error{padding:10px 12px;border:1px solid #6b2d3b;background:#29121a;border-radius:9px;color:#ffb0be;margin:10px 0}.success{padding:10px 12px;border:1px solid #235b49;background:#10251e;border-radius:9px;color:#8ce7c3;margin:10px 0}@media(max-width:850px){.grid{grid-template-columns:1fr}.formGrid{grid-template-columns:1fr}.wide{grid-column:auto}.productRow{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style>
</head>
<body><div class="wrap"><div class="top"><div><div class="crumb">NODEXA ADMIN · MULTISITE</div><h1>Storefronts</h1><div style="color:#939dad">Administrer flere brands og domæner fra samme Nodexa-installation.</div></div><div><button class="btn" onclick="location.href='/'">← Panel</button> <button class="btn primary" onclick="newSite()">+ Ny storefront</button></div></div><div id="message"></div><div class="grid"><aside class="card"><div id="sites"></div></aside><section class="card" id="editor"><div class="empty">Vælg en storefront eller opret en ny.</div></section></div></div>
<script>
const token=localStorage.getItem('nodexa_panel_token');
const headers={'Authorization':'Bearer '+token,'Accept':'application/json','Content-Type':'application/json'};
let sites=[], current=null, creating=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function msg(text,type='success'){document.getElementById('message').innerHTML=`<div class="${type}">${esc(text)}</div>`;setTimeout(()=>document.getElementById('message').innerHTML='',4500)}
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{...headers,...(opts.headers||{})}});if(r.status===204)return null;const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||Object.values(d.errors||{}).flat().join(' ')||`HTTP ${r.status}`);return d}
async function boot(){if(!token)return location.href='/';const me=await api('/api/me').catch(()=>null);if(!me||!me.is_admin)return location.href='/';await load()}
async function load(){sites=await api('/api/admin/storefronts');renderSites();if(current){current=sites.find(s=>s.id===current.id)||null;if(current)renderEditor()}}
function renderSites(){document.getElementById('sites').innerHTML=sites.length?sites.map(s=>`<button class="site ${current&&current.id===s.id?'active':''}" onclick="selectSite(${s.id})"><strong>${esc(s.name)}</strong><small>${esc(s.primary_domain)}</small><div class="badges"><span class="badge ${s.enabled?'ok':''}">${s.enabled?'Aktiv':'Deaktiveret'}</span>${s.is_default?'<span class="badge default">Standard</span>':''}<span class="badge">${s.products_count??(s.products||[]).length} produkter</span></div></button>`).join(''):'<div class="empty">Ingen storefronts endnu.</div>'}
function selectSite(id){creating=false;current=sites.find(s=>s.id===id);renderSites();renderEditor()}
function newSite(){creating=true;current={name:'',slug:'',primary_domain:'',aliases:[],enabled:true,is_default:sites.length===0,logo_url:'',primary_color:'#745cff',accent_color:'#9a6dff',currency:'DKK',locale:'da-DK',title:'',tagline:'',description:'',support_email:'',panel_url:location.origin,products:[]};renderSites();renderEditor()}
function renderEditor(){const s=current;if(!s)return;document.getElementById('editor').innerHTML=`<div class="formGrid"><label><span>Navn / brand</span><input id="name" value="${esc(s.name)}"></label><label><span>Slug</span><input id="slug" value="${esc(s.slug)}" placeholder="revive-gaming"></label><label class="wide"><span>Primært domæne</span><input id="domain" value="${esc(s.primary_domain)}" placeholder="example.com"></label><label class="wide"><span>Aliases (kommasepareret)</span><input id="aliases" value="${esc((s.aliases||[]).join(', '))}" placeholder="www.example.com, shop.example.com"></label><label><span>Primær farve</span><input id="primary" value="${esc(s.primary_color||'#745cff')}"></label><label><span>Accentfarve</span><input id="accent" value="${esc(s.accent_color||'#9a6dff')}"></label><label><span>Valuta</span><input id="currency" value="${esc(s.currency||'DKK')}"></label><label><span>Locale</span><input id="locale" value="${esc(s.locale||'da-DK')}"></label><label class="wide"><span>SEO titel</span><input id="title" value="${esc(s.title||'')}"></label><label class="wide"><span>Hero tagline</span><input id="tagline" value="${esc(s.tagline||'')}"></label><label class="wide"><span>Beskrivelse</span><textarea id="description">${esc(s.description||'')}</textarea></label><label><span>Support e-mail</span><input id="support" value="${esc(s.support_email||'')}"></label><label><span>Kundeportal URL</span><input id="panelUrl" value="${esc(s.panel_url||'')}"></label></div><label class="check"><input id="enabled" type="checkbox" ${s.enabled?'checked':''}> Aktiv storefront</label><label class="check"><input id="default" type="checkbox" ${s.is_default?'checked':''}> Standard storefront</label><div class="domainNote"><b>Multisite:</b> Hvert domæne kan have sit eget brand, farver, produkter, priser, valuta og kurv. DNS skal pege mod denne Nodexa-server. Efter du tilføjer nye domæner, kør Nodexa-opdateringen for at synkronisere Nginx/SSL.</div><div class="actions">${!creating?'<button class="btn danger" onclick="deleteSite()">Slet</button>':''}<button class="btn primary" onclick="saveSite()">${creating?'Opret storefront':'Gem ændringer'}</button></div>${!creating?renderProducts(s):''}`}
function payload(){return {name:v('name'),slug:v('slug').toLowerCase().replace(/[^a-z0-9-]/g,'-'),primary_domain:v('domain'),aliases:v('aliases').split(',').map(x=>x.trim()).filter(Boolean),enabled:document.getElementById('enabled').checked,is_default:document.getElementById('default').checked,logo_url:null,primary_color:v('primary'),accent_color:v('accent'),currency:v('currency').toUpperCase(),locale:v('locale'),title:v('title')||null,tagline:v('tagline')||null,description:v('description')||null,support_email:v('support')||null,panel_url:v('panelUrl')||null,settings:{}}}
const v=id=>document.getElementById(id)?.value?.trim()||'';
async function saveSite(){try{if(creating){current=await api('/api/admin/storefronts',{method:'POST',body:JSON.stringify(payload())});creating=false}else current=await api('/api/admin/storefronts/'+current.id,{method:'PUT',body:JSON.stringify(payload())});msg('Storefront gemt.');await load();renderEditor()}catch(e){msg(e.message,'error')}}
async function deleteSite(){if(!confirm('Slet denne storefront og dens produkter?'))return;try{await api('/api/admin/storefronts/'+current.id,{method:'DELETE'});current=null;msg('Storefront slettet.');await load();document.getElementById('editor').innerHTML='<div class="empty">Vælg en storefront eller opret en ny.</div>'}catch(e){msg(e.message,'error')}}
function renderProducts(s){return `<div class="products"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><h2 style="margin:0">Produkter</h2><p style="color:#8f99aa;margin:5px 0 15px">Kataloget gælder kun ${esc(s.name)}.</p></div><button class="btn" onclick="addProduct()">+ Produkt</button></div><div id="productList">${(s.products||[]).map(p=>`<div class="productRow"><div><strong>${esc(p.name)}</strong><br><small>${esc(p.slug)} · ${esc(p.type)}</small></div><div>${(Number(p.price_cents||0)/100).toFixed(2)} ${esc(s.currency)}</div><div>${p.enabled?'Aktiv':'Skjult'}</div><div><button class="btn" onclick="editProduct(${p.id})">Rediger</button> <button class="btn danger" onclick="deleteProduct(${p.id})">Slet</button></div></div>`).join('')||'<div class="empty">Ingen produkter.</div>'}</div></div>`}
function productPrompt(base={}){const name=prompt('Produktnavn',base.name||'');if(name===null)return null;const slug=prompt('Slug',base.slug||name.toLowerCase().replace(/[^a-z0-9]+/g,'-'));if(slug===null)return null;const price=prompt('Pris i '+(current.currency||'DKK')+' (fx 129.00)',((base.price_cents||0)/100).toFixed(2));if(price===null)return null;const description=prompt('Beskrivelse',base.description||'')??'';const features=(prompt('Features, kommasepareret',(base.features||[]).join(', '))??'').split(',').map(x=>x.trim()).filter(Boolean);return {slug,name,description,price_cents:Math.round(Number(price.replace(',','.'))*100),billing_period:base.billing_period||'monthly',type:base.type||'game',features,enabled:base.enabled!==false,sort_order:base.sort_order||0,settings:{}}}
async function addProduct(){const p=productPrompt();if(!p)return;try{await api(`/api/admin/storefronts/${current.id}/products`,{method:'POST',body:JSON.stringify(p)});msg('Produkt oprettet.');await load()}catch(e){msg(e.message,'error')}}
async function editProduct(id){const old=(current.products||[]).find(p=>p.id===id);const p=productPrompt(old);if(!p)return;try{await api(`/api/admin/storefronts/${current.id}/products/${id}`,{method:'PUT',body:JSON.stringify({...old,...p})});msg('Produkt opdateret.');await load()}catch(e){msg(e.message,'error')}}
async function deleteProduct(id){if(!confirm('Slet produkt?'))return;try{await api(`/api/admin/storefronts/${current.id}/products/${id}`,{method:'DELETE'});msg('Produkt slettet.');await load()}catch(e){msg(e.message,'error')}}
boot();
</script></body></html>
