@extends('layouts.admin')
@section('title','Notification Center')
@section('content-header')
@php($invoiceCount=$items->where('type','invoice')->count()) @php($ticketCount=$items->where('type','ticket')->count()) @php($orderCount=$items->where('type','order')->count())
<div class="nc-title"><div><small>NODEXA OPERATIONS</small><h1>Notification Center</h1><p>Samlet action feed for fakturering, support og provisioning.</p></div><span class="nc-total"><i class="fa fa-bell"></i> {{$items->count()}} aktive</span></div>
@endsection
@section('content')
<style>.nc-title{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:20px}.nc-title small{font-size:9px;letter-spacing:.16em;color:#42e9a6;font-weight:900}.nc-title h1{font-size:27px;font-weight:850;margin:4px 0}.nc-title p{margin:0;color:#718a96}.nc-total{padding:8px 11px;border:1px solid #1a3544;border-radius:9px;background:#0a1923;color:#8da5ae;font-size:9px}.nc-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:11px;margin-bottom:13px}.nc-kpi,.nc-card{background:linear-gradient(145deg,#0b1c27,#08131b);border:1px solid #183241;border-radius:13px}.nc-kpi{padding:15px}.nc-kpi i{color:#42e9a6;margin-bottom:10px}.nc-kpi strong{display:block;font-size:21px}.nc-kpi label{display:block;margin:4px 0 0;color:#718b96;font-size:8px}.nc-layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(270px,.55fr);gap:13px}.nc-card{overflow:hidden}.nc-head{padding:14px 16px;border-bottom:1px solid #183241;display:flex;justify-content:space-between}.nc-head strong{font-size:11px}.nc-head span{font-size:8px;color:#607b87}.nc-feed{padding:5px 16px}.nc-item{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:12px;align-items:center;padding:15px 0;border-bottom:1px solid #142b38}.nc-item:last-child{border:0}.nc-icon{width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;background:rgba(66,233,166,.07);color:#42e9a6}.nc-icon.invoice{background:rgba(255,113,129,.07);color:#ff7181}.nc-icon.ticket{background:rgba(83,157,255,.08);color:#6ca9ff}.nc-info strong{display:block;font-size:10px}.nc-info p{margin:3px 0;color:#718b96;font-size:9px}.nc-info time{font-size:8px;color:#536e7a}.nc-badge{font-size:7px;font-weight:850;padding:5px 7px;border-radius:99px;background:#102630;color:#7f99a4;text-transform:uppercase}.nc-side{padding:15px}.nc-action{display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid #142b38}.nc-action:last-child{border:0}.nc-action span{font-size:9px;color:#708995}.nc-action strong{font-size:10px}.nc-empty{text-align:center;padding:65px 20px}.nc-empty i{font-size:30px;color:#42e9a6}.nc-empty h3{font-size:14px;margin:12px 0 5px}.nc-empty p{font-size:9px;color:#718b96}@media(max-width:900px){.nc-kpis{grid-template-columns:1fr 1fr}.nc-layout{grid-template-columns:1fr}}@media(max-width:560px){.nc-title{align-items:flex-start;flex-direction:column}.nc-item{grid-template-columns:38px 1fr}.nc-item>.nc-badge{grid-column:2;justify-self:start}.nc-kpi{padding:13px}}</style>
<div class="nc-kpis"><div class="nc-kpi"><i class="fa fa-bell"></i><strong>{{$items->count()}}</strong><label>Alle aktive hændelser</label></div><div class="nc-kpi"><i class="fa fa-file-text-o"></i><strong>{{$invoiceCount}}</strong><label>Forfaldne fakturaer</label></div><div class="nc-kpi"><i class="fa fa-ticket"></i><strong>{{$ticketCount}}</strong><label>Åbne support tickets</label></div><div class="nc-kpi"><i class="fa fa-cubes"></i><strong>{{$orderCount}}</strong><label>Ordrer i pipeline</label></div></div>
<div class="nc-layout"><section class="nc-card"><div class="nc-head"><strong>Action feed</strong><span>Nyeste først</span></div>@forelse($items as $i)<div class="nc-feed"><div class="nc-item"><div class="nc-icon {{$i->type}}"><i class="fa {{$i->type==='invoice'?'fa-file-text-o':($i->type==='ticket'?'fa-ticket':'fa-cubes')}}"></i></div><div class="nc-info"><strong>{{$i->title}}</strong><p>{{$i->text}}</p><time>{{\Carbon\Carbon::parse($i->at)->diffForHumans()}}</time></div><span class="nc-badge">{{$i->type==='invoice'?'Billing':($i->type==='ticket'?'Support':'Provisioning')}}</span></div></div>@empty<div class="nc-empty"><i class="fa fa-check-circle"></i><h3>Alt ser roligt ud</h3><p>Ingen aktuelle hændelser kræver administrativ opmærksomhed.</p></div>@endforelse</section><aside class="nc-card"><div class="nc-head"><strong>Operations pulse</strong><span>Prioritering</span></div><div class="nc-side"><div class="nc-action"><span>Betaling kræver handling</span><strong>{{$invoiceCount}}</strong></div><div class="nc-action"><span>Kunder venter på support</span><strong>{{$ticketCount}}</strong></div><div class="nc-action"><span>Provisioning i kø</span><strong>{{$orderCount}}</strong></div><div class="nc-action"><span>Samlet workload</span><strong>{{$items->count()}}</strong></div><p style="font-size:8px;color:#58727e;line-height:1.55;margin:14px 0 0">Feedet samler eksisterende Nodexa-data. Det sender ikke automatisk e-mail eller Discord-notifikationer endnu.</p></div></aside></div>
@endsection