@extends('storefront.layout')
@section('title', 'Planer')
@section('description', 'Se aktive Nodexa game hosting-pakker og priser.')
@section('content')
<style>
.nxp-hero{text-align:center;padding:82px 20px 48px}.nxp-hero .nx-eyebrow{margin-bottom:14px}.nxp-hero h1{font-size:clamp(34px,5vw,58px);margin:0 0 14px;line-height:1.02}.nxp-hero h1 em{font-style:normal;color:var(--nx-primary,#5790ff)}.nxp-hero p{max-width:650px;margin:auto;color:var(--nx-muted,#8995a8)}.nxp-category{margin:0 0 64px}.nxp-category-head{text-align:center;margin-bottom:26px}.nxp-category-head h2{font-size:30px;margin:5px 0 7px}.nxp-category-head p{color:var(--nx-muted,#8995a8);margin:0 auto;max-width:600px}.nxp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;max-width:920px;margin:0 auto}.nxp-card{position:relative;display:flex;flex-direction:column;min-height:365px;padding:24px;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:rgba(12,22,35,.86);box-shadow:0 12px 35px rgba(0,0,0,.12);transition:.2s ease}.nxp-card:hover{transform:translateY(-2px);border-color:rgba(87,144,255,.35)}.nxp-card.featured{border-color:var(--nx-primary,#5790ff);box-shadow:0 0 0 1px color-mix(in srgb,var(--nx-primary,#5790ff) 35%,transparent),0 18px 45px rgba(0,0,0,.2)}.nxp-badge{position:absolute;right:18px;top:-10px;background:var(--nx-primary,#5790ff);color:white;border-radius:20px;padding:5px 10px;font-size:9px;font-weight:800;letter-spacing:.08em}.nxp-top{display:flex;align-items:center;gap:12px}.nxp-icon{width:42px;height:42px;border-radius:10px;display:grid;place-items:center;background:rgba(87,144,255,.12);border:1px solid rgba(87,144,255,.15);font-weight:900;color:#8db2ff;font-size:15px}.nxp-name small{display:block;color:var(--nx-muted,#8995a8);font-size:10px;margin-top:2px}.nxp-name h3{margin:0;font-size:17px}.nxp-price{margin:24px 0 18px;padding-bottom:18px;border-bottom:1px solid rgba(255,255,255,.065)}.nxp-price strong{font-size:29px;letter-spacing:-.03em}.nxp-price span{font-size:11px;color:var(--nx-muted,#8995a8);margin-left:5px}.nxp-desc{font-size:12px;color:var(--nx-muted,#8995a8);margin:-8px 0 15px;line-height:1.5}.nxp-features{display:grid;gap:9px;margin-bottom:23px}.nxp-feature{font-size:12px;color:#aeb8c7}.nxp-feature:before{content:'✓';color:#54d69b;font-weight:800;margin-right:9px}.nxp-buy{margin-top:auto;width:100%;min-height:42px}.nxp-empty{text-align:center;padding:35px;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:rgba(12,22,35,.7)}@media(max-width:700px){.nxp-hero{padding-top:58px}.nxp-grid{grid-template-columns:1fr}.nxp-card{min-height:0}.nxp-category{margin-bottom:48px}}
</style>
<section class="nxp-hero"><div class="nx-shell"><span class="nx-eyebrow">GAME SERVER HOSTING</span><h1>Game Hosting <em>Plans</em></h1><p>Vælg dit spil og den pakke der passer til din server. Alle priser og ressourcer styres direkte fra Nodexa Admin.</p></div></section>
<section class="nx-section nx-section-tight"><div class="nx-shell">
@if($categories->isEmpty() && $products->isEmpty())<div class="nxp-empty"><h3>Ingen aktive pakker endnu</h3><p>Opret kategorier og pakker under Admin → Billing.</p></div>@else
@foreach($categories as $category) @php($categoryProducts=$products->where('category_id',$category->id)) @if($categoryProducts->isNotEmpty())
<section class="nxp-category"><header class="nxp-category-head"><span class="nx-kicker">GAME HOSTING</span><h2>{{$category->name}} Server Hosting</h2>@if($category->description)<p>{{$category->description}}</p>@endif</header><div class="nxp-grid">
@foreach($categoryProducts as $plan)
<article class="nxp-card {{$loop->iteration===2?'featured':''}}">@if($loop->iteration===2)<span class="nxp-badge">POPULÆR</span>@endif<div class="nxp-top"><div class="nxp-icon">{{strtoupper(substr($plan->name,0,2))}}</div><div class="nxp-name"><h3>{{$plan->name}}</h3><small>{{$category->name}} · Nodexa Hosting</small></div></div><div class="nxp-price"><strong>{{number_format((float)$plan->price,2,',','.')}} {{$plan->currency}}</strong><span>{{['monthly'=>'/ måned','quarterly'=>'/ 3 mdr.','semiannually'=>'/ 6 mdr.','annually'=>'/ år','one_time'=>'/ én gang'][$plan->billing_cycle]??''}}</span></div>@if($plan->description)<p class="nxp-desc">{{$plan->description}}</p>@endif<div class="nxp-features">@if($plan->memory_mb)<div class="nxp-feature">{{number_format($plan->memory_mb/1024,$plan->memory_mb%1024?1:0,',','.')}} GB RAM</div>@endif @if($plan->disk_mb)<div class="nxp-feature">{{number_format($plan->disk_mb/1024,$plan->disk_mb%1024?1:0,',','.')}} GB NVMe SSD</div>@endif @if($plan->cpu_percent)<div class="nxp-feature">{{$plan->cpu_percent}}% CPU</div>@endif @if($plan->databases_limit)<div class="nxp-feature">{{$plan->databases_limit}} databaser</div>@endif @if($plan->backups_limit)<div class="nxp-feature">{{$plan->backups_limit}} backups</div>@endif @if($plan->allocations_limit)<div class="nxp-feature">{{$plan->allocations_limit}} port{{(int)$plan->allocations_limit===1?'':'s'}}</div>@endif<div class="nxp-feature">Nodexa kontrolpanel</div></div><a class="nx-btn {{$loop->iteration===2?'nx-btn-primary':'nx-btn-ghost'}} nxp-buy" href="{{url('/client')}}">Kom i gang →</a></article>
@endforeach</div></section>@endif @endforeach
@php($uncategorized=$products->whereNull('category_id')) @if($uncategorized->isNotEmpty())<section class="nxp-category"><header class="nxp-category-head"><span class="nx-kicker">ANDRE PAKKER</span><h2>Øvrige serverpakker</h2></header><div class="nxp-grid">@foreach($uncategorized as $plan)<article class="nxp-card"><div class="nxp-top"><div class="nxp-icon">{{strtoupper(substr($plan->name,0,2))}}</div><div class="nxp-name"><h3>{{$plan->name}}</h3><small>Nodexa Hosting</small></div></div><div class="nxp-price"><strong>{{number_format((float)$plan->price,2,',','.')}} {{$plan->currency}}</strong></div><div class="nxp-features">@if($plan->memory_mb)<div class="nxp-feature">{{number_format($plan->memory_mb/1024,1,',','.')}} GB RAM</div>@endif @if($plan->disk_mb)<div class="nxp-feature">{{number_format($plan->disk_mb/1024,1,',','.')}} GB NVMe SSD</div>@endif @if($plan->cpu_percent)<div class="nxp-feature">{{$plan->cpu_percent}}% CPU</div>@endif<div class="nxp-feature">Nodexa kontrolpanel</div></div><a class="nx-btn nx-btn-ghost nxp-buy" href="{{url('/client')}}">Kom i gang →</a></article>@endforeach</div></section>@endif
@endif
</div></section>
@endsection