<?php
return [
 'levels'=>['icon'=>'fa-line-chart','title'=>'Levels & XP','description'=>'XP, levels og automatiske level-roller.','fields'=>['channel_id'=>'Level-up kanal','xp_min'=>'Minimum XP pr. besked','xp_max'=>'Maksimum XP pr. besked','cooldown_seconds'=>'XP cooldown (sek.)','level_up_message'=>'Level-up besked','role_rewards'=>'Level-roller (level:role_id, komma-separeret)'],'variables'=>['mention'=>'Medlem','level'=>'Nyt level','xp'=>'XP']],
 'giveaways'=>['icon'=>'fa-gift','title'=>'Giveaways','description'=>'Professionelle giveaways med slutdato, vindere og krav.','fields'=>['channel_id'=>'Standard giveaway kanal','manager_role_id'=>'Giveaway manager rolle','default_duration'=>'Standard varighed (min.)','default_winners'=>'Standard antal vindere','require_role_id'=>'Krævet rolle (valgfri)']],
 'suggestions'=>['icon'=>'fa-lightbulb-o','title'=>'Suggestions','description'=>'Forslag med embeds, afstemning og moderatorstatus.','fields'=>['channel_id'=>'Forslagskanal','review_channel_id'=>'Staff review kanal','manager_role_id'=>'Forslags-manager rolle','upvote_emoji'=>'Upvote emoji','downvote_emoji'=>'Downvote emoji']],
 'reaction_roles'=>['icon'=>'fa-hand-pointer-o','title'=>'Reaction Roles','description'=>'Selvbetjente roller via knapper eller reactions.','fields'=>['channel_id'=>'Rollekanal','message_id'=>'Besked-ID','role_map'=>'Emoji/knap → rolle (emoji:role_id)']],
 'starboard'=>['icon'=>'fa-star','title'=>'Starboard','description'=>'Fremhæv populære community-beskeder automatisk.','fields'=>['channel_id'=>'Starboard kanal','emoji'=>'Star emoji','threshold'=>'Minimum antal stars','ignore_channels'=>'Ignorerede kanal-ID’er']],
 'polls'=>['icon'=>'fa-bar-chart','title'=>'Polls','description'=>'Afstemninger med varighed og automatisk resultat.','fields'=>['channel_id'=>'Standard poll kanal','manager_role_id'=>'Poll manager rolle','default_duration'=>'Standard varighed (min.)']],
 'temp_voice'=>['icon'=>'fa-microphone','title'=>'Temp Voice','description'=>'Opret private midlertidige voice-kanaler automatisk.','fields'=>['lobby_channel_id'=>'Join-to-create voice kanal','category_id'=>'Temp voice kategori','default_limit'=>'Standard brugergrænse','name_format'=>'Kanalnavn format']],
 'sticky_messages'=>['icon'=>'fa-thumb-tack','title'=>'Sticky Messages','description'=>'Hold vigtig information nederst i udvalgte kanaler.','fields'=>['channel_id'=>'Kanal','message'=>'Sticky besked','interval_messages'=>'Genpost efter antal beskeder']],
 'invite_tracking'=>['icon'=>'fa-link','title'=>'Invite Tracking','description'=>'Se hvilken invitation nye medlemmer brugte.','fields'=>['channel_id'=>'Invite log kanal','reward_role_id'=>'Belønningsrolle','reward_invites'=>'Invites krævet til belønning']],
 'birthdays'=>['icon'=>'fa-birthday-cake','title'=>'Birthdays','description'=>'Fødselsdage, automatisk besked og valgfri rolle.','fields'=>['channel_id'=>'Fødselsdagskanal','role_id'=>'Fødselsdagsrolle','message'=>'Fødselsdagsbesked','timezone'=>'Tidszone'],'variables'=>['mention'=>'Medlem','age'=>'Alder']],
 'counting'=>['icon'=>'fa-sort-numeric-asc','title'=>'Counting','description'=>'Community counting med streak og anti-cheat.','fields'=>['channel_id'=>'Counting kanal','start_number'=>'Starttal','reset_on_error'=>'Reset ved fejl (1/0)','prevent_double'=>'Forhindr samme bruger to gange (1/0)']],
 'afk'=>['icon'=>'fa-clock-o','title'=>'AFK','description'=>'AFK-status med automatisk retur og mentionsvar.','fields'=>['default_message'=>'Standard AFK-besked','max_reason_length'=>'Maks længde på årsag']],
 'reminders'=>['icon'=>'fa-bell','title'=>'Reminders','description'=>'Personlige og staff-oprettede Discord reminders.','fields'=>['max_per_user'=>'Maks reminders pr. bruger','max_days'=>'Maks dage frem','allow_dm'=>'Tillad DM reminders (1/0)']]
];
