<?php

$advanced = [
    'general' => [
        'enabled_mode'=>'Driftstil (normal/silent/test)',
        'audit_log_channel_id'=>'Audit log kanal',
        'manager_role_id'=>'Manager rolle',
        'allowed_roles'=>'Tilladte rolle-ID’er (komma-separeret)',
        'ignored_roles'=>'Ignorerede rolle-ID’er',
        'allowed_channels'=>'Tilladte kanal-ID’er',
        'ignored_channels'=>'Ignorerede kanal-ID’er',
        'cooldown_seconds'=>'Global cooldown (sek.)',
        'rate_limit'=>'Rate limit pr. minut',
        'max_actions_per_hour'=>'Maks handlinger pr. time',
        'timezone'=>'Tidszone',
        'locale'=>'Sprog/locale',
        'success_message'=>'Succesbesked',
        'error_message'=>'Fejlbesked',
        'dm_notifications'=>'DM-notifikationer (1/0)',
        'ephemeral_replies'=>'Private command-svar (1/0)',
        'delete_command_messages'=>'Slet command-beskeder (1/0)',
        'audit_enabled'=>'Audit logging (1/0)',
    ],
    'Moderation' => [
        'action'=>'Standard handling (delete/warn/timeout/kick/ban)',
        'timeout_minutes'=>'Standard timeout (min.)',
        'warn_before_action'=>'Warn før handling (1/0)',
        'dm_user'=>'DM bruger ved handling (1/0)',
        'reason_required'=>'Kræv begrundelse (1/0)',
        'exempt_users'=>'Undtagede bruger-ID’er',
        'case_logging'=>'Opret moderation case (1/0)',
        'staff_bypass'=>'Staff bypass (1/0)',
    ],
    'Community' => [
        'staff_role_id'=>'Staff rolle',
        'log_channel_id'=>'Community log kanal',
        'anonymous_allowed'=>'Tillad anonym brug (1/0)',
        'approval_required'=>'Kræv staff-godkendelse (1/0)',
        'thread_enabled'=>'Opret thread automatisk (1/0)',
        'mention_role_id'=>'Rolle der nævnes',
    ],
    'Automation' => [
        'retry_attempts'=>'Retry-forsøg',
        'retry_delay_seconds'=>'Retry delay (sek.)',
        'schedule_enabled'=>'Tillad scheduling (1/0)',
        'failure_log_channel_id'=>'Fejl-log kanal',
        'concurrency_limit'=>'Maks samtidige jobs',
        'dry_run'=>'Test mode / dry-run (1/0)',
    ],
    'Engagement' => [
        'reward_role_id'=>'Belønningsrolle',
        'announce_channel_id'=>'Announcement kanal',
        'leaderboard_enabled'=>'Leaderboard (1/0)',
        'reset_schedule'=>'Reset schedule',
        'minimum_account_age_hours'=>'Minimum kontoalder (timer)',
        'minimum_membership_hours'=>'Minimum medlemstid (timer)',
    ],
    'Voice' => [
        'voice_category_id'=>'Voice kategori',
        'controller_role_id'=>'Voice controller rolle',
        'default_user_limit'=>'Standard brugerlimit',
        'inactive_timeout_minutes'=>'Inaktiv timeout (min.)',
        'owner_controls'=>'Owner controls (1/0)',
        'auto_cleanup'=>'Automatisk cleanup (1/0)',
    ],
    'Integrations' => [
        'webhook_url'=>'Webhook URL',
        'mention_role_id'=>'Mention rolle',
        'poll_interval_seconds'=>'Polling interval (sek.)',
        'retry_attempts'=>'Retry-forsøg',
        'deduplicate'=>'Undgå dubletter (1/0)',
        'failure_log_channel_id'=>'Fejl-log kanal',
    ],
    'Utilities' => [
        'staff_role_id'=>'Staff rolle',
        'log_channel_id'=>'Log kanal',
        'retention_days'=>'Data retention (dage)',
        'max_items_per_user'=>'Maks elementer pr. bruger',
        'export_enabled'=>'Tillad eksport (1/0)',
        'privacy_mode'=>'Privacy mode (1/0)',
    ],
];

$module = static function(string $category, string $icon, string $title, string $description, array $fields = [], array $variables = []) use ($advanced): array {
    $fields = array_merge($fields, $advanced['general'], $advanced[$category] ?? []);
    return array_filter(['category'=>$category,'icon'=>$icon,'title'=>$title,'description'=>$description,'fields'=>$fields,'variables'=>$variables], static fn($value)=>$value!==[]);
};

return [
 'levels'=>$module('Engagement','fa-line-chart','Levels & XP','Avanceret XP-system med level-roller, anti-farm, rewards, leaderboard og automatisering.',['channel_id'=>'Level-up kanal','xp_min'=>'Minimum XP pr. besked','xp_max'=>'Maksimum XP pr. besked','cooldown_seconds'=>'XP cooldown (sek.)','level_up_message'=>'Level-up besked','role_rewards'=>'Level-roller (level:role_id)','xp_multiplier'=>'Global XP multiplier','voice_xp_enabled'=>'Voice XP integration (1/0)','ignore_bots'=>'Ignorer bots (1/0)'],['mention'=>'Medlem','level'=>'Nyt level','xp'=>'XP']),
 'giveaways'=>$module('Engagement','fa-gift','Giveaways','Giveaways med krav, flere vindere, reroll, bonus entries og anti-alt controls.',['channel_id'=>'Giveaway kanal','default_duration'=>'Standard varighed (min.)','default_winners'=>'Standard vindere','require_role_id'=>'Krævet rolle','bonus_roles'=>'Bonus roller (role_id:entries)','minimum_messages'=>'Minimum beskeder','minimum_level'=>'Minimum level','reroll_enabled'=>'Tillad reroll (1/0)']),
 'suggestions'=>$module('Community','fa-lightbulb-o','Suggestions','Komplet suggestion workflow med voting, review, status, threads og staff-svar.',['channel_id'=>'Forslagskanal','review_channel_id'=>'Staff review kanal','upvote_emoji'=>'Upvote emoji','downvote_emoji'=>'Downvote emoji','minimum_votes'=>'Minimum votes','auto_thread'=>'Auto thread (1/0)','allow_comments'=>'Tillad kommentarer (1/0)']),
 'reaction_roles'=>$module('Community','fa-hand-pointer-o','Reaction Roles','Avancerede self-roles med buttons, reactions, exclusivity og rollegrænser.',['channel_id'=>'Rollekanal','message_id'=>'Besked-ID','role_map'=>'Emoji/knap → rolle','max_roles'=>'Maks roller pr. medlem','exclusive_groups'=>'Eksklusive rollegrupper','remove_on_unreact'=>'Fjern ved unreact (1/0)']),
 'starboard'=>$module('Engagement','fa-star','Starboard','Starboard med thresholds, self-star protection, ignored content og kanalregler.',['channel_id'=>'Starboard kanal','emoji'=>'Star emoji','threshold'=>'Minimum stars','ignore_channels'=>'Ignorerede kanaler','self_star'=>'Tillad self-star (1/0)','max_age_hours'=>'Maks beskedalder (timer)','include_attachments'=>'Vis attachments (1/0)']),
 'polls'=>$module('Engagement','fa-bar-chart','Polls','Avancerede polls med varighed, multiple choice, anonymitet og automatisk resultat.',['channel_id'=>'Standard poll kanal','default_duration'=>'Standard varighed (min.)','max_options'=>'Maks valgmuligheder','multiple_choice'=>'Multiple choice (1/0)','anonymous_votes'=>'Anonyme votes (1/0)','auto_results'=>'Auto resultat (1/0)']),
 'temp_voice'=>$module('Voice','fa-microphone','Temp Voice','Dynamiske voice rooms med ejerskab, permissions, limits og auto-cleanup.',['lobby_channel_id'=>'Join-to-create kanal','category_id'=>'Temp voice kategori','default_limit'=>'Standard brugergrænse','name_format'=>'Kanalnavn format','allow_rename'=>'Tillad rename (1/0)','allow_lock'=>'Tillad lock (1/0)','allow_kick'=>'Tillad kick (1/0)']),
 'sticky_messages'=>$module('Automation','fa-thumb-tack','Sticky Messages','Sticky embeds/beskeder med intelligent repost og kanalbaserede regler.',['channel_id'=>'Kanal','message'=>'Sticky besked','interval_messages'=>'Genpost efter beskeder','minimum_seconds'=>'Minimum tid mellem reposts','embed_enabled'=>'Brug embed (1/0)','delete_previous'=>'Slet forrige sticky (1/0)']),
 'invite_tracking'=>$module('Community','fa-link','Invite Tracking','Invite analytics, fake-invite detection, rewards og inviter leaderboards.',['channel_id'=>'Invite log kanal','reward_role_id'=>'Belønningsrolle','reward_invites'=>'Invites til belønning','fake_account_hours'=>'Fake account grænse (timer)','leave_penalty'=>'Træk invite ved leave (1/0)','leaderboard_enabled'=>'Invite leaderboard (1/0)']),
 'birthdays'=>$module('Community','fa-birthday-cake','Birthdays','Fødselsdage med timezone, rolle, announcement og privacy controls.',['channel_id'=>'Fødselsdagskanal','role_id'=>'Fødselsdagsrolle','message'=>'Fødselsdagsbesked','timezone'=>'Tidszone','allow_age'=>'Tillad alder (1/0)','reminder_hours'=>'Reminder før fødselsdag (timer)'],['mention'=>'Medlem','age'=>'Alder']),
 'counting'=>$module('Engagement','fa-sort-numeric-asc','Counting','Counting med streaks, anti-cheat, milestones, records og recovery.',['channel_id'=>'Counting kanal','start_number'=>'Starttal','reset_on_error'=>'Reset ved fejl (1/0)','prevent_double'=>'Forhindr dobbelt tur (1/0)','milestones'=>'Milestones','save_highscore'=>'Gem highscore (1/0)','delete_invalid'=>'Slet ugyldige beskeder (1/0)']),
 'afk'=>$module('Utilities','fa-clock-o','AFK','AFK-system med reasons, mentions, auto-return og nickname support.',['default_message'=>'Standard AFK-besked','max_reason_length'=>'Maks årsagslængde','nickname_prefix'=>'AFK nickname prefix','mention_notice'=>'Mention notice (1/0)','auto_remove'=>'Auto-fjern ved besked (1/0)']),
 'reminders'=>$module('Utilities','fa-bell','Reminders','Personlige/staff reminders med recurring schedules, DM og kanal-levering.',['max_per_user'=>'Maks reminders pr. bruger','max_days'=>'Maks dage frem','allow_dm'=>'Tillad DM (1/0)','allow_recurring'=>'Tillad gentagelser (1/0)','minimum_delay_seconds'=>'Minimum delay (sek.)']),
 'music'=>$module('Voice','fa-music','Music','Musik med queue, DJ controls, autoplay, filters, playlists og vote skip.',['dj_role_id'=>'DJ rolle','default_volume'=>'Standard volume','max_queue'=>'Maks queue','allow_playlists'=>'Tillad playlists (1/0)','autoplay'=>'Autoplay (1/0)','vote_skip_percent'=>'Vote skip (%)','max_track_minutes'=>'Maks sanglængde']),
 'temp_bans'=>$module('Moderation','fa-hourglass-half','Temporary Bans','Midlertidige bans med scheduler, unban, cases og audit trail.',['log_channel_id'=>'Log kanal','default_duration'=>'Standard varighed','max_duration'=>'Maks varighed','dm_user'=>'Send DM (1/0)','appeal_enabled'=>'Tillad appeal (1/0)','unban_message'=>'Unban besked']),
 'voice_activity'=>$module('Voice','fa-volume-up','Voice Activity','Detaljeret voice tracking med sessioner, leaderboards og anti-idle.',['excluded_channels'=>'Ignorerede voice-kanaler','minimum_minutes'=>'Minimum minutter','stats_channel_id'=>'Statistikkanal','ignore_deafened'=>'Ignorer deafened (1/0)','ignore_muted'=>'Ignorer muted (1/0)','leaderboard_enabled'=>'Leaderboard (1/0)']),
 'economy'=>$module('Engagement','fa-money','Economy','Community economy med daily, transfers, cooldowns, tax og balance controls.',['currency_name'=>'Valutanavn','currency_symbol'=>'Valutasymbol','daily_amount'=>'Daily reward','starting_balance'=>'Startsaldo','transfer_enabled'=>'Transfers (1/0)','transfer_tax_percent'=>'Transfer tax (%)','max_balance'=>'Maks saldo','daily_streak_bonus'=>'Daily streak bonus']),
 'shop'=>$module('Engagement','fa-shopping-cart','Shop','Shop med rollevarer, stock, cooldown, purchase logs og economy integration.',['shop_channel_id'=>'Shop kanal','items'=>'Varer (navn:pris:role_id)','purchase_log_channel_id'=>'Købslog kanal','max_purchases_daily'=>'Maks køb pr. dag','refund_enabled'=>'Tillad refund (1/0)','stock_enabled'=>'Aktivér lager (1/0)']),
 'custom_commands'=>$module('Automation','fa-code','Custom Commands','Custom commands med aliases, permissions, cooldowns, embeds og variables.',['commands'=>'Commands (navn:svar)','cooldown_seconds'=>'Standard cooldown','aliases_enabled'=>'Aliases (1/0)','variables_enabled'=>'Variables (1/0)','embed_enabled'=>'Embed output (1/0)','max_commands'=>'Maks commands']),
 'applications'=>$module('Community','fa-id-card','Applications','Ansøgninger med formularer, reviewer workflow, cooldown og automatisk rolle.',['channel_id'=>'Ansøgningskanal','review_channel_id'=>'Review kanal','reviewer_role_id'=>'Reviewer rolle','accepted_role_id'=>'Godkendt rolle','questions'=>'Ansøgningsspørgsmål','cooldown_hours'=>'Ansøgnings-cooldown','dm_result'=>'DM resultat (1/0)']),
 'forms'=>$module('Community','fa-list-alt','Forms','Dynamiske formularer med felttyper, validation, review og exports.',['channel_id'=>'Form kanal','response_channel_id'=>'Svar-kanal','questions'=>'Spørgsmål','max_responses_per_user'=>'Maks svar pr. bruger','allow_edits'=>'Tillad redigering (1/0)','export_format'=>'Eksportformat']),
 'auto_threads'=>$module('Automation','fa-comments-o','Auto Threads','Automatiske threads med templates, tags, archive og kanalregler.',['channel_ids'=>'Kanal-ID’er','thread_name'=>'Thread navn format','auto_archive_minutes'=>'Auto-archive minutter','starter_message'=>'Starter besked','ignore_bots'=>'Ignorer bots (1/0)','slowmode_seconds'=>'Thread slowmode']),
 'voice_xp'=>$module('Voice','fa-signal','Voice XP','Voice XP med anti-idle, multipliers, channel rules og level integration.',['xp_per_minute'=>'XP pr. minut','cooldown_seconds'=>'Cooldown','excluded_channels'=>'Ignorerede kanaler','muted_earns_xp'=>'Muted giver XP (1/0)','deafened_earns_xp'=>'Deafened giver XP (1/0)','minimum_members'=>'Minimum medlemmer']),
 'member_statistics'=>$module('Utilities','fa-pie-chart','Member Statistics','Live counters og statistikkanaler med templates og refresh controls.',['category_id'=>'Statistik kategori','members_enabled'=>'Medlemmer (1/0)','online_enabled'=>'Online (1/0)','voice_enabled'=>'Voice (1/0)','bots_enabled'=>'Bots (1/0)','refresh_minutes'=>'Refresh minutter','name_templates'=>'Kanalnavn templates']),
 'server_backup'=>$module('Utilities','fa-database','Server Backup / Restore','Versionerede Discord structure-backups med retention, preview og restore controls.',['retention_count'=>'Antal backups','include_permissions'=>'Permissions (1/0)','include_channels'=>'Kanaler (1/0)','include_roles'=>'Roller (1/0)','automatic_backup_hours'=>'Auto backup interval','require_restore_confirmation'=>'Kræv restore confirmation (1/0)']),
 'social_notifications'=>$module('Integrations','fa-rss','Twitch / YouTube Notifications','Multi-source notifications med deduplication, templates og mention rules.',['channel_id'=>'Notifikationskanal','twitch_channels'=>'Twitch kanaler','youtube_channels'=>'YouTube kanaler','mention_role_id'=>'Mention rolle','live_message'=>'Live template','video_message'=>'Video template','offline_updates'=>'Offline updates (1/0)']),
 'scheduled_messages'=>$module('Automation','fa-calendar','Scheduled Messages','Scheduler med recurring jobs, timezone, embeds og delivery logs.',['channel_id'=>'Standard kanal','timezone'=>'Tidszone','schedule'=>'Standard schedule','message'=>'Besked template','embed_enabled'=>'Embed (1/0)','max_schedules'=>'Maks schedules']),
 'embed_builder'=>$module('Utilities','fa-object-group','Embed Builder','Embed templates med author, fields, images, buttons og reusable presets.',['channel_id'=>'Standard kanal','default_footer'=>'Standard footer','default_color'=>'Standard farve','allow_buttons'=>'Tillad buttons (1/0)','allow_images'=>'Tillad billeder (1/0)','max_fields'=>'Maks embed fields']),
 'role_menus'=>$module('Community','fa-list','Role Menus','Buttons/select menus med prerequisites, exclusivity og max-role policies.',['channel_id'=>'Rollekanal','message_id'=>'Besked-ID','roles'=>'Roller','max_roles'=>'Maks valgte roller','required_roles'=>'Krævede roller','exclusive_roles'=>'Eksklusive roller','remove_roles'=>'Roller der fjernes']),
 'join_to_create'=>$module('Voice','fa-plus-circle','Join-to-Create Voice','Private voice rooms med owner panel, permissions, transfer og cleanup.',['lobby_channel_id'=>'Join kanal','category_id'=>'Voice kategori','default_limit'=>'Standard limit','name_format'=>'Navneformat','allow_transfer'=>'Tillad owner transfer (1/0)','allow_whitelist'=>'Whitelist controls (1/0)','allow_blocklist'=>'Blocklist controls (1/0)']),
 'ai_assistant'=>$module('Automation','fa-magic','AI Assistant','AI-assistent med kanalregler, context limits, staff approval og safety controls.',['channel_ids'=>'Tilladte kanaler','staff_role_id'=>'Staff rolle','system_prompt'=>'Bot instruktion','max_context_messages'=>'Maks kontekst','staff_approval'=>'Kræv staff approval (1/0)','max_response_length'=>'Maks svarlængde','daily_user_limit'=>'Daglig brugergrænse','log_prompts'=>'Log prompts (1/0)']),
 'anti_nuke'=>$module('Moderation','fa-bomb','Anti-Nuke','Anti-nuke med thresholds, trusted actors, lockdown og recovery logging.',['log_channel_id'=>'Security log kanal','trusted_roles'=>'Betroede roller','trusted_users'=>'Betroede brugere','channel_delete_limit'=>'Kanal-sletningsgrænse','role_delete_limit'=>'Rolle-sletningsgrænse','ban_limit'=>'Ban-grænse','kick_limit'=>'Kick-grænse','window_seconds'=>'Detection window','auto_lockdown'=>'Auto lockdown (1/0)']),
 'advanced_antispam'=>$module('Moderation','fa-filter','Advanced Anti-Spam','Multi-signal anti-spam med flood, duplicates, mentions, emoji og escalation.',['log_channel_id'=>'AutoMod log kanal','message_limit'=>'Beskedgrænse','interval_seconds'=>'Interval','duplicate_limit'=>'Duplicate grænse','mention_limit'=>'Mention grænse','emoji_limit'=>'Emoji grænse','caps_percent'=>'CAPS procent','escalation_enabled'=>'Escalation (1/0)']),
 'link_filter'=>$module('Moderation','fa-chain-broken','Link / Invite Filter','Domain allow/block lists, invite detection, redirects og exemptions.',['log_channel_id'=>'Log kanal','allowed_domains'=>'Tilladte domæner','blocked_domains'=>'Blokerede domæner','block_invites'=>'Bloker invites (1/0)','block_links'=>'Bloker links (1/0)','scan_redirects'=>'Scan redirects (1/0)','exempt_roles'=>'Undtagede roller']),
 'word_filter'=>$module('Moderation','fa-ban','Word Filter','Ord-, regex- og pattern-filter med exemptions og escalation.',['log_channel_id'=>'Log kanal','blocked_words'=>'Blokerede ord','blocked_patterns'=>'Blokerede patterns','action'=>'Handling','exempt_roles'=>'Undtagede roller','exempt_channels'=>'Undtagede kanaler','match_variations'=>'Match variationer (1/0)']),
 'captcha'=>$module('Moderation','fa-user-secret','Captcha / Anti-Bot','Join-gate med account-age, quarantine, timeout og anti-alt controls.',['verification_channel_id'=>'Verification kanal','verified_role_id'=>'Verificeret rolle','quarantine_role_id'=>'Karantæne rolle','timeout_minutes'=>'Verification timeout','min_account_age_hours'=>'Minimum kontoalder','max_attempts'=>'Maks forsøg','kick_on_failure'=>'Kick ved fejl (1/0)']),
 'modmail'=>$module('Community','fa-envelope','Mod Mail','DM-baseret support med threads, claims, transcripts, tags og close reasons.',['category_id'=>'ModMail kategori','staff_role_id'=>'Staff rolle','log_channel_id'=>'Log kanal','welcome_message'=>'Velkomstbesked','close_message'=>'Lukkebesked','claim_enabled'=>'Claim system (1/0)','transcript_enabled'=>'Gem transcript (1/0)','anonymous_staff'=>'Skjul staff-navn (1/0)']),
 'server_suggestions'=>$module('Community','fa-commenting','Server Suggestions','Roadmap-lignende suggestion board med tags, statuses, voting og staff notes.',['channel_id'=>'Suggestion kanal','review_channel_id'=>'Review kanal','accepted_channel_id'=>'Godkendte forslag','denied_channel_id'=>'Afviste forslag','tags'=>'Suggestion tags','minimum_votes'=>'Minimum votes','auto_archive_days'=>'Auto archive dage']),
 'event_manager'=>$module('Engagement','fa-calendar-check-o','Event Manager','Events med RSVP, capacity, waitlist, reminders, roles og attendance tracking.',['channel_id'=>'Event kanal','reminder_minutes'=>'Reminder minutter','participant_role_id'=>'Deltagerrolle','timezone'=>'Tidszone','max_participants'=>'Maks deltagere','waitlist_enabled'=>'Venteliste (1/0)','attendance_tracking'=>'Track attendance (1/0)','dm_reminders'=>'DM reminders (1/0)']),
];
