<!doctype html>
<html lang="da">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Nodexa · Server Startup</title>
<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui;background:#080913;color:#f7f7fb}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% 0,#171334 0,transparent 36%),#080913}.shell{min-height:100vh;display:grid;grid-template-columns:240px 1fr}aside{background:#0d0e19;border-right:1px solid #24263a;padding:25px 18px}.brand{font-size:24px;font-weight:900;letter-spacing:1px;margin-bottom:35px}.brand span{color:#8666ff}nav a{display:block;color:#aeb3c6;text-decoration:none;padding:12px 14px;border-radius:9px;margin-bottom:7px}nav a.active{background:#201a3a;color:#fff;border:1px solid #40346d}main{padding:34px;max-width:1200px;width:100%}.crumb{color:#7f8497;font-size:13px}.head{display:flex;justify-content:space-between;align-items:center;margin:10px 0 24px}.head h1{margin:0}.badge{border:1px solid #2d684d;background:#102a22;color:#66dfa8;padding:7px 11px;border-radius:999px}.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(250px,1fr);gap:18px}.card{background:#11131f;border:1px solid #272b40;border-radius:14px;padding:20px;box-shadow:0 18px 50px #0004}.card h2{margin-top:0}.warning{background:#241b13;border-color:#5f4221;color:#f1c991}.field{display:grid;gap:7px;margin:16px 0}.field span{font-size:13px;color:#bdc2d1}.field input,.field textarea{width:100%;background:#090b14;border:1px solid #30354b;color:#fff;border-radius:9px;padding:12px;font:inherit}.field textarea{min-height:145px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.row{display:flex;justify-content:flex-end;gap:10px;margin-top:20px}button{border:1px solid #373c50;background:#171a27;color:#fff;border-radius:9px;padding:11px 15px;cursor:pointer}.primary{background:#7457ff;border-color:#8c75ff}.env{display:grid;gap:10px}.envrow{display:grid;grid-template-columns:1fr 1.3fr auto;gap:8px}.muted{color:#8d93a7;font-size:13px}.error{background:#35181d;border:1px solid #6d2834;color:#ffb7c2;padding:11px;border-radius:9px;display:none}.success{background:#112b21;border:1px solid #276246;color:#8de4b7;padding:11px;border-radius:9px;display:none}@media(max-width:850px){.shell{grid-template-columns:1fr}aside{display:none}.grid{grid-template-columns:1fr}main{padding:20px}}
</style>
</head><body><div class="shell"><aside><div class="brand">NOD<span>EXA</span></div><nav><a href="/">Servers</a><a href="/admin/database-hosts">Database Hosts</a><a class="active">Server Startup</a></nav></aside><main><div class="crumb">Admin → Servers → <span id="crumbServer">Server</span> → Startup</div><div class="head"><div><h1>Startup</h1><div class="muted">Kun administratorer kan ændre disse værdier.</div></div><span class="badge">ADMIN ONLY</span></div><div id="error" class="error"></div><div id="success" class="success"></div><div class="grid"><section class="card"><h2 id="serverName">Indlæser server…</h2><label class="field"><span>Startup Command</span><textarea id="startup" spellcheck="false"></textarea></label><label class="field"><span>Docker Image</span><input id="image"></label><h3>Environment variabler</h3><p class="muted">Disse værdier bruges ved serverens opstart.</p><div id="env" class="env"></div><button id="addEnv">+ Tilføj variabel</button><div class="row"><button id="reload">Fortryd ændringer</button><button id="save" class="primary">Gem startup</button></div></section><aside class="card warning" style="display:block;background:#241b13;border:1px solid #5f4221;padding:20px"><h2>Beskyttet område</h2><p>Startup Command og Docker Image kan ikke ændres fra kundens serverpanel eller af inviterede serverbrugere.</p><p>Ændringer her påvirker næste serverstart og kan forhindre serveren i at starte, hvis kommandoen er ugyldig.</p></aside></div></main></div>
<script>
const token=localStorage.getItem('nodexa_panel_token');if(!token)location.href='/';
const headers={'Authorization':'Bearer '+token,'Content-Type':'application/json','Accept':'application/json'};
const parts=location.pathname.split('/').filter(Boolean),serverId=parts[2];let state=null;
const err=document.getElementById('error'),ok=document.getElementById('success');
function message(el,text){el.textContent=text;el.style.display='block';setTimeout(()=>el.style.display='none',4500)}
function renderEnv(obj){const root=document.getElementById('env');root.innerHTML='';Object.entries(obj||{}).forEach(([k,v])=>addRow(k,String(v)))}
function addRow(k='',v=''){const row=document.createElement('div');row.className='envrow';row.innerHTML='<input class="ek" placeholder="VARIABLE"><input class="ev" placeholder="Værdi"><button type="button">Fjern</button>';row.querySelector('.ek').value=k;row.querySelector('.ev').value=v;row.querySelector('button').onclick=()=>row.remove();document.getElementById('env').appendChild(row)}
async function load(){const me=await fetch('/api/me',{headers}).then(r=>r.ok?r.json():Promise.reject(r));if(!me.is_admin){location.href='/';return}const r=await fetch('/api/admin/servers/'+serverId+'/startup',{headers});if(!r.ok){message(err,'Kunne ikke hente serverens startup.');return}state=await r.json();document.getElementById('serverName').textContent=state.name+' · '+(state.identifier||'');document.getElementById('crumbServer').textContent=state.identifier||state.name;document.getElementById('startup').value=state.startup||'';document.getElementById('image').value=state.docker_image||'';renderEnv(state.environment)}
document.getElementById('addEnv').onclick=()=>addRow();document.getElementById('reload').onclick=load;
document.getElementById('save').onclick=async()=>{const environment={};document.querySelectorAll('.envrow').forEach(row=>{const k=row.querySelector('.ek').value.trim();if(k)environment[k]=row.querySelector('.ev').value});const body={startup:document.getElementById('startup').value,docker_image:document.getElementById('image').value,environment};const r=await fetch('/api/admin/servers/'+serverId+'/startup',{method:'PUT',headers,body:JSON.stringify(body)});if(!r.ok){const j=await r.json().catch(()=>({}));message(err,j.message||'Kunne ikke gemme startup.');return}message(ok,'Startup-indstillinger gemt.');load()};load();
</script></body></html>
