import React, {useEffect, useState} from 'react';
import axios from 'axios';

type Server={id:string;uuid:string;name:string;status:string;memory_mb:number;disk_mb:number;cpu_limit:number};
type Stats={state:string;cpu_percent:number;memory_bytes:number;memory_limit:number;network_rx_bytes:number;network_tx_bytes:number};
const fmt=(n:number)=>n>1024**3?(n/1024**3).toFixed(2)+' GB':(n/1024**2).toFixed(1)+' MB';

export default function App(){
 const [servers,setServers]=useState<Server[]>([]),[selected,setSelected]=useState<Server|null>(null),[stats,setStats]=useState<Stats|null>(null),[logs,setLogs]=useState(''),[cmd,setCmd]=useState('');
 useEffect(()=>{axios.get('/api/servers').then(r=>{const s=r.data.data??r.data;setServers(s);if(s[0])setSelected(s[0]);});},[]);
 useEffect(()=>{if(!selected)return; const tick=()=>{axios.get(`/api/servers/${selected.id}/stats`).then(r=>setStats(r.data)).catch(()=>{});axios.get(`/api/servers/${selected.id}/logs?tail=150`).then(r=>setLogs(r.data)).catch(()=>{});};tick();const i=setInterval(tick,3000);return()=>clearInterval(i)},[selected]);
 const power=(signal:string)=>selected&&axios.post(`/api/servers/${selected.id}/power`,{signal}).then(()=>setTimeout(()=>setSelected({...selected,status:signal==='start'?'running':signal==='stop'?'offline':selected.status}),500));
 const send=()=>{if(!selected||!cmd.trim())return;axios.post(`/api/servers/${selected.id}/command`,{command:cmd}).then(()=>setCmd(''));};
 return <div className="shell"><aside><div className="brand">NOD<span>EXA</span></div><nav><b>Servers</b><span>Dashboard</span><span>Nodes</span><span>Backups</span><span>Administration</span></nav><div className="version">v0.4.2</div></aside><main><header><div><small>NODEXA CONTROL PANEL</small><h1>{selected?.name??'Nodexa'}</h1></div><div className={'status '+(stats?.state==='running'?'online':'offline')}>{stats?.state??selected?.status??'offline'}</div></header><section className="server-grid"><div className="server-list card"><h3>Your servers</h3>{servers.map(s=><button key={s.id} className={selected?.id===s.id?'active':''} onClick={()=>setSelected(s)}><strong>{s.name}</strong><small>{s.memory_mb} MB · {s.cpu_limit}% CPU</small></button>)}</div><div className="content"><div className="metrics"><div className="metric"><small>CPU</small><strong>{stats?stats.cpu_percent.toFixed(1):'0'}%</strong></div><div className="metric"><small>MEMORY</small><strong>{stats?fmt(stats.memory_bytes):'0 MB'}</strong></div><div className="metric"><small>NETWORK RX</small><strong>{stats?fmt(stats.network_rx_bytes):'0 MB'}</strong></div><div className="metric"><small>NETWORK TX</small><strong>{stats?fmt(stats.network_tx_bytes):'0 MB'}</strong></div></div><div className="power"><button onClick={()=>power('start')}>Start</button><button onClick={()=>power('restart')}>Restart</button><button onClick={()=>power('stop')}>Stop</button><button className="danger" onClick={()=>power('kill')}>Kill</button></div><div className="console card"><div className="console-title">Console</div><pre>{logs||'No console output yet.'}</pre><div className="command"><span>&gt;</span><input value={cmd} onChange={e=>setCmd(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Type a server command..."/><button onClick={send}>Send</button></div></div></div></section></main></div>
}
