@extends('layouts.admin')
@section('title','Discord Bot Modules')
@section('content-header')<h1>Discord Bot <small>Module Manager</small></h1>@endsection
@section('content')
<style>.mod-wrap{max-width:1180px;margin:auto}.mod-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.mod-head h2{margin:0;color:#fff}.mod-head p{margin:4px 0 0;color:#8298a2}.mod-back{border:1px solid rgba(125,211,252,.15);padding:9px 13px;border-radius:9px;color:#dce8ec;background:#0a1820}.mod-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.mod-card{background:linear-gradient(145deg,#0c202a,#091820);border:1px solid rgba(125,211,252,.12);border-radius:14px;padding:17px;display:flex;gap:14px;align-items:center;cursor:pointer;transition:.18s}.mod-card:hover{border-color:rgba(88,101,242,.55);transform:translateY(-1px);background:linear-gradient(145deg,#102632,#091820)}.mod-icon{width:42px;height:42px;flex:0 0 42px;border-radius:11px;background:rgba(88,101,242,.13);color:#8490ff;display:flex;align-items:center;justify-content:center;font-size:17px}.mod-main{flex:1;min-width:0}.mod-title{display:flex;align-items:center;justify-content:space-between;gap:10px}.mod-title strong{color:#fff;font-size:14px}.mod-main p{color:#849ba5;font-size:11px;margin:6px 0 0}.mod-right{display:flex;align-items:center;gap:12px}.mod-state{font-size:10px;font-weight:700;padding:5px 8px;border-radius:99px}.on{color:#57d68d;background:rgba(35,165,90,.12)}.off{color:#9aabb2;background:rgba(148,163,184,.08)}.mod-arrow{color:#637d88;font-size:14px}.mod-note{margin-top:15px;color:#718993;font-size:11px;text-align:right}@media(max-width:760px){.mod-grid{grid-template-columns:1fr}.mod-card{padding:14px}.mod-head{align-items:flex-start}.mod-state{display:none}}</style>
<div class="mod-wrap"><div class="mod-head"><div><h2>Modules</h2><p>Tryk på et modul for at ændre dets indstillinger.</p></div><a class="mod-back" href="{{ route('admin.discord-bot') }}"><i class="fa fa-arrow-left"></i> Bot</a></div><div class="mod-grid">
@foreach($definitions as $key=>$item) @php $cfg=$modules[$key]??[]; @endphp
<div class="mod-card" role="link" tabindex="0" onclick="window.location='{{ route('admin.discord-bot.modules.module',['module'=>$key]) }}'" onkeydown="if(event.key==='Enter')window.location='{{ route('admin.discord-bot.modules.module',['module'=>$key]) }}'"><div class="mod-icon"><i class="fa {{ $item['icon'] }}"></i></div><div class="mod-main"><div class="mod-title"><strong>{{ $item['title'] }}</strong></div><p>{{ $item['description'] }}</p></div><div class="mod-right"><span class="mod-state {{ !empty($cfg['enabled'])?'on':'off' }}">{{ !empty($cfg['enabled'])?'Aktiv':'Deaktiveret' }}</span><i class="fa fa-chevron-right mod-arrow"></i></div></div>
@endforeach
</div><div class="mod-note"><i class="fa fa-info-circle"></i> Aktivering og alle indstillinger administreres nu inde på hvert modul.</div></div>
@endsection
