@extends('layouts.admin')
@section('title', $module['title'].' - Discord Bot')
@section('content-header')<h1>Discord Bot <small>{{ $module['title'] }}</small></h1>@endsection
@section('content')
<style>.ms-wrap{max-width:900px;margin:auto}.ms-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.ms-title{display:flex;gap:13px;align-items:center}.ms-icon{width:48px;height:48px;border-radius:13px;background:rgba(88,101,242,.14);color:#8993ff;display:flex;align-items:center;justify-content:center;font-size:20px}.ms-title h2{color:#fff;margin:0;font-size:21px}.ms-title p{color:#8298a2;margin:4px 0 0;font-size:12px}.ms-back{padding:9px 13px;border-radius:9px;background:#0a1820;border:1px solid rgba(125,211,252,.14);color:#dbe7eb}.ms-card{background:linear-gradient(145deg,#0c202a,#091820);border:1px solid rgba(125,211,252,.12);border-radius:14px;overflow:hidden}.ms-section{padding:19px;border-bottom:1px solid rgba(125,211,252,.09)}.ms-section:last-child{border:0}.ms-toggle{display:flex;align-items:center;justify-content:space-between}.ms-toggle strong{color:#edf7fa;font-size:13px}.ms-toggle small{display:block;color:#8097a1;margin-top:4px}.switch{position:relative;width:46px;height:25px}.switch input{opacity:0}.slider{position:absolute;inset:0;background:#263942;border-radius:99px}.slider:before{content:'';position:absolute;width:19px;height:19px;left:3px;top:3px;background:#fff;border-radius:50%;transition:.2s}.switch input:checked+.slider{background:#5865f2}.switch input:checked+.slider:before{transform:translateX(21px)}.ms-field{margin-bottom:16px}.ms-field:last-child{margin:0}.ms-field label{display:block;margin-bottom:7px;color:#dce9ed;font-size:12px}.ms-field input,.ms-field textarea,.ms-field select{width:100%;background:#07151c;border:1px solid rgba(125,211,252,.14);border-radius:9px;color:#eef8fa;padding:10px 12px;outline:none;min-height:42px}.ms-field select option{background:#07151c;color:#eef8fa}.ms-field textarea{min-height:100px;resize:vertical}.ms-hint{font-size:10px;color:#708993;margin-top:5px}.ms-alert{margin-bottom:16px;padding:11px 13px;border-radius:9px;background:rgba(245,158,11,.08);border:1px solid rgba(245,158,11,.18);color:#d8b66b;font-size:11px}.ms-actions{display:flex;justify-content:flex-end;padding:16px 19px;background:rgba(0,0,0,.08)}.ms-save{background:#5865f2!important;color:white!important;border:0!important;border-radius:9px!important;padding:10px 18px!important;font-weight:700!important}@media(max-width:600px){.ms-head{align-items:flex-start}.ms-title{gap:10px}.ms-icon{width:40px;height:40px}.ms-title h2{font-size:18px}.ms-title p{max-width:210px}.ms-section{padding:15px}.ms-actions .btn{width:100%}}</style>
<div class="ms-wrap"><div class="ms-head"><div class="ms-title"><div class="ms-icon"><i class="fa {{ $module['icon'] }}"></i></div><div><h2>{{ $module['title'] }}</h2><p>{{ $module['description'] }}</p></div></div><a href="{{ route('admin.discord-bot.modules') }}" class="ms-back"><i class="fa fa-arrow-left"></i> Modules</a></div>
<form method="POST" action="{{ route('admin.discord-bot.modules.module.update',['module'=>$key]) }}">{!! csrf_field() !!}{!! method_field('PATCH') !!}<div class="ms-card"><div class="ms-section"><div class="ms-toggle"><div><strong>Aktivér {{ $module['title'] }}</strong><small>Slå dette modul til eller fra.</small></div><label class="switch"><input type="checkbox" name="enabled" value="1" {{ !empty($config['enabled'])?'checked':'' }}><span class="slider"></span></label></div></div><div class="ms-section">@if($discordError)<div class="ms-alert"><i class="fa fa-exclamation-triangle"></i> {{ $discordError }}</div>@endif
@foreach($module['fields'] as $field=>$label) @php $value=old($field,$config[$field]??''); $isCategory=$field==='category_id'; $isRole=str_contains($field,'role_id'); $isChannel=str_contains($field,'channel_id'); @endphp<div class="ms-field"><label>{{ $label }}</label>
@if($isCategory)<select name="{{ $field }}"><option value="">Vælg Discord kategori...</option>@foreach($categories as $item)<option value="{{ $item['id'] }}" {{ (string)$value===(string)$item['id']?'selected':'' }}>📁 {{ $item['name'] }}</option>@endforeach @if($value && !collect($categories)->contains('id',(string)$value))<option value="{{ $value }}" selected>Gemte kategori ({{ $value }})</option>@endif</select><div class="ms-hint">Kategorier hentes automatisk fra den valgte Discord-server.</div>
@elseif($isRole)<select name="{{ $field }}"><option value="">Vælg Discord rolle...</option>@foreach($roles as $item)<option value="{{ $item['id'] }}" {{ (string)$value===(string)$item['id']?'selected':'' }}>@if($item['color'])● @endif{{ $item['name'] }}</option>@endforeach @if($value && !collect($roles)->contains('id',(string)$value))<option value="{{ $value }}" selected>Gemt rolle ({{ $value }})</option>@endif</select><div class="ms-hint">Roller hentes direkte fra Discord. Botten skal have adgang til serveren.</div>
@elseif($isChannel)<select name="{{ $field }}"><option value="">Vælg Discord kanal...</option>@foreach($channels as $item)<option value="{{ $item['id'] }}" {{ (string)$value===(string)$item['id']?'selected':'' }}>@if($item['type']===2 || $item['type']===13)🔊@else#@endif {{ $item['name'] }}</option>@endforeach @if($value && !collect($channels)->contains('id',(string)$value))<option value="{{ $value }}" selected>Gemt kanal ({{ $value }})</option>@endif</select><div class="ms-hint">Kanaler hentes automatisk fra Discord-serveren.</div>
@elseif(str_contains($field,'message'))<textarea name="{{ $field }}" placeholder="{{ $label }}">{{ $value }}</textarea>
@else<input name="{{ $field }}" value="{{ $value }}" placeholder="{{ $label }}">@endif</div>@endforeach</div><div class="ms-actions"><button class="btn ms-save" type="submit"><i class="fa fa-save"></i> Gem indstillinger</button></div></div></form></div>
@endsection
