#!/usr/bin/env bash
set -Eeuo pipefail

# Nodexa Node Installer
# Prepares a fresh Debian/Ubuntu host for Nodexa/Pterodactyl Wings.
# After this finishes, run the Configuration command generated by Nodexa Admin -> Nodes.

WINGS_VERSION="${WINGS_VERSION:-latest}"
CONFIG_DIR="/etc/pterodactyl"
DATA_DIR="/var/lib/pterodactyl"
WINGS_BIN="/usr/local/bin/wings"

info(){ printf '\033[1;36m[Nodexa]\033[0m %s\n' "$*"; }
ok(){ printf '\033[1;32m[OK]\033[0m %s\n' "$*"; }
fail(){ printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

[[ ${EUID} -eq 0 ]] || fail "Kør installeren som root (sudo -i)."
[[ -r /etc/os-release ]] || fail "Kan ikke identificere operativsystemet."
. /etc/os-release
case "${ID:-}" in
  ubuntu|debian) ;;
  *) fail "Denne version understøtter Ubuntu og Debian. Fundet: ${PRETTY_NAME:-ukendt}." ;;
esac

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) WINGS_ARCH="amd64" ;;
  aarch64|arm64) WINGS_ARCH="arm64" ;;
  *) fail "Ikke-understøttet arkitektur: $ARCH" ;;
esac

info "Klargør Nodexa node på ${PRETTY_NAME:-$ID} ($WINGS_ARCH)..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y ca-certificates curl gnupg lsb-release tar unzip ufw

if ! command -v docker >/dev/null 2>&1; then
  info "Installerer Docker Engine..."
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL "https://download.docker.com/linux/${ID}/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  CODENAME="${VERSION_CODENAME:-$(lsb_release -cs)}"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${CODENAME} stable" > /etc/apt/sources.list.d/docker.list
  apt-get update
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
else
  info "Docker er allerede installeret."
fi
systemctl enable --now docker

install -d -m 0755 "$CONFIG_DIR"
install -d -m 0755 "$DATA_DIR"

if [[ "$WINGS_VERSION" == "latest" ]]; then
  WINGS_URL="https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_${WINGS_ARCH}"
else
  WINGS_URL="https://github.com/pterodactyl/wings/releases/download/${WINGS_VERSION}/wings_linux_${WINGS_ARCH}"
fi
info "Installerer Wings..."
curl -fL "$WINGS_URL" -o "$WINGS_BIN"
chmod u+x "$WINGS_BIN"

cat > /etc/systemd/system/wings.service <<'UNIT'
[Unit]
Description=Nodexa Wings Daemon
After=docker.service
Requires=docker.service
PartOf=docker.service

[Service]
User=root
WorkingDirectory=/etc/pterodactyl
LimitNOFILE=4096
PIDFile=/var/run/wings/daemon.pid
ExecStart=/usr/local/bin/wings
Restart=on-failure
StartLimitInterval=180
StartLimitBurst=30
RestartSec=5s

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable wings

if command -v ufw >/dev/null 2>&1; then
  info "Forbereder firewall-regler..."
  ufw allow 22/tcp >/dev/null || true
  ufw allow 8080/tcp >/dev/null || true
  ufw allow 2022/tcp >/dev/null || true
  # Do not force-enable UFW: that can unexpectedly lock down an existing host.
fi

cat > /usr/local/bin/nodexa-node <<'CLI'
#!/usr/bin/env bash
set -e
case "${1:-status}" in
  status) systemctl status wings --no-pager || true ;;
  start) systemctl start wings ;;
  stop) systemctl stop wings ;;
  restart) systemctl restart wings ;;
  logs) journalctl -u wings -n 150 --no-pager ;;
  follow) journalctl -u wings -f ;;
  config) ${EDITOR:-nano} /etc/pterodactyl/config.yml ;;
  *) echo "Brug: nodexa-node {status|start|stop|restart|logs|follow|config}"; exit 1 ;;
esac
CLI
chmod +x /usr/local/bin/nodexa-node

ok "Node-klargøring er færdig."
printf '\nNæste trin:\n'
printf '  1. Opret noden i Nodexa Admin -> Nodes.\n'
printf '  2. Åbn nodens Configuration-fane.\n'
printf '  3. Kør Configuration-commanden på denne server.\n'
printf '  4. Kør: systemctl start wings\n\n'
printf 'Hjælp: nodexa-node status | logs | follow | restart\n'
printf 'Wings config forventes i: %s/config.yml\n' "$CONFIG_DIR"
