@extends('store.layout')
@section('title','Game Server Hosting')
@section('description','Nodexa leverer game server hosting med ét samlet kontrolpanel til konsol, filer, databaser, backups og serverdrift.')
@section('content')
<section class="hero"><div class="container"><div class="pill"><span class="statusdot"></span> Infrastruktur klar til nye servere</div><h1>Hosting til communities<br><span class="gradient">der forventer mere.</span></h1><p class="lead">En samlet hostingplatform til bestilling, deployment og daglig serverdrift. Administrér hele serveren fra Nodexa Control Panel.</p><div class="heroactions"><a class="btn primary" href="{{route('store.hosting')}}">Udforsk server hosting →</a><a class="btn" href="{{route('store.features')}}">Se kontrolpanelet</a></div><div class="proof"><span>✓ <strong>Central serverstyring</strong></span><span>✓ <strong>Automatiseret ordreflow</strong></span><span>✓ <strong>Mobilvenligt panel</strong></span></div></div></section>
<div class="container"><div class="metricbar"><div class="metric"><span>PLATFORM</span><strong>Nodexa Control Panel</strong></div><div class="metric"><span>SERVERSTYRING</span><strong>24/7 adgang</strong></div><div class="metric"><span>DEPLOYMENT</span><strong>Integreret provisioning</strong></div><div class="metric"><span>ADMINISTRATION</span><strong>Web + SFTP</strong></div></div></div>
<section class="section"><div class="container"><div class="sectionhead"><div><div class="eyebrow">Hostingplatform</div><h2>Fra ordre til server. Ét flow.</h2><p class="muted" style="max-width:650px">Nodexa er designet som én sammenhængende oplevelse i stedet for en samling separate værktøjer.</p></div><a class="btn" href="{{route('store.features')}}">Udforsk platformen →</a></div><div class="grid"><article class="card"><div class="miniLabel">01 · CONTROL</div><div class="icon" style="margin-top:15px">⌘</div><h3>Serverkontrol i realtid</h3><p class="muted">Power actions, live-konsol og ressourceforbrug samlet i serverens workspace.</p></article><article class="card"><div class="miniLabel">02 · DATA</div><div class="icon" style="margin-top:15px">▣</div><h3>Filer, backups & databaser</h3><p class="muted">Administrér serverdata gennem panelet og brug SFTP, når du har brug for direkte filadgang.</p></article><article class="card"><div class="miniLabel">03 · AUTOMATION</div><div class="icon" style="margin-top:15px">◷</div><h3>Schedules & provisioning</h3><p class="muted">Automatisér serveropgaver og forbind kundens bestilling med den rigtige serverkonfiguration.</p></article></div></div></section>
<div class="trustline"><div class="container trustlinein"><span>Powered by <b>Nodexa</b></span><span>Server Console</span><span>Database Manager</span><span>SFTP Access</span><span>Automated Backups</span></div></div>
<section class="section alt"><div class="container"><div class="sectionhead"><div><div class="eyebrow">Aktuelle serverpakker</div><h2>Start med de ressourcer, du har brug for.</h2><p class="muted">Ingen skjulte produktkort på forsiden — specifikationer og pris vises direkte.</p></div><a class="btn" href="{{route('store.hosting')}}">Alle pakker →</a></div><div class="grid">@forelse($products->take(3) as $p)<article class="card {{$p->featured?'featured':''}}"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><span class="tag">{{$p->game}}</span>@if($p->featured)<span class="miniLabel" style="color:#a996ff">★ Fremhævet</span>@endif</div><h3 style="font-size:24px">{{$p->name}}</h3><p class="muted">{{$p->description ?: 'Serverpakke klar til Nodexa Control Panel.'}}</p><div class="price">{{number_format($p->price_monthly,0,',','.')}} kr <small>/ md.</small></div><div class="specs"><span>{{$p->memory}} MB RAM</span><span>{{$p->cpu}}% CPU</span><span>{{$p->disk}} MB disk</span><span>{{$p->backups}} backups</span></div><a class="btn primary" style="width:100%;margin-top:20px" href="{{route('store.product',$p)}}">Konfigurér →</a></article>@empty<article class="card" style="grid-column:1/-1;text-align:center;padding:50px"><div class="miniLabel">STORE CATALOG</div><h3 style="font-size:24px">Serverpakker er ved at blive klargjort</h3><p class="muted">Aktive produkter vises automatisk her fra Storefront & Billing.</p></article>@endforelse</div></div></section>
<section class="section"><div class="container"><div class="cta"><div><div class="eyebrow">Nodexa Game Server Cloud</div><h2 style="margin:5px 0 7px">Én konto. Én platform. Dine servere.</h2><p class="muted" style="margin:0">Vælg en serverpakke og fortsæt gennem Nodexas integrerede ordreflow.</p></div><a class="btn primary" href="{{route('store.hosting')}}">Se server hosting →</a></div></div></section>
@endsection