@extends('store.layout')
@section('title',$product->name)
@section('description',$product->description ?: 'Konfigurér og bestil din Nodexa server.')
@section('content')
<section class="pagehero"><div class="container"><div class="eyebrow">{{$product->game}} · Serverpakke</div><h1>{{$product->name}}</h1><p class="lead">{{$product->description ?: 'Konfigurér din server og fortsæt til checkout.'}}</p></div></section>
<section class="section"><div class="container" style="max-width:1000px"><div style="display:grid;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr);gap:20px" class="product-layout">
<div class="card"><div class="eyebrow">Inkluderet</div><h2 style="margin-top:7px">Serverressourcer</h2><div class="specs" style="grid-template-columns:repeat(2,1fr);font-size:15px;gap:13px"><span>◆ <b>{{$product->memory}} MB</b> RAM</span><span>◆ <b>{{$product->cpu}}%</b> CPU</span><span>◆ <b>{{$product->disk}} MB</b> disk</span><span>◆ <b>{{$product->backups}}</b> backups</span><span>◆ <b>{{$product->databases}}</b> databaser</span><span>◆ <b>{{$product->allocations}}</b> allocations</span></div><div style="margin-top:28px;padding-top:22px;border-top:1px solid var(--line)"><h3>Nodexa Control Panel</h3><p class="muted">Efter aktivering administrerer du serveren fra Nodexa med konsol, filer, netværk, databaser, schedules og backups.</p></div></div>
<aside class="card featured"><span class="tag">Månedlig hosting</span><div class="price">{{number_format($product->price_monthly,2,',','.')}} kr <small>/ måned</small></div><p class="muted" style="font-size:13px">Serveren oprettes først, når ordren er registreret som betalt.</p>@auth<form method="POST" action="{{route('store.order',$product)}}">@csrf<label for="server_name" style="display:block;font-size:13px;font-weight:800;margin:19px 0 7px">Servernavn</label><input id="server_name" name="server_name" required minlength="3" maxlength="100" placeholder="F.eks. Min Minecraft Server" style="width:100%;height:47px;padding:0 13px;border-radius:10px;border:1px solid #294765;background:#071320;color:white;outline:none"><button class="btn primary" style="width:100%;margin-top:12px">Fortsæt til checkout →</button></form>@else<a class="btn primary" style="width:100%;margin-top:16px" href="/auth/login">Log ind for at bestille →</a><p class="muted" style="font-size:12px;text-align:center">Du skal være logget ind for at oprette en ordre.</p>@endauth</aside></div><div style="margin-top:20px"><a class="muted" href="{{route('store.hosting')}}">← Tilbage til server hosting</a></div></div></section>
@push('styles')<style>@media(max-width:760px){.product-layout{grid-template-columns:1fr!important}}</style>@endpush
@endsection