package api

import (
	"io"
	"net/http"
	"os"
	"path/filepath"

	"github.com/gin-gonic/gin"
	gpDocker "nodexa/agent/internal/docker"
	"nodexa/agent/internal/server"
	nodexaSFTP "nodexa/agent/internal/sftp"
)

type API struct { token string; docker *gpDocker.Manager; sftpStore *nodexaSFTP.CredentialStore }
func New(token string,d *gpDocker.Manager, stores ...*nodexaSFTP.CredentialStore)*API{a:=&API{token:token,docker:d};if len(stores)>0{a.sftpStore=stores[0]};return a}
func(a *API)Router()*gin.Engine{r:=gin.New();r.Use(gin.Recovery());r.GET("/health",func(c *gin.Context){c.JSON(200,gin.H{"ok":true,"service":"nodexa-agent"})});api:=r.Group("/api",a.auth);api.PUT("/servers/:id/sftp",a.setSFTP);api.DELETE("/servers/:id/sftp",a.deleteSFTP);api.POST("/servers",a.create);api.POST("/servers/:id/reinstall",a.reinstall);api.PUT("/servers/:id/runtime",a.reconfigure);api.POST("/servers/:id/power",a.power);api.POST("/servers/:id/command",a.command);api.POST("/servers/:id/stdin",a.stdin);api.GET("/servers/:id/stats",a.stats);api.GET("/servers/:id/logs",a.logs);api.GET("/servers/:id/logs/stream",a.streamLogs);api.GET("/servers/:id/files",a.listFiles);api.GET("/servers/:id/files/content",a.readFile);api.PUT("/servers/:id/files/content",a.writeFile);api.POST("/servers/:id/files/directory",a.makeDirectory);api.POST("/servers/:id/files/rename",a.renameFile);api.POST("/servers/:id/files/upload",a.uploadFile);api.GET("/servers/:id/files/download",a.downloadFile);api.POST("/servers/:id/files/archive",a.archiveFile);api.POST("/servers/:id/files/extract",a.extractFile);api.DELETE("/servers/:id/files",a.deleteFile);api.GET("/servers/:id/backups",a.listBackups);api.POST("/servers/:id/backups",a.backup);api.GET("/servers/:id/backups/:name",a.downloadBackup);api.POST("/servers/:id/backups/:name/restore",a.restoreBackup);api.DELETE("/servers/:id/backups/:name",a.deleteBackup);return r}
func(a *API)auth(c *gin.Context){if c.GetHeader("Authorization")!="Bearer "+a.token{c.AbortWithStatusJSON(401,gin.H{"error":"unauthorized"});return};c.Next()}
func(a *API)setSFTP(c *gin.Context){if a.sftpStore==nil{c.JSON(503,gin.H{"error":"SFTP credential store unavailable"});return};var q struct{Username string `json:"username"`;Password string `json:"password"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};if err:=a.sftpStore.Upsert(nodexaSFTP.Credential{Username:q.Username,Password:q.Password,ServerUUID:c.Param("id")});err!=nil{c.JSON(422,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true,"username":q.Username})}
func(a *API)deleteSFTP(c *gin.Context){if a.sftpStore==nil{c.JSON(503,gin.H{"error":"SFTP credential store unavailable"});return};if err:=a.sftpStore.DeleteServer(c.Param("id"));err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true})}
func(a *API)create(c *gin.Context){var q server.CreateRequest;if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request","detail":err.Error()});return};if err:=a.docker.Create(c,q);err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(201,gin.H{"id":q.ID,"status":"created"})}
func(a *API)reinstall(c *gin.Context){var q server.CreateRequest;if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request","detail":err.Error()});return};q.ID=c.Param("id");if err:=a.docker.ReinstallWithProgress(c,q);err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"id":q.ID,"status":"reinstalled"})}
func(a *API)reconfigure(c *gin.Context){var q server.CreateRequest;if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request","detail":err.Error()});return};q.ID=c.Param("id");if err:=a.docker.Reconfigure(c,q);err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"id":q.ID,"status":"reconfigured"})}
func(a *API)power(c *gin.Context){var q struct{Signal string `json:"signal"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};id:=c.Param("id");var err error;switch q.Signal{case"start":err=a.docker.StartWithDiagnostics(c,id);case"stop":err=a.docker.Stop(c,id);case"restart":err=a.docker.Restart(c,id);case"kill":err=a.docker.Kill(c,id);default:c.JSON(422,gin.H{"error":"invalid signal"});return};if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true})}
func(a *API)command(c *gin.Context){var q struct{Command string `json:"command"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};if err:=a.docker.WriteStdin(c,c.Param("id"),q.Command);err!=nil{c.JSON(409,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true,"mode":"stdin"})}
func(a *API)stdin(c *gin.Context){var q struct{Input string `json:"input"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};if err:=a.docker.WriteStdin(c,c.Param("id"),q.Input);err!=nil{c.JSON(409,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true})}
func(a *API)stats(c *gin.Context){stats,err:=a.docker.Stats(c,c.Param("id"));if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,stats)}
func(a *API)logs(c *gin.Context){id:=c.Param("id");tail:=c.DefaultQuery("tail","200");if output,handled,err:=a.docker.InstallConsole(c,id,tail);err!=nil{c.JSON(500,gin.H{"error":err.Error()});return}else if handled{c.Data(200,"text/plain; charset=utf-8",[]byte(output+"\n"));return};reader,err:=a.docker.Logs(c,id,tail);if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};defer reader.Close();body,err:=io.ReadAll(io.LimitReader(reader,2*1024*1024));if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.Data(200,"text/plain; charset=utf-8",body)}
func(a *API)streamLogs(c *gin.Context){reader,err:=a.docker.StreamLogs(c,c.Param("id"),c.DefaultQuery("tail","100"));if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};defer reader.Close();c.Header("Content-Type","text/plain; charset=utf-8");c.Header("Cache-Control","no-cache, no-transform");c.Header("X-Accel-Buffering","no");c.Status(http.StatusOK);buf:=make([]byte,32*1024);for{n,readErr:=reader.Read(buf);if n>0{if _,err:=c.Writer.Write(buf[:n]);err!=nil{return};c.Writer.Flush()};if readErr!=nil{return}}}
func(a *API)listFiles(c *gin.Context){path,err:=a.docker.SafePath(c.Param("id"),c.DefaultQuery("path","/"));if err!=nil{c.JSON(400,gin.H{"error":err.Error()});return};items,err:=os.ReadDir(path);if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};out:=make([]gin.H,0,len(items));for _,item:=range items{info,e:=item.Info();if e!=nil{continue};out=append(out,gin.H{"name":item.Name(),"directory":item.IsDir(),"size":info.Size(),"modified_at":info.ModTime()})};c.JSON(200,gin.H{"items":out})}
func(a *API)readFile(c *gin.Context){path,err:=a.docker.SafePath(c.Param("id"),c.Query("path"));if err!=nil{c.JSON(400,gin.H{"error":err.Error()});return};info,err:=os.Stat(path);if err!=nil{c.JSON(404,gin.H{"error":err.Error()});return};if info.IsDir(){c.JSON(422,gin.H{"error":"path is a directory"});return};if info.Size()>8*1024*1024{c.JSON(413,gin.H{"error":"file is too large for the web editor; download it instead"});return};body,err:=os.ReadFile(path);if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.Data(200,"text/plain; charset=utf-8",body)}
func(a *API)writeFile(c *gin.Context){path,err:=a.docker.SafePath(c.Param("id"),c.Query("path"));if err!=nil{c.JSON(400,gin.H{"error":err.Error()});return};body,err:=io.ReadAll(io.LimitReader(c.Request.Body,8*1024*1024+1));if err!=nil{c.JSON(400,gin.H{"error":err.Error()});return};if len(body)>8*1024*1024{c.JSON(413,gin.H{"error":"editor payload exceeds 8 MB"});return};if err=os.MkdirAll(filepath.Dir(path),0750);err==nil{err=os.WriteFile(path,body,0640)};if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true,"bytes":len(body)})}
func(a *API)makeDirectory(c *gin.Context){var q struct{Path string `json:"path"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};path,err:=a.docker.SafePath(c.Param("id"),q.Path);if err==nil{err=os.MkdirAll(path,0750)};if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(201,gin.H{"ok":true})}
func(a *API)renameFile(c *gin.Context){var q struct{From string `json:"from"`;To string `json:"to"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};if err:=a.docker.RenamePath(c.Param("id"),q.From,q.To);err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true})}
func(a *API)uploadFile(c *gin.Context){c.Request.Body=http.MaxBytesReader(c.Writer,c.Request.Body,512*1024*1024);fh,err:=c.FormFile("file");if err!=nil{c.JSON(422,gin.H{"error":"file is required"});return};name:=filepath.Base(fh.Filename);if name=="."||name==""{c.JSON(422,gin.H{"error":"invalid filename"});return};targetRel:=filepath.ToSlash(filepath.Join(c.PostForm("path"),name));target,err:=a.docker.SafePath(c.Param("id"),targetRel);if err!=nil{c.JSON(400,gin.H{"error":err.Error()});return};if err:=os.MkdirAll(filepath.Dir(target),0750);err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};src,err:=fh.Open();if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};defer src.Close();dst,err:=os.OpenFile(target,os.O_CREATE|os.O_TRUNC|os.O_WRONLY,0640);if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};written,copyErr:=io.Copy(dst,src);closeErr:=dst.Close();if copyErr!=nil{c.JSON(500,gin.H{"error":copyErr.Error()});return};if closeErr!=nil{c.JSON(500,gin.H{"error":closeErr.Error()});return};c.JSON(201,gin.H{"ok":true,"name":name,"bytes":written})}
func(a *API)downloadFile(c *gin.Context){path,err:=a.docker.SafePath(c.Param("id"),c.Query("path"));if err!=nil{c.JSON(400,gin.H{"error":err.Error()});return};info,err:=os.Stat(path);if err!=nil{c.JSON(404,gin.H{"error":err.Error()});return};if info.IsDir(){c.JSON(422,gin.H{"error":"directories must be archived before download"});return};c.FileAttachment(path,filepath.Base(path))}
func(a *API)archiveFile(c *gin.Context){var q struct{Path string `json:"path"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};path,err:=a.docker.ArchivePath(c.Param("id"),q.Path);if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(201,gin.H{"ok":true,"path":path})}
func(a *API)extractFile(c *gin.Context){var q struct{Path string `json:"path"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};if err:=a.docker.ExtractPath(c.Param("id"),q.Path);err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true})}
func(a *API)deleteFile(c *gin.Context){path,err:=a.docker.SafePath(c.Param("id"),c.Query("path"));if err==nil{err=os.RemoveAll(path)};if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true})}
func(a *API)listBackups(c *gin.Context){items,err:=a.docker.ListBackups(c.Param("id"));if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"items":items})}
func(a *API)backup(c *gin.Context){var q struct{Name string `json:"name"`};if err:=c.ShouldBindJSON(&q);err!=nil{c.JSON(422,gin.H{"error":"invalid request"});return};path,err:=a.docker.Backup(c.Param("id"),q.Name);if err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};info,err:=os.Stat(path);if err!=nil{c.JSON(500,gin.H{"error":"backup was created but could not be inspected: "+err.Error()});return};c.JSON(201,gin.H{"ok":true,"name":filepath.Base(path),"bytes":info.Size(),"modified_at":info.ModTime()})}
func(a *API)downloadBackup(c *gin.Context){path,err:=a.docker.BackupPath(c.Param("id"),c.Param("name"));if err!=nil{c.JSON(404,gin.H{"error":err.Error()});return};c.FileAttachment(path,filepath.Base(path))}
func(a *API)restoreBackup(c *gin.Context){if err:=a.docker.RestoreBackup(c,c.Param("id"),c.Param("name"));err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true,"status":"restored"})}
func(a *API)deleteBackup(c *gin.Context){if err:=a.docker.DeleteBackup(c.Param("id"),c.Param("name"));err!=nil{c.JSON(500,gin.H{"error":err.Error()});return};c.JSON(200,gin.H{"ok":true})}
