<?php
namespace Pterodactyl\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Pterodactyl\Models\SupportTicket;
use Pterodactyl\Services\Support\TicketNotificationService;
class SupportTicketController extends Controller {
 public function __construct(private TicketNotificationService $notifications) {}
 public function index(Request $r){return view('store.client.tickets.index',['tickets'=>SupportTicket::where('user_id',$r->user()->id)->with('server')->latest('last_reply_at')->latest()->get()]);}
 public function create(Request $r){return view('store.client.tickets.create',['servers'=>$r->user()->servers()->orderBy('name')->get()]);}
 private function due(string $priority){return now()->addMinutes(['urgent'=>60,'high'=>240,'normal'=>720,'low'=>1440][$priority]??720);}
 private function attach(Request $r,SupportTicket $ticket,$message): void {foreach($r->file('attachments',[]) as $file){$path=$file->store('support-tickets/'.$ticket->id,'local');$ticket->attachments()->create(['message_id'=>$message->id,'user_id'=>$r->user()->id,'disk'=>'local','path'=>$path,'original_name'=>$file->getClientOriginalName(),'mime'=>$file->getMimeType(),'size'=>$file->getSize()]);}}
 public function store(Request $r){$d=$r->validate(['subject'=>'required|string|max:160','department'=>'required|in:support,billing,technical,sales','priority'=>'required|in:low,normal,high,urgent','server_id'=>'nullable|integer','message'=>'required|string|min:10|max:20000','attachments.*'=>'file|max:10240|mimes:png,jpg,jpeg,gif,webp,pdf,txt,log,zip']);if(!empty($d['server_id'])&&!$r->user()->servers()->whereKey($d['server_id'])->exists())abort(403);$ticket=SupportTicket::create(['ticket_number'=>'NX-'.strtoupper(Str::random(8)),'user_id'=>$r->user()->id,'server_id'=>$d['server_id']??null,'subject'=>$d['subject'],'department'=>$d['department'],'priority'=>$d['priority'],'status'=>'open','last_reply_at'=>now(),'last_customer_reply_at'=>now(),'due_at'=>$this->due($d['priority'])]);$m=$ticket->messages()->create(['user_id'=>$r->user()->id,'staff'=>false,'message'=>$d['message']]);$this->attach($r,$ticket,$m);$ticket->events()->create(['user_id'=>$r->user()->id,'event'=>'created','details'=>'Ticket created']);$this->notifications->created($ticket);return redirect()->route('store.client.tickets.show',$ticket);}
 public function show(Request $r,SupportTicket $ticket){abort_unless($ticket->user_id===$r->user()->id,403);$ticket->load(['messages'=>fn($q)=>$q->where('internal',false)->with(['user','attachments']),'server','assignee']);return view('store.client.tickets.show',compact('ticket'));}
 public function reply(Request $r,SupportTicket $ticket){abort_unless($ticket->user_id===$r->user()->id,403);abort_if($ticket->status==='closed',422);$d=$r->validate(['message'=>'required|string|min:2|max:20000','attachments.*'=>'file|max:10240|mimes:png,jpg,jpeg,gif,webp,pdf,txt,log,zip']);$m=$ticket->messages()->create(['user_id'=>$r->user()->id,'staff'=>false,'message'=>$d['message']]);$this->attach($r,$ticket,$m);$ticket->update(['status'=>'customer_reply','last_reply_at'=>now(),'last_customer_reply_at'=>now(),'due_at'=>$this->due($ticket->priority)]);$ticket->events()->create(['user_id'=>$r->user()->id,'event'=>'customer_reply','details'=>'Customer replied']);$this->notifications->customerReply($ticket);return back();}
 public function close(Request $r,SupportTicket $ticket){abort_unless($ticket->user_id===$r->user()->id,403);$ticket->update(['status'=>'closed','closed_at'=>now(),'due_at'=>null]);$ticket->events()->create(['user_id'=>$r->user()->id,'event'=>'closed','details'=>'Closed by customer']);$this->notifications->closed($ticket);return back();}
 public function attachment(Request $r,SupportTicket $ticket,$attachment){abort_unless($ticket->user_id===$r->user()->id,403);$a=$ticket->attachments()->findOrFail($attachment);return Storage::disk($a->disk)->download($a->path,$a->original_name);}
}