@php
$selectedTicketTemplates=json_decode((string)($config['ticket_templates']??'[]'),true);if(!is_array($selectedTicketTemplates))$selectedTicketTemplates=[];
$defaults=['support'=>['emoji'=>'🎫','name'=>'Support','description'=>'Generel hjælp og spørgsmål'],'billing'=>['emoji'=>'💳','name'=>'Betaling','description'=>'Faktura, køb og betaling'],'technical'=>['emoji'=>'🔧','name'=>'Teknisk problem','description'=>'Fejl, server og teknisk hjælp'],'report'=>['emoji'=>'🚨','name'=>'Spiller-rapport','description'=>'Rapportér en spiller eller hændelse'],'staff'=>['emoji'=>'👮','name'=>'Staff-klage','description'=>'Privat klage over staff'],'ban'=>['emoji'=>'🔨','name'=>'Ban Appeal','description'=>'Ansøg om unban'],'whitelist'=>['emoji'=>'✅','name'=>'Whitelist','description'=>'Whitelist-ansøgning og hjælp'],'partner'=>['emoji'=>'🤝','name'=>'Partnerskab','description'=>'Partner- og samarbejdsforespørgsler'],'other'=>['emoji'=>'📩','name'=>'Andet','description'=>'Fleksibel standardskabelon']];
$custom=json_decode((string)($config['ticket_template_settings']??'{}'),true);if(!is_array($custom))$custom=[];$ticketTemplates=[];foreach($defaults as $k=>$v)$ticketTemplates[$k]=array_merge($v,is_array($custom[$k]??null)?$custom[$k]:[]);
@endphp
<style>
.ms-template{position:relative}.ms-template.selected{border-color:#5865f2!important;background:rgba(88,101,242,.18)!important}.ms-template .ms-check{float:right;width:18px;height:18px;border-radius:50%;border:1px solid rgba(125,211,252,.25);display:flex;align-items:center;justify-content:center;font-size:10px;color:transparent}.ms-template.selected .ms-check{background:#5865f2;border-color:#5865f2;color:#fff}.ms-template-edit{position:absolute;right:8px;bottom:8px;border:0;background:transparent;color:#8298a2;padding:4px;z-index:3}.ms-template-edit:hover{color:#fff}.ms-selected-summary{margin-top:12px;padding:11px;border-radius:9px;background:rgba(88,101,242,.06);border:1px solid rgba(88,101,242,.13)}.ms-selected-summary b{font-size:10px;color:#aab2ff}.ms-selected-chips{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.ms-selected-chip{padding:5px 8px;border-radius:7px;background:#0a1b24;border:1px solid rgba(125,211,252,.13);font-size:10px;color:#dbe7eb}.ms-selected-empty{font-size:10px;color:#78909a;margin-top:6px}.ms-editor{display:none;margin-top:14px;padding:14px;border:1px solid rgba(88,101,242,.2);background:#07151c;border-radius:10px}.ms-editor.open{display:block}.ms-editor-grid{display:grid;grid-template-columns:90px 1fr;gap:10px}.ms-editor label{font-size:10px;color:#9db0b8;display:block;margin-bottom:5px}.ms-editor input,.ms-editor textarea{width:100%;background:#0a1b24;border:1px solid rgba(125,211,252,.14);border-radius:8px;color:#fff;padding:9px}.ms-editor textarea{min-height:70px}.ms-editor-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:10px}.ms-editor-actions button{border-radius:7px;padding:7px 11px;border:1px solid rgba(125,211,252,.14);background:#0a1b24;color:#dbe7eb}.ms-editor-actions .save{background:#5865f2;border-color:#5865f2;color:#fff}
</style>
<input type="hidden" name="ticket_templates" id="ticket-templates-value" value="{{ json_encode(array_values($selectedTicketTemplates)) }}"><input type="hidden" name="ticket_template_settings" id="ticket-template-settings" value="{{ json_encode($ticketTemplates,JSON_UNESCAPED_UNICODE) }}">
<div class="ms-section"><div class="ms-template-head"><div><div class="ms-section-title" style="margin:0"><i class="fa fa-magic"></i> Ticket Templates</div><p>Vælg flere templates, eller tryk på blyanten for at ændre navn, emoji og beskrivelse.</p></div></div><div class="ms-template-grid">
@foreach($ticketTemplates as $templateKey=>$template)<button type="button" class="ms-template ms-template-choice {{ in_array($templateKey,$selectedTicketTemplates,true)?'selected':'' }}" data-template="{{ $templateKey }}"><span class="ms-check"><i class="fa fa-check"></i></span><span class="emoji">{{ $template['emoji'] }}</span><b>{{ $template['name'] }}</b><small>{{ $template['description'] }}</small><span class="ms-template-edit" title="Rediger template"><i class="fa fa-pencil"></i></span></button>@endforeach
</div><div id="template-editor" class="ms-editor"><div class="ms-section-title">Rediger <span id="editor-template-name"></span></div><div class="ms-editor-grid"><div><label>Emoji</label><input id="editor-emoji" maxlength="16"></div><div><label>Navn</label><input id="editor-name" maxlength="60"></div></div><div style="margin-top:10px"><label>Beskrivelse</label><textarea id="editor-description" maxlength="180"></textarea></div><div class="ms-editor-actions"><button type="button" id="editor-cancel">Annuller</button><button type="button" class="save" id="editor-save"><i class="fa fa-save"></i> Gem template</button></div></div><div class="ms-selected-summary"><b>VALGTE TICKET-KATEGORIER</b><div id="ticket-template-chips" class="ms-selected-chips"></div><div id="ticket-template-empty" class="ms-selected-empty">Ingen templates valgt endnu.</div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){var input=document.getElementById('ticket-templates-value'),settingsInput=document.getElementById('ticket-template-settings');if(!input||!settingsInput)return;var selected=[],settings={};try{selected=JSON.parse(input.value||'[]');}catch(e){}try{settings=JSON.parse(settingsInput.value||'{}');}catch(e){}if(!Array.isArray(selected))selected=[];var editing=null,editor=document.getElementById('template-editor');function label(k){var x=settings[k]||{};return(x.emoji?x.emoji+' ':'')+(x.name||k)}function render(){input.value=JSON.stringify(selected);settingsInput.value=JSON.stringify(settings);document.querySelectorAll('.ms-template-choice').forEach(function(b){var x=settings[b.dataset.template]||{};b.classList.toggle('selected',selected.indexOf(b.dataset.template)!==-1);b.querySelector('.emoji').textContent=x.emoji||'';b.querySelector('b').textContent=x.name||b.dataset.template;b.querySelector('small').textContent=x.description||''});var chips=document.getElementById('ticket-template-chips'),empty=document.getElementById('ticket-template-empty');chips.innerHTML='';selected.forEach(function(k){var c=document.createElement('span');c.className='ms-selected-chip';c.textContent=label(k);chips.appendChild(c)});empty.style.display=selected.length?'none':'block'}function openEditor(k){editing=k;var x=settings[k]||{};document.getElementById('editor-template-name').textContent=x.name||k;document.getElementById('editor-emoji').value=x.emoji||'';document.getElementById('editor-name').value=x.name||'';document.getElementById('editor-description').value=x.description||'';editor.classList.add('open');editor.scrollIntoView({behavior:'smooth',block:'nearest'})}document.querySelectorAll('.ms-template-choice').forEach(function(b){b.addEventListener('click',function(e){e.preventDefault();if(e.target.closest('.ms-template-edit')){openEditor(b.dataset.template);return}var k=b.dataset.template,i=selected.indexOf(k);if(i===-1)selected.push(k);else selected.splice(i,1);render()})});document.getElementById('editor-cancel').onclick=function(){editor.classList.remove('open');editing=null};document.getElementById('editor-save').onclick=function(){if(!editing)return;settings[editing]={emoji:document.getElementById('editor-emoji').value.trim(),name:document.getElementById('editor-name').value.trim()||editing,description:document.getElementById('editor-description').value.trim()};render();editor.classList.remove('open');editing=null};render()});
</script>
