@extends('layouts.admin')
@section('title')Database Hosts@endsection
@section('content-header')<h1>Database Hosts <small>Forbind og administrér eksterne MySQL/MariaDB hosts.</small></h1><ol class="breadcrumb"><li><a href="{{route('admin.index')}}">Admin</a></li><li class="active">Database Hosts</li></ol>@endsection
@section('content')
<style>.nx-db-hero{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:14px;padding:18px;border:1px solid var(--nodexa-border);border-radius:14px;background:linear-gradient(135deg,var(--nodexa-surface-2),var(--nodexa-surface))}.nx-db-hero h3{margin:0 0 5px;font-weight:800}.nx-db-hero p{margin:0;color:var(--nodexa-muted);font-size:11px}.nx-db-tip{margin-bottom:14px;padding:12px 14px;border:1px solid rgba(var(--nodexa-accent-rgb),.18);border-radius:11px;background:rgba(var(--nodexa-accent-rgb),.055);color:#9fb5c1;font-size:11px}.nx-db-tip i{margin-right:6px;color:var(--nodexa-accent)}.nx-db-empty{padding:42px 18px;text-align:center;color:var(--nodexa-muted)}.nx-db-empty i{display:block;margin-bottom:10px;color:var(--nodexa-accent);font-size:28px}.nx-db-endpoint{display:inline-flex;gap:5px;align-items:center;padding:4px 7px;border:1px solid var(--nodexa-border);border-radius:7px;background:var(--nodexa-bg-2)}@media(max-width:767px){.nx-db-hero{align-items:stretch;flex-direction:column}.nx-db-hero .btn{width:100%}}</style>
<div class="nx-db-hero"><div><h3><i class="fa fa-database" style="color:var(--nodexa-accent);margin-right:7px"></i>Database Infrastructure</h3><p>Nodexa validerer forbindelsen, før en ny database-host gemmes.</p></div><button class="btn btn-primary" data-toggle="modal" data-target="#newHostModal"><i class="fa fa-plus"></i> Tilføj database-host</button></div>
<div class="nx-db-tip"><i class="fa fa-shield"></i><strong>Forbindelsestjek:</strong> Hvis en host ikke kan nås, viser Nodexa nu en læsbar diagnose uden at eksponere den rå SQL-fejl. Connection refused betyder normalt, at MySQL/MariaDB ikke lytter eksternt eller at en firewall blokerer porten.</div>
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Database Hosts</h3><div class="box-tools"><span class="nx-u-badge">{{count($hosts)}} hosts</span></div></div><div class="box-body table-responsive no-padding"><table class="table table-hover"><thead><tr><th>ID</th><th>Navn</th><th>Endpoint</th><th>Bruger</th><th class="text-center">Databaser</th><th class="text-center">Node</th></tr></thead><tbody>@forelse($hosts as $host)<tr><td><code>#{{$host->id}}</code></td><td><a href="{{route('admin.databases.view',$host->id)}}"><strong>{{$host->name}}</strong></a></td><td><span class="nx-db-endpoint"><i class="fa fa-plug"></i><code>{{$host->host}}:{{$host->port}}</code></span></td><td>{{$host->username}}</td><td class="text-center">{{$host->databases_count}}</td><td class="text-center">@if(!is_null($host->node))<a href="{{route('admin.nodes.view',$host->node->id)}}">{{$host->node->name}}</a>@else<span class="label label-default">Ingen</span>@endif</td></tr>@empty<tr><td colspan="6"><div class="nx-db-empty"><i class="fa fa-database"></i><strong>Ingen database-hosts endnu</strong><br><small>Tilføj en MySQL/MariaDB host for at oprette serverdatabaser.</small></div></td></tr>@endforelse</tbody></table></div></div>
<div class="modal fade" id="newHostModal" tabindex="-1" role="dialog"><div class="modal-dialog" role="document"><div class="modal-content"><form action="{{route('admin.databases')}}" method="POST"><div class="modal-header"><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button><h4 class="modal-title">Tilføj database-host</h4></div><div class="modal-body"><div class="form-group"><label for="pName">Navn</label><input type="text" name="name" id="pName" class="form-control" value="{{old('name')}}" required><p class="text-muted small">Et genkendeligt navn, fx <code>mysql-node-01</code>.</p></div><div class="row"><div class="col-md-8"><label for="pHost">Host / IP</label><input type="text" name="host" id="pHost" class="form-control" value="{{old('host')}}" required><p class="text-muted small">IP eller FQDN som Nodexa-panelet kan nå.</p></div><div class="col-md-4"><label for="pPort">Port</label><input type="number" name="port" id="pPort" class="form-control" value="{{old('port',3306)}}" min="1" max="65535" required></div></div><div class="row"><div class="col-md-6"><label for="pUsername">Brugernavn</label><input type="text" name="username" id="pUsername" class="form-control" value="{{old('username')}}" required></div><div class="col-md-6"><label for="pPassword">Adgangskode</label><input type="password" name="password" id="pPassword" class="form-control" required></div></div><div class="form-group" style="margin-top:14px"><label for="pNodeId">Tilknyttet node</label><select name="node_id" id="pNodeId" class="form-control"><option value="">Ingen</option>@foreach($locations as $location)<optgroup label="{{$location->short}}">@foreach($location->nodes as $node)<option value="{{$node->id}}" {{(string)old('node_id')===(string)$node->id?'selected':''}}>{{$node->name}}</option>@endforeach</optgroup>@endforeach</select><p class="text-muted small">Bruges som standard database-host for servere på den valgte node.</p></div><div class="callout callout-info"><strong>Før du gemmer:</strong> MySQL/MariaDB skal acceptere forbindelser fra Nodexa-panelets IP. Brugeren skal have de nødvendige rettigheder, inklusive <code>WITH GRANT OPTION</code>.</div></div><div class="modal-footer">{!!csrf_field()!!}<button type="button" class="btn btn-default pull-left" data-dismiss="modal">Annuller</button><button type="submit" class="btn btn-success"><i class="fa fa-plug"></i> Test & opret</button></div></form></div></div></div>
@endsection
@section('footer-scripts')@parent<script>$('#pNodeId').select2({width:'100%'});@if($errors->any()||old('host'))$('#newHostModal').modal('show');@endif</script>@endsection
