<?php
namespace Pterodactyl\Http\Controllers\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Pterodactyl\Http\Controllers\Controller;
use Pterodactyl\Models\SupportTicket;
use Pterodactyl\Models\User;
use Pterodactyl\Models\SupportSetting;
use Pterodactyl\Services\Support\TicketNotificationService;
class SupportTicketController extends Controller {
 public function __construct(private TicketNotificationService $notifications) {}
 public function index(Request $r){$q=SupportTicket::with(['user','server','assignee'])->withCount('messages')->latest('last_reply_at');foreach(['status','priority','department','assigned_to'] as $f)if($r->filled($f))$q->where($f,$r->$f);return view('admin.tickets.index',['tickets'=>$q->limit(200)->get(),'staff'=>User::where('root_admin',true)->orderBy('username')->get()]);}
 public function show(SupportTicket $ticket){$ticket->load(['user','server','assignee','messages.user','messages.attachments','events.user']);return view('admin.tickets.show',['ticket'=>$ticket,'staff'=>User::where('root_admin',true)->orderBy('username')->get()]);}
 private function due(string $priority){return now()->addMinutes(['urgent'=>60,'high'=>240,'normal'=>720,'low'=>1440][$priority]??720);}
 private function attach(Request $r,SupportTicket $ticket,$message): void {foreach($r->file('attachments',[]) as $file){$path=$file->store('support-tickets/'.$ticket->id,'local');$ticket->attachments()->create(['message_id'=>$message->id,'user_id'=>$r->user()->id,'disk'=>'local','path'=>$path,'original_name'=>$file->getClientOriginalName(),'mime'=>$file->getMimeType(),'size'=>$file->getSize()]);}}
 public function reply(Request $r,SupportTicket $ticket){$d=$r->validate(['message'=>'required|string|min:2|max:20000','status'=>'nullable|in:open,waiting_customer,answered,closed','internal'=>'nullable|boolean','attachments.*'=>'file|max:10240|mimes:png,jpg,jpeg,gif,webp,pdf,txt,log,zip']);$internal=$r->boolean('internal');$m=$ticket->messages()->create(['user_id'=>$r->user()->id,'staff'=>true,'internal'=>$internal,'message'=>$d['message']]);$this->attach($r,$ticket,$m);if(!$internal){$status=$d['status']??'answered';$ticket->update(['status'=>$status,'last_reply_at'=>now(),'first_response_at'=>$ticket->first_response_at??now(),'last_staff_reply_at'=>now(),'resolved_at'=>in_array($status,['answered','closed'])?now():null,'due_at'=>$status==='closed'?null:$this->due($ticket->priority),'closed_at'=>$status==='closed'?now():null]);}$ticket->events()->create(['user_id'=>$r->user()->id,'event'=>$internal?'internal_note':'staff_reply','details'=>$internal?'Internal note added':'Staff replied']);if(!$internal){$this->notifications->staffReply($ticket);if(($status??null)==='closed')$this->notifications->closed($ticket);}return back();}
 public function update(Request $r,SupportTicket $ticket){$d=$r->validate(['status'=>'required|in:open,waiting_customer,answered,customer_reply,closed','priority'=>'required|in:low,normal,high,urgent','department'=>'required|in:support,billing,technical,sales','assigned_to'=>'nullable|exists:users,id','tags'=>'nullable|string|max:500']);$d['closed_at']=$d['status']==='closed'?now():null;$d['due_at']=$d['status']==='closed'?null:$this->due($d['priority']);$before=$ticket->only(['status','priority','department','assigned_to','tags']);$ticket->update($d);$ticket->events()->create(['user_id'=>$r->user()->id,'event'=>'updated','details'=>json_encode(['before'=>$before,'after'=>$d])]);return back()->with('success','Ticket opdateret.');}
 public function settings(Request $r){return view('admin.tickets.settings',['settings'=>['discord_webhook'=>SupportSetting::value('discord_webhook',''),'auto_assign'=>SupportSetting::value('auto_assign','1'),'sla_urgent'=>SupportSetting::value('sla_urgent','60'),'sla_high'=>SupportSetting::value('sla_high','240'),'sla_normal'=>SupportSetting::value('sla_normal','720'),'sla_low'=>SupportSetting::value('sla_low','1440')]]);}
 public function saveSettings(Request $r){$d=$r->validate(['discord_webhook'=>'nullable|url|max:1000','auto_assign'=>'nullable|boolean','sla_urgent'=>'required|integer|min:15|max:10080','sla_high'=>'required|integer|min:15|max:10080','sla_normal'=>'required|integer|min:15|max:10080','sla_low'=>'required|integer|min:15|max:10080']);foreach($d as $k=>$v)SupportSetting::put($k,(string)$v);SupportSetting::put('auto_assign',$r->boolean('auto_assign')?'1':'0');return back()->with('success','Support settings saved.');}
 public function attachment(SupportTicket $ticket,$attachment){$a=$ticket->attachments()->findOrFail($attachment);return Storage::disk($a->disk)->download($a->path,$a->original_name);}
}