import fs from 'node:fs';
import path from 'node:path';
import {Client,GatewayIntentBits,PermissionFlagsBits,SlashCommandBuilder,REST,Routes,EmbedBuilder} from 'discord.js';
const token=process.env.DISCORD_TOKEN; const clientId=process.env.DISCORD_CLIENT_ID; const guildId=process.env.DISCORD_GUILD_ID;
const configPath=process.env.NODEXA_MODULE_CONFIG||path.resolve('../panel/storage/app/nodexa/discord-bot-modules.json');
if(!token||!clientId||!guildId) throw new Error('DISCORD_TOKEN, DISCORD_CLIENT_ID and DISCORD_GUILD_ID are required');
const load=()=>{try{return JSON.parse(fs.readFileSync(configPath,'utf8')).moderation||{}}catch{return {}}};
const commands=[
 new SlashCommandBuilder().setName('warn').setDescription('Advar et medlem').addUserOption(o=>o.setName('user').setDescription('Medlem').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Årsag').setRequired(true)),
 new SlashCommandBuilder().setName('timeout').setDescription('Timeout et medlem').addUserOption(o=>o.setName('user').setDescription('Medlem').setRequired(true)).addIntegerOption(o=>o.setName('minutes').setDescription('Minutter').setMinValue(1).setMaxValue(40320).setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Årsag').setRequired(true)),
 new SlashCommandBuilder().setName('kick').setDescription('Kick et medlem').addUserOption(o=>o.setName('user').setDescription('Medlem').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Årsag').setRequired(true)),
 new SlashCommandBuilder().setName('ban').setDescription('Ban et medlem').addUserOption(o=>o.setName('user').setDescription('Medlem').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Årsag').setRequired(true)),
 new SlashCommandBuilder().setName('purge').setDescription('Slet beskeder').addIntegerOption(o=>o.setName('amount').setDescription('Antal').setMinValue(1).setMaxValue(100).setRequired(true)),
 new SlashCommandBuilder().setName('lock').setDescription('Lås kanalen'),new SlashCommandBuilder().setName('unlock').setDescription('Lås kanalen op')
].map(c=>c.setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers).toJSON());
const rest=new REST({version:'10'}).setToken(token); await rest.put(Routes.applicationGuildCommands(clientId,guildId),{body:commands});
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const spam=new Map(); let caseNo=Date.now()%1000000;
async function log(guild,title,description){const c=load(),id=c.case_log_channel_id||c.log_channel_id;if(!id)return;const ch=guild.channels.cache.get(id);if(ch?.isTextBased())await ch.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(description).setTimestamp()]});}
async function moderate(message,reason,action='delete'){if(message.deletable)await message.delete().catch(()=>{});await log(message.guild,'AutoMod',`${message.author.tag} (${message.author.id})\n${reason}\n#${message.channel.name}`);if(action==='timeout'&&message.member?.moderatable)await message.member.timeout(10*60*1000,reason).catch(()=>{});}
client.on('messageCreate',async m=>{if(!m.guild||m.author.bot)return;const c=load();if(!c.enabled||!c.automod_enabled)return;const text=m.content||'';const now=Date.now(),key=`${m.guild.id}:${m.author.id}`,arr=(spam.get(key)||[]).filter(t=>now-t<Number(c.spam_interval||5)*1000);arr.push(now);spam.set(key,arr);if(c.spam_enabled&&arr.length>Number(c.spam_limit||5))return moderate(m,'Spam/flood registreret','timeout');if(c.mention_enabled&&m.mentions.users.size>Number(c.mention_limit||5))return moderate(m,'For mange mentions');if(c.caps_enabled&&text.length>10){const letters=text.match(/[a-zæøå]/gi)||[],upper=text.match(/[A-ZÆØÅ]/g)||[];if(letters.length&&upper.length/letters.length*100>Number(c.caps_percent||75))return moderate(m,'CAPS filter');}if(c.invite_enabled&&/discord(?:\.gg|\.com\/invite)\//i.test(text))return moderate(m,'Discord invitation');const blocked=String(c.blocked_words||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(c.blacklist_enabled&&blocked.some(w=>text.toLowerCase().includes(w)))return moderate(m,'Blacklistet ord');if(c.scam_enabled&&/(free nitro|steam gift|claim.*gift|airdrop.*http)/i.test(text))return moderate(m,'Muligt scam/phishing');});
client.on('interactionCreate',async i=>{if(!i.isChatInputCommand())return;const c=load();if(!c.enabled)return i.reply({content:'Moderation er deaktiveret.',ephemeral:true});const reason=i.options.getString('reason')||'Ingen årsag angivet';try{if(i.commandName==='purge'){const n=i.options.getInteger('amount');await i.channel.bulkDelete(n,true);return i.reply({content:`Slettede op til ${n} beskeder.`,ephemeral:true});}if(i.commandName==='lock'||i.commandName==='unlock'){await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:i.commandName==='unlock'?null:false});await log(i.guild,'Kanal',`${i.user.tag} ${i.commandName==='lock'?'låste':'åbnede'} #${i.channel.name}`);return i.reply(`Kanalen er ${i.commandName==='lock'?'låst':'åbnet'}.`);}const user=i.options.getUser('user'),member=await i.guild.members.fetch(user.id);const id=`CASE-${String(++caseNo).padStart(6,'0')}`;if(c.dm_punishments)await user.send(`Nodexa moderation • ${id}\nÅrsag: ${reason}`).catch(()=>{});if(i.commandName==='warn'){await log(i.guild,`Warn • ${id}`,`${user.tag} blev advaret af ${i.user.tag}\nÅrsag: ${reason}`);}if(i.commandName==='timeout'){await member.timeout(i.options.getInteger('minutes')*60000,reason);await log(i.guild,`Timeout • ${id}`,`${user.tag} • ${reason}`);}if(i.commandName==='kick'){await member.kick(reason);await log(i.guild,`Kick • ${id}`,`${user.tag} • ${reason}`);}if(i.commandName==='ban'){await i.guild.members.ban(user,{reason});await log(i.guild,`Ban • ${id}`,`${user.tag} • ${reason}`);}return i.reply({content:`Udført • ${id}`,ephemeral:true});}catch(e){console.error(e);return i.replied?null:i.reply({content:'Handlingen kunne ikke udføres. Kontrollér bot-rolle og permissions.',ephemeral:true});}});
client.on('guildMemberAdd',async member=>{const c=load();if(!c.enabled||!c.antiraid_enabled)return;const age=(Date.now()-member.user.createdTimestamp)/3600000;if(age<Number(c.min_account_age_hours||0))await log(member.guild,'Anti-Raid',`Ny konto: ${member.user.tag} • ${age.toFixed(1)} timer gammel`);});
client.once('ready',()=>console.log(`Nodexa Moderation online as ${client.user.tag}`));client.login(token);
